const ar = {
  anasayfa: "الصفحة الرئيسية",
  apiKeys: "مفاتيح API الخاصة بي",
  addNew: "إضافة جديد",
  noApiKey: "لم يتم إضافة أي مفتاح API حتى الآن. يمكنك البدء باستخدام زر 'إضافة جديد'.",
  trades: "التداولات",
  signals: "الإشارات",
  channels: "القنوات",
  partnership: "الشراكة",
  subscription: "الاشتراك",
  adminLogin: "دخول المسؤول",
  loading: "جار التحميل...",
  telegramRequired: "يجب عليك تسجيل الدخول عبر Telegram لاستخدام هذا التطبيق.",
  goToTelegram: "اذهب إلى Telegram",
  dashboardTitle: "لوحة التحكم",
  lastUpdate: "آخر تحديث",
  activeSignals: "الإشارات النشطة",
  activeSignalsDesc: "إشارة للمعالجة",
  openTrades: "التداولات المفتوحة",
  openTradesDesc: "يمكنك تتبع تداولاتك الحالية هنا.",
  performance: "الأداء",
  performanceDesc: "الربح/الخسارة لمدة 30 يومًا",
  apiStatus: "حالة API",
  apiStatusDesc: "البورصة النشطة",
  son_islemler: "آخر التداولات",
  sizin_adiniza_gerceklesen_son_islemler: "آخر التداولات التي تمت نيابة عنك",
  signalsList: {
    title: "آخر الإشارات",
    description: "آخر إشارات التداول من القناة",
    viewAll: "عرض كل الإشارات ←"
  },
  buy: "شراء",
  sell: "بيع",
  unit: "وحدة",
  tradesList: { viewAll: "عرض كل التداولات ←" },
  entry: "دخول",
  usdt: "USDT",
  active: "نشط",
  filled: "مكتمل",
  cancelled: "ملغى",
  balanceChart: {
    title: "تطور الرصيد",
    balance: "الرصيد",
    description: "تغير محفظتك بمرور الوقت"
  },
  'backtest.title': 'اختبار رجعي',
  'backtest.channelSelect': 'اختيار القناة',
  'backtest.channelSelectDescription': 'اختر قناة الإشارات لاستخدامها في الاختبار الرجعي',
  'backtest.selectChannel': 'اختر قناة',
  'backtest.dateRange': 'نطاق التاريخ',
  'backtest.dateRangeDescription': 'اختر نطاق التاريخ للاختبار الرجعي',
  'backtest.selectDateRange': 'اختر نطاق التاريخ',
  'backtest.autoTrade': 'تداول آلي',
  'backtest.autoTradeDescription': 'تنفيذ الإشارات تلقائيًا',
  'backtest.entryAmount': 'مبلغ الدخول',
  'backtest.entryAmountDescription': 'المبلغ الذي سيتم استخدامه في كل صفقة',
  'backtest.enterAmount': 'أدخل المبلغ',
  'backtest.usdt': 'USDT',
  'backtest.howMuchToEnter': 'بكم دولار تريد الدخول في الصفقة؟',
  'backtest.enterAmountInfo1': 'اضرب المبلغ الذي تريد استثماره في نسبة الرافعة المالية التي حددتها وأدخل النتيجة كـ "لوت".',
  'backtest.enterAmountInfo2': 'مثال: إذا كنت تريد الدخول في صفقة بـ 20 دولارًا ورافعة مالية 20X: 20 × 20 = 400. في هذه الحالة ، يجب عليك كتابة 400 في قسم اللوت.',
  'backtest.leverage': 'الرافعة المالية',
  'backtest.leverageDescription': 'نسبة الرافعة المالية لصفقاتك',
  'backtest.safe': '1x (آمن)',
  'backtest.risky': '25x (محفوف بالمخاطر)',
  'backtest.tradeType': 'نوع الصفقة',
  'backtest.tradeTypeDescription': 'اختر نوع هامش الصفقة',
  'backtest.isolated': 'معزول',
  'backtest.cross': 'متقاطع',
  'backtest.profitTradeSettings': 'إعدادات جني الأرباح',
  'backtest.profitTradeSettingsDescription': 'اختر استراتيجية إغلاق الصفقة',
  'backtest.profitTradeSelect': 'اختر استراتيجية جني الأرباح',
  'backtest.closed': 'مغلق',
  'backtest.percentage': 'نسبة مئوية من الرصيد',
  'backtest.fixedAmount': 'مبلغ ثابت',
  'backtest.tp': 'TP',
  'backtest.tpLevel': 'مستوى TP',
  'backtest.stopLossSettings': 'إعدادات وقف الخسارة',
  'backtest.stopLossSettingsDescription': 'اختر الإجراء بعد وقف الخسارة',
  'backtest.actionSelect': 'اختر إجراءً',
  'backtest.trailStop': 'وقف الخسارة المتحرك',
  'backtest.costToWithdraw': 'السحب بالتكلفة',
  'backtest.specificLoss': 'إغلاق الصفقة عند خسارة معينة',
  'backtest.lossPercentage': 'إغلاق عند الخسارة (٪)',
  'backtest.specificLossInfo': 'ما هو "إغلاق الصفقة عند خسارة معينة"؟',
  'backtest.specificLossInfo1': 'تضمن هذه الميزة إغلاق صفقتك تلقائيًا عند وصولها إلى معدل خسارة معين.',
  'backtest.specificLossInfo2': 'على سبيل المثال ، إذا كنت تريد إغلاق المركز عندما تتكبد صفقتك خسارة بنسبة 10٪ مقارنة بسعر السوق الفوري ، فما عليك سوى إدخال 10٪ في الإعداد ذي الصلة.',
  'backtest.costToWithdrawDescription': 'اختر مستوى السحب بالتكلفة',
  'backtest.levelSelect': 'اختر المستوى',
  'backtest.none': 'لا شيء',
  'backtest.tp1': 'TP1',
  'backtest.tp2': 'TP2',
  'backtest.tp3': 'TP3',
  'backtest.tp4': 'TP4',
  'backtest.tp5': 'TP5',
  'backtest.costToWithdrawInfo': 'ما هو "السحب بالتكلفة"؟',
  'backtest.costToWithdrawInfo1': 'عند الوصول إلى مستوى جني الأرباح 1 أو 2 ، يتم نقل أمر وقف الخسارة إلى مستوى الدخول.',
  'backtest.costToWithdrawInfo2': 'بفضل هذا النظام ، تصبح إدارة المخاطر أكثر أمانًا مع حماية المكاسب.',
  'backtest.trailStopDescription': 'اختر مستوى وقف الخسارة المتحرك',
  'backtest.trailStopInfo': 'ما هو "وقف الخسارة المتحرك"؟',
  'backtest.trailStopInfo1': 'يسمح وقف الخسارة المتحرك لمستوى وقف الخسارة بالتحرك تلقائيًا لأعلى مع السعر كلما أصبحت صفقتك مربحة.',
  'backtest.trailStopInfo2': 'الهدف هو حماية الأرباح الحالية في حالة انعكاسات السوق.',
  'backtest.maxOrders': 'الحد الأقصى للطلبات',
  'backtest.maxOrdersDescription': 'حدد الحد الأقصى لعدد الطلبات',
  'backtest.startBacktest': 'بدء الاختبار الرجعي',
  'totalTrades': 'إجمالي الصفقات',
  'winRate': 'معدل الفوز',
  'totalPL': 'إجمالي الربح / الخسارة',
  'averageTrade': 'متوسط الصفقة',
  'openPositions': 'المراكز المفتوحة',
  'closedPositions': 'المراكز المغلقة',
  'cumulativeProfitLoss': 'الربح / الخسارة التراكمي',
  'profitLossPerChannel': 'الربح / الخسارة لكل واجهة برمجة تطبيقات بمرور الوقت',
  'notEnoughData': 'لا توجد بيانات كافية للرسم البياني.',
  'date': 'التاريخ',
  'previous': 'السابق',
  'next': 'التالي',
  'page': 'الصفحة',
  'trendDirection': 'اتجاه الترند',
  'symbol': "الزوج",
  'entry1': 'الدخول 1',
  'entry2': 'الدخول 2',
  'sl': 'SL',
  'tp1': 'TP1',
  'tp2': 'TP2',
  'tp3': 'TP3',
  'tp4': 'TP4',
  'tp5': 'TP5',
  'tp6': 'TP6',
  'tp7': 'TP7',
  'tp8': 'TP8',
  'tp9': 'TP9',
  'tp10': 'TP10',
  'entryPrice': "سعر الافتتاح",
  'entryDate': "تاريخ الافتتاح",
  'takeProfit': 'جني الأرباح',
  'exitPrice': 'سعر الإغلاق',
  'exitDate': 'تاريخ الإغلاق',
  'profitLoss': 'الربح / الخسارة',
  'allTime': 'كل الأوقات',
  'last24': 'آخر 24 ساعة',
  'last30': 'آخر 30 يومًا',
  'last7': 'آخر 7 أيام',
  'channelSelect': 'اختر قناة',
  'allChannels': 'كل القنوات',
  'timeSelect': 'اختر الوقت',
  'error': "خطأ",
  tradeHistory: 'سجل التداولات',
  totalPnL: 'إجمالي الربح / الخسارة',
  profitLossByApi: 'الربح / الخسارة حسب واجهة برمجة التطبيقات',
  tradeSearch: 'بحث عن صفقة ...',
  allExchanges: 'كل البورصات',
  realizedPnL: 'الربح / الخسارة المحقق',
  perCompletedTrade: 'لكل صفقة مكتملة',
  profitableTrades: 'صفقات مربحة',
  ticket: 'تذكرة',
  direction: "الاتجاه",
  openPrice: 'سعر الافتتاح',
  openTime: 'وقت الافتتاح',
  volume: 'الحجم',
  closePrice: 'سعر الإغلاق',
  closeTime: 'وقت الإغلاق',
  status: 'الحالة',
  completed: 'مكتمل',
  open: 'افتتاح',
  allTrades: 'كل الصفقات',
  'signals.title': 'الإشارات',
  'signals.activeSignals': 'الإشارات النشطة',
  'signals.signalHistory': 'سجل الإشارات',
  'signals.channel': 'القناة',
  'signals.symbol': 'الرمز',
  'signals.direction': 'الاتجاه',
  'signals.openPrice': 'افتتاح',
  'signals.openDate': 'تاريخ الافتتاح',
  'signals.closePrice': 'إغلاق',
  'signals.closeDate': 'تاريخ الإغلاق',
  'signals.stopLoss': 'وقف الخسارة',
  'signals.takeProfit': 'جني الأرباح',
  'signals.profitLoss': 'الربح / الخسارة',
  'signals.totalTrades': 'إجمالي الصفقات',
  'signals.winRate': 'معدل الفوز',
  'signals.totalPL': 'إجمالي الربح / الخسارة',
  'signals.avgTrade': 'متوسط الصفقة',
  'signals.openPositions': 'المراكز المفتوحة',
  'signals.closedPositions': 'المراكز المغلقة',
  'signals.cumulativePL': 'الربح / الخسارة التراكمي',
  'signals.plByChannel': 'الربح / الخسارة حسب القناة بمرور الوقت',
  'signals.noChartData': 'لا توجد بيانات كافية للرسم البياني.',
  'signals.channelName': 'اسم القناة:',
  'signals.trendDirection': 'اتجاه الترند:',
  'signals.entry1': 'الدخول 1:',
  'signals.entry2': 'الدخول 2:',
  'signals.sl': 'SL:',
  'signals.tp': 'TP',
  'backtest.noResults': 'لم يتم العثور على نتائج',
  'backtest.results': 'نتائج الاختبار الرجعي',
  'backtest.profitChart': 'مخطط الأرباح',
  'backtest.simulationTrades': 'صفقات المحاكاة',
  'backtest.lot': 'لوت',
  'retry': 'إعادة المحاولة',
  goBack: "رجوع",
  channelOwnerApply: "طلب مالك القناة",
  channelNamePlaceholder: "أدخل اسم القناة",
  channelLink: "رابط القناة",
  followerCount: "عدد المتابعين",
  fullName: "الاسم الكامل",
  email: "البريد الإلكتروني",
  phoneNumber: "رقم الهاتف",
  ownerTelegram: "اسم مستخدم Telegram",
  agreementAccept: "لقد قرأت اتفاقية الشراكة وأوافق عليها",
  submit: "إرسال",
  submitting: "جارٍ الإرسال ...",
  telegram_channels: "قنوات Telegram",
  total_signals: "إجمالي الإشارات",
  success_rate: "معدل النجاح",
  total_profit: "إجمالي الربح",
  subscribers: "عدد المشتركين",
  per_month: "شهر",
  channel_loading: "جارٍ تحميل معلومات القناة ...",
  channel_not_found: "لم يتم العثور على معلومات القناة",
  back_to_channels: "العودة إلى القنوات",
  no_channels_found: "لم يتم العثور على أي قنوات حتى الآن.",
  success: "نجاح",
  application_success: "تم إرسال طلبك بنجاح.",
  error_occurred: "حدث خطأ",
  accept_agreement_warning: "يرجى قبول اتفاقية الشراكة.",
  fill_all_fields_warning: "يرجى ملء جميع الحقول.",
  confirmation_title: 'تم تأكيد الطلب',
  confirmation_message: "تم استلام طلبك بنجاح. سنتصل بك في أقرب وقت ممكن.",
  confirmation_return: "العودة إلى الصفحة الرئيسية",
  go_to_channel: "اذهب إلى القناة",
  subscribe: "اشتراك",
  closed_signals: "الإشارات المغلقة",
  cumulative_profit_loss: "الربح / الخسارة التراكمي",
  profit_loss_per_channel: "الربح / الخسارة حسب القناة بمرور الوقت",
  total: "المجموع",
  openDate: "تاريخ الافتتاح",
  closeDate: "تاريخ الإغلاق",
  channelNameLabel: "اسم القناة",
  subscription_title: "الاشتراك",
  adminMenu: "قائمة المسؤول",
  members: "الأعضاء",
  memberNotifications: "إشعارات الأعضاء",
  channelNotifications: "إشعارات القناة",
  botChannels: {
    loadError: "فشل تحميل قنوات البوت",
    unknownDeleteError: "خطأ حذف غير معروف",
    deleteError: "فشل الحذف",
    deleteSuccess: "تم حذف قناة البوت بنجاح",
    deleteErrorDetailed: "خطأ أثناء حذف قناة البوت: {{error}}",
    channelId: "معرف القناة",
    channelName: "اسم القناة",
    status: "الحالة",
    actions: "الإجراءات",
    admin: "مسؤول",
    description: "الوصف",
    registerDate: "تاريخ التسجيل",
    channelImageAlt: "صورة القناة",
    title: "قنوات البوت",
    addChannel: "إضافة قناة",
    pageDescription: "يمكنك عرض وإدارة قنوات الروبوت المسجلة في النظام.",
    searchPlaceholder: "ابحث باسم القناة أو المعرف ...",
    deleteConfirmTitle: "تأكيد حذف قناة البوت",
    deleteConfirmDesc: "هل أنت متأكد من أنك تريد حذف قناة البوت هذه نهائيًا؟",
    confirmDelete: "نعم ، احذف",
  },
  subscriptions: "الاشتراكات",
  subscriptionPackages: "باقات الاشتراك",
  'signalsList.title': "آخر الإشارات",
  'signalsList.description': "آخر إشارات التداول من القناة",
  'signalsList.viewAll': "عرض كل الإشارات ←",
  'tradesList.viewAll': "عرض كل الصفقات ←",
  subscriptionHistory: "سجل الاشتراك",
  allActiveAndPastSubscriptions: "جميع اشتراكاتك النشطة والسابقة",
  ended: "انتهى",
  start: "بداية",
  end: "نهاية",
  noSubscriptionFound: "ليس لديك اشتراك بعد.",
  upgradeToPremium: "الترقية إلى بريميوم",
  monthlyPlan: "شهري",
  monthlyAccess: "وصول بريميوم لمدة شهر",
  selectPlan: "اختر الباقة",
  enterPassword: "أدخل كلمة المرور",
  login: "تسجيل الدخول",
  // الميزات
  'Tüm sinyallere erişim': "الوصول إلى جميع الإشارات",
  'Manuel trading': "تداول يدوي",
  'Temel destek': "دعم أساسي",
  'Tanışma Paketi': "باقة ترحيبية",
  'Öncelikli destek': "دعم ذو أولوية",
  '3 aylık indirim': "خصم لمدة 3 أشهر",
  'Premium destek': "دعم بريميوم",
  '6 aylık indirim': "خصم لمدة 6 أشهر",
  'VIP destek': "دعم VIP",
  'Yıllık indirim': "خصم سنوي",
  threeMonthPlan: "3 أشهر",
  sixMonthPlan: "6 أشهر",
  yearlyPlan: "سنوي",
  premiumAccess: "وصول بريميوم لمدة",
  accessAllSignals: "الوصول إلى جميع الإشارات",
  manualTrading: "تداول يدوي",
  basicSupport: "دعم أساسي",
  welcomePackage: "باقة ترحيبية",
  prioritySupport: "دعم ذو أولوية",
  threeMonthDiscount: "خصم لمدة 3 أشهر",
  premiumSupport: "دعم بريميوم",
  sixMonthDiscount: "خصم لمدة 6 أشهر",
  vipSupport: "دعم VIP",
  annualDiscount: "خصم سنوي",
  'settings.title': 'إعدادات API',
  'settings.invalidId': 'معرف غير صالح',
  'settings.apiNotFound': 'لم يتم العثور على API',
  'settings.loadingError': 'خطأ في التحميل',
  'settings.missingApiId': 'معرف API مفقود',
  'settings.autoTrade': 'صفقة تلقائية',
  'settings.autoTradeDescription': 'تفعيل ميزة التداول التلقائي',
  'settings.entryAmount': 'مبلغ الصفقة',
  'settings.entryAmountDescription': 'المبلغ الذي سيتم استخدامه في كل صفقة',
  'settings.entryAmountPlaceholder': 'أدخل المبلغ',
  'settings.usdt': 'USDT',
  'settings.entryAmountQuestion': 'كم يجب أن يكون مبلغ الصفقة؟',
  'settings.entryAmountExplanation1': 'هذا المبلغ هو المبلغ المبدئي الذي سيتم استخدامه في كل صفقة.',
  'settings.entryAmountExplanation2': 'سيتغير حجم المركز وفقًا لنسبة الرافعة المالية.',
  'settings.leverage': 'الرافعة المالية',
  'settings.leverageDescription': 'نسبة الرافعة المالية التي ستستخدم في صفقاتك',
  'settings.safe': 'آمن',
  'settings.risky': 'محفوف بالمخاطر',
  'settings.tradeType': 'نوع الصفقة',
  'settings.tradeTypeDescription': 'نوع الهامش الذي سيستخدم في صفقاتك',
  'settings.isolated': 'معزول',
  'settings.cross': 'متقاطع',
  'settings.profitTradeSettings': 'إعدادات جني الأرباح',
  'settings.profitTradeSettingsDescription': 'مستويات واستراتيجيات جني الأرباح',
  'settings.selectEntryType': 'اختر نوع الدخول',
  'settings.closed': 'مغلق',
  'settings.percentage': 'نسبة مئوية',
  'settings.fixedAmount': 'مبلغ ثابت',
  'settings.percentSymbol': '٪',
  'settings.tp1': 'TP1',
  'settings.tp2': 'TP2',
  'settings.tp3': 'TP3',
  'settings.tp4': 'TP4',
  'settings.tp5': 'TP5',
  'settings.tp6': 'TP6',
  'settings.tp7': 'TP7',
  'settings.tp8': 'TP8',
  'settings.tp9': 'TP9',
  'settings.tp10': 'TP10',
  'settings.tpLevel': 'مستوى TP',
  'settings.stoplossTradeSettings': 'إعدادات وقف الخسارة',
  'settings.stoplossTradeSettingsDescription': 'مستويات واستراتيجيات وقف الخسارة',
  'settings.selectStopLossStrategy': 'اختر استراتيجية وقف الخسارة',
  'settings.useSignalSL': 'استخدام SL للإشارة',
  'settings.customStopLoss': 'وقف خسارة مخصص',
  'settings.customStopLossInput': 'مستوى وقف الخسارة',
  'settings.customStopLossHelp': 'مستوى وقف الخسارة بالنسبة المئوية بناءً على سعر فتح المركز',
  'settings.stopLossActionSettings': 'إعدادات إجراء وقف الخسارة',
  'settings.stopLossActionDescription': 'الإجراءات التي يجب اتخاذها عند تفعيل وقف الخسارة',
  'settings.selectAction': 'اختر إجراءً',
  'settings.trailStopAction': 'وقف الخسارة المتحرك',
  'settings.costWithdrawAction': 'السحب بالتكلفة',
  'settings.specificLossAction': 'إغلاق عند خسارة معينة',
  'settings.specificLossLabel': 'نسبة الخسارة',
  'settings.specificLossQuestion': 'كيف تعمل هذه الميزة؟',
  'settings.specificLossExplanation': 'يتم إغلاق المركز تلقائيًا عند الوصول إلى نسبة الخسارة المحددة.',
  'settings.costWithdraw': 'السحب بالتكلفة',
  'settings.costWithdrawDescription': 'نقل مستوى وقف الخسارة إلى نقطة التعادل عند الوصول إلى هدف الربح',
  'settings.selectLevel': 'اختر المستوى',
  'settings.none': 'لا شيء',
  'settings.costWithdrawQuestion': 'كيف يعمل السحب بالتكلفة؟',
  'settings.costWithdrawExplanation1': 'عند الوصول إلى مستوى TP المحدد ، يتم نقل مستوى وقف الخسارة إلى نقطة التعادل.',
  'settings.costWithdrawExplanation2': 'بهذه الطريقة ، في أسوأ الحالات ، تصل إلى نقطة التعادل.',
  'settings.costWithdrawExplanation3': 'إذا انعكس السوق ، يتم حماية الربح.',
  'settings.costWithdrawExplanation4': 'إنها استراتيجية مهمة لإدارة المخاطر.',
  'settings.trailStop': 'وقف الخسارة المتحرك',
  'settings.trailStopDescription': 'نقل مستوى وقف الخسارة تلقائيًا لأعلى',
  'settings.trailStopQuestion': 'كيف يعمل وقف الخسارة المتحرك؟',
  'settings.trailStopExplanation': 'عند الوصول إلى مستوى TP المحدد ، يتم نقل وقف الخسارة تلقائيًا إلى منطقة الربح ويستمر في الارتفاع مع ارتفاع السعر.',
  'settings.maxOrders': 'الحد الأقصى للطلبات',
  'settings.maxOrdersDescription': 'الحد الأقصى لعدد الطلبات التي يمكن فتحها في وقت واحد',
  'settings.save': 'حفظ',
  'settings.saving': 'جارٍ الحفظ ...',
  'settings.saveSuccess': 'تم حفظ الإعدادات بنجاح.',
  'settings.saveError': 'حدث خطأ أثناء حفظ الإعدادات.',
  addSignal: 'إضافة إشارة',
  addNewSignal: 'إضافة إشارة جديدة',
  fillSignalDetails: 'املأ تفاصيل الإشارة',
  exchange: "بورصة",
  side: "اتجاه",
  pnl: "الربح / الخسارة",
  action: "إجراء",
  close: "إغلاق",
  trend: 'ترند',
  selectTrend: 'اختر ترند',
  long: "طويل",
  short: "قصير",
  stopLossPercentage: 'نسبة وقف الخسارة',
  entryRangePercentage: 'نسبة نطاق الدخول',
  takeProfitCount: 'عدد جني الأرباح',
  takeProfitRangePercentage: 'نسبة نطاق جني الأرباح',
  createSignal: 'إنشاء إشارة',
  signal_channels: "قنوات الإشارات",
  addYourChannel: "أضف قناتك",
  welcomeMessage: "مرحبًا بك ،",
  openTradesLabel: "صفقات جارية",
  apiStatusLabel: "حسابات بورصة متصلة",
  addApiKey: "إضافة مفتاح API",
  noApiKeyCta: "ليس لديك مفتاح API حتى الآن. انقر لتوصيل حساب البورصة الخاص بك.",
  noOpenTrades: "لا توجد صفقات مفتوحة",
  waiting: 'في الانتظار',
  openStatus: "مفتوح",
  recentTrades: "الصفقات الأخيرة",
  yourRecentTrades: "أحدث صفقاتك",
  openClose: "فتح / إغلاق",
  noTradesFound: "لم يتم العثور على صفقات",
  unknown: 'غير معروف',
  closed: 'مغلق',
  loginError: "خطأ في تسجيل الدخول",
  loginWithTelegram: "تسجيل الدخول باستخدام Telegram",
  pleaseLoginWithTelegram: "يرجى تسجيل الدخول عبر Telegram.",
  pageNotFound: "عفوًا! الصفحة غير موجودة",
  returnToHome: "العودة إلى الصفحة الرئيسية",
  copied: "تم النسخ",
  copiedToClipboard: "تم نسخ {{field}} إلى الحافظة.",
  copyError: "فشل النسخ.",
  fillAllFields: "يرجى ملء جميع الحقول.",
  sessionNotFound: "لم يتم العثور على معلومات الجلسة",
  userNotFound: "لم يتم العثور على المستخدم",
  newApiKey: "مفتاح API جديد:",
  addApiKeyError: "تعذر إضافة مفتاح API",
  newApiKeyNotFound: "لم يتم العثور على مفتاح API جديد",
  apiKeyAdded: 'تمت إضافة مفتاح API "{{name}}" بنجاح.',
  apiKeyAddError: "خطأ أثناء إضافة مفتاح API:",
  addNewApiKey: "إضافة مفتاح API جديد",
  addNewApiKeyDesc: "أدخل معلومات مفتاح API الخاص بالبورصة هنا. سيتم استخدام هذه المعلومات للمعاملات التلقائية.",
  exchangeType: "نوع البورصة",
  name: "الاسم",
  apiKeyNamePlaceholder: "مثال: Binance Futures",
  apiKeyNameDesc: "أدخل اسمًا لمساعدتك على تذكر هذا المفتاح.",
  apiKeyPlaceholder: "أدخل مفتاح API الخاص بك",
  apiSecretPlaceholder: "أدخل سر API الخاص بك",
  apiSecretDesc: "لا تشارك مفتاح API والسر الخاص بك مع أي شخص.",
  signalChannel: "قناة الإشارات",
  searchChannelPlaceholder: "ابحث باسم القناة أو المعرف ...",
  selectedChannel: "القناة المحددة",
  subscriptionPackage: "باقة الاشتراك",
  select: "اختر",
  cancel: "إلغاء",
  adding: "جارٍ الإضافة ...",
  save: "حفظ",
  apiKeyIdNotFound: "لم يتم العثور على معرف مفتاح API",
  apiKeyNotFound: "لم يتم العثور على مفتاح API",
  apiKeyLoadError: "خطأ أثناء تحميل مفتاح API:",
  apiKeyLoadErrorText: "فشل تحميل مفتاح API",
  apiKeyUpdated: 'تم تحديث مفتاح API "{{name}}" بنجاح.',
  apiKeyUpdateError: "خطأ أثناء تحديث مفتاح API:",
  apiKeyUpdateErrorText: "فشل تحديث مفتاح API.",
  editApiKey: "تعديل مفتاح API",
  editApiKeyDesc: "قم بتحديث معلومات مفتاح API الخاص بالبورصة.",
  saving: "جارٍ الحفظ ...",
  apiChannelDesc: "اختر قناة الإشارات التي سيستمع إليها مفتاح API.",
  deleteApiKeyConfirm: "هل أنت متأكد من أنك تريد حذف مفتاح API هذا؟",
  apiKeyDeleted: "تم حذف مفتاح API بنجاح.",
  apiKeyDeleteError: "حدث خطأ أثناء حذف مفتاح API.",
  networkError: "لم تكن استجابة الشبكة جيدة",
  fetchDetailsError: "فشل في جلب التفاصيل",
  deleteFailed: "فشل الحذف",
  apiKeyDeletedSuccess: "تم حذف مفتاح API بنجاح",
  adminApiKeys: {
    title: "مفاتيح API",
    description: "يمكنك عرض وإدارة مفاتيح API الخاصة بالمستخدمين.",
    searchPlaceholder: "ابحث باسم المستخدم أو الاسم ...",
    user: "المستخدم",
    apiName: "اسم API",
    apiType: "نوع API",
    packageEnd: "نهاية الباقة",
    channel: "القناة",
    packageStart: "بداية الباقة",
    lotsize: "حجم اللوت",
    leverage: "الرافعة المالية",
    marginType: "نوع الهامش",
    maxOrders: "الحد الأقصى للطلبات",
    autoTrade: "تداول آلي",
    actions: "الإجراءات",
    deleteConfirmTitle: "تأكيد الحذف",
    deleteConfirmDesc: "هل أنت متأكد من أنك تريد حذف مفتاح API هذا نهائيًا؟ هذا الإجراء لا رجعة فيه.",
  },
  on: "تشغيل",
  off: "إيقاف",
  delete: "حذف",
  edit: "تعديل",
  admin: {
    notLoggedIn: "لم تقم بتسجيل الدخول كمسؤول أو انتهت صلاحية جلستك. يرجى تسجيل الدخول مرة أخرى.",
    faq: {
      addSuccess: "تمت إضافة السؤال بنجاح!",
      addError: "فشل في إضافة السجل",
      addNewTitle: "إضافة سؤال جديد",
      addNewDesc: "يمكنك إضافة سؤال جديد متكرر.",
      questionInfo: "معلومات السؤال",
      question: "السؤال",
      questionPlaceholder: "اكتب السؤال ...",
      answer: "الإجابة",
      answerPlaceholder: "اكتب الإجابة ...",
    }
  },
  fromLastMonth: "مقارنة بالشهر الماضي",
  newTrades: "صفقة جديدة",
  thisMonth: "هذا الشهر",
  dashboard: "لوحة التحكم",
  switchToLightMode: "التبديل إلى الوضع الفاتح",
  switchToDarkMode: "التبديل إلى الوضع الداكن",
  noTradeOnPage: "لا توجد صفقات لعرضها في هذه الصفحة.",
  tradeRecordNotFound: "لم يتم العثور على سجل التداول.",
  previousPage: "الصفحة السابقة",
  nextPage: "الصفحة التالية",
  filterByExchange: "تصفية حسب البورصة",
  profit: "ربح",
  "faq.title": "الأسئلة الشائعة",
  tradeStatus: {
    waiting: "في الانتظار",
    open: "مفتوح",
    completed: "مكتمل",
    failed: "فشل",
    unknown: "غير معروف"
  },
  orderError: "خطأ في الأمر: {{error}}",
};

export default ar; 