const de = {
  anasayfa: "Startseite",
  apiKeys: "Meine API-Schlüssel",
  addNew: "Neu hinzufügen",
  noApiKey: "Noch kein API-Schlüssel hinzugefügt. Sie können mit der Schaltfläche 'Neu hinzufügen' beginnen.",
  trades: "Handel",
  signals: "Signale",
  channels: "Kanäle",
  partnership: "Partnerschaft",
  subscription: "Abonnement",
  adminLogin: "Admin-Anmeldung",
  loading: "Wird geladen...",
  telegramRequired: "Sie müssen sich über Telegram anmelden, um diese Anwendung zu nutzen.",
  goToTelegram: "Gehe zu Telegram",
  dashboardTitle: "Dashboard",
  lastUpdate: "Letzte Aktualisierung",
  activeSignals: "Aktive Signale",
  activeSignalsDesc: "Zu verarbeitendes Signal",
  openTrades: "Offene Handel",
  openTradesDesc: "Hier können Sie Ihre laufenden Handel überwachen.",
  performance: "Leistung",
  performanceDesc: "30-Tage G/V",
  apiStatus: "API-Status",
  apiStatusDesc: "Aktive Börse",
  son_islemler: "Letzte Handel",
  sizin_adiniza_gerceklesen_son_islemler: "Letzte Handel, die in Ihrem Namen getätigt wurden",
  signalsList: {
    title: "Letzte Signale",
    description: "Letzte Handelssignale aus dem Kanal",
    viewAll: "Alle Signale anzeigen →"
  },
  buy: "KAUFEN",
  sell: "VERKAUFEN",
  unit: "Einheit",
  tradesList: { viewAll: "Alle Handel anzeigen →" },
  entry: "Eintritt",
  usdt: "USDT",
  active: "AKTIV",
  filled: "GEFÜLLT",
  cancelled: "STORNIERT",
  balanceChart: {
    title: "Kontostandsverlauf",
    balance: "Kontostand",
    description: "Die Veränderung Ihres Portfolios im Laufe der Zeit"
  },
  'backtest.title': 'Backtest',
  'backtest.channelSelect': 'Kanalauswahl',
  'backtest.channelSelectDescription': 'Wählen Sie den Signalkanal für den Backtest aus',
  'backtest.selectChannel': 'Kanal auswählen',
  'backtest.dateRange': 'Datumsbereich',
  'backtest.dateRangeDescription': 'Wählen Sie den Datumsbereich für den Backtest aus',
  'backtest.selectDateRange': 'Datumsbereich auswählen',
  'backtest.autoTrade': 'Automatischer Handel',
  'backtest.autoTradeDescription': 'Signale automatisch verarbeiten',
  'backtest.entryAmount': 'Einstiegsbetrag',
  'backtest.entryAmountDescription': 'Betrag, der für jeden Handel verwendet werden soll',
  'backtest.enterAmount': 'Betrag eingeben',
  'backtest.usdt': 'USDT',
  'backtest.howMuchToEnter': 'Mit wie vielen Dollar möchten Sie in den Handel einsteigen?',
  'backtest.enterAmountInfo1': 'Multiplizieren Sie den Betrag, den Sie eingeben möchten, mit dem von Ihnen gewählten Hebel und geben Sie das Ergebnis als Losgröße ein.',
  'backtest.enterAmountInfo2': 'Beispiel: Wenn Sie mit 20 $ und 20-fachem Hebel in einen Handel einsteigen möchten: 20 × 20 = 400. In diesem Fall sollten Sie 400 im Los-Abschnitt eingeben.',
  'backtest.leverage': 'Hebel',
  'backtest.leverageDescription': 'Hebelverhältnis für Ihre Handel',
  'backtest.safe': '1x (Sicher)',
  'backtest.risky': '25x (Riskant)',
  'backtest.tradeType': 'Handelsart',
  'backtest.tradeTypeDescription': 'Wählen Sie die Handelsmargenart aus',
  'backtest.isolated': 'ISOLIERT',
  'backtest.cross': 'CROSS',
  'backtest.profitTradeSettings': 'Gewinnmitnahme-Einstellungen',
  'backtest.profitTradeSettingsDescription': 'Wählen Sie die Strategie zum Schließen von Positionen',
  'backtest.profitTradeSelect': 'Gewinnmitnahmestrategie auswählen',
  'backtest.closed': 'Geschlossen',
  'backtest.percentage': 'Prozentsatz des Guthabens',
  'backtest.fixedAmount': 'Fester Betrag',
  'backtest.tp': 'TP',
  'backtest.tpLevel': 'TP-Niveau',
  'backtest.stopLossSettings': 'Stop-Loss-Einstellungen',
  'backtest.stopLossSettingsDescription': 'Wählen Sie die Aktion nach dem Stop',
  'backtest.actionSelect': 'Aktion auswählen',
  'backtest.trailStop': 'TrailStop',
  'backtest.costToWithdraw': 'Auf Einstand ziehen',
  'backtest.specificLoss': 'Bei bestimmtem Verlust schließen',
  'backtest.lossPercentage': 'Bei Verlust schließen (%)',
  'backtest.specificLossInfo': 'Was bedeutet "Bei bestimmtem Verlust schließen"?',
  'backtest.specificLossInfo1': 'Diese Funktion schließt Ihren Handel automatisch, wenn er einen bestimmten Verlustprozentsatz erreicht.',
  'backtest.specificLossInfo2': 'Wenn Sie beispielsweise möchten, dass die Position geschlossen wird, wenn sie einen Verlust von 10 % im Verhältnis zum Spotpreis aufweist, müssen Sie nur 10 % in die entsprechende Einstellung eingeben.',
  'backtest.costToWithdrawDescription': 'Wählen Sie das Niveau für "Auf Einstand ziehen"',
  'backtest.levelSelect': 'Niveau auswählen',
  'backtest.none': 'Keine',
  'backtest.tp1': 'TP1',
  'backtest.tp2': 'TP2',
  'backtest.tp3': 'TP3',
  'backtest.tp4': 'TP4',
  'backtest.tp5': 'TP5',
  'backtest.costToWithdrawInfo': 'Was bedeutet "Auf Einstand ziehen"?',
  'backtest.costToWithdrawInfo1': 'Wenn Gewinnmitnahme-Niveau 1 oder 2 erreicht ist, wird der Stop-Loss-Auftrag auf das Einstiegsniveau verschoben.',
  'backtest.costToWithdrawInfo2': 'Mit diesem System wird das Risikomanagement sicherer, während Gewinne geschützt werden.',
  'backtest.trailStopDescription': 'Wählen Sie das TrailStop-Niveau',
  'backtest.trailStopInfo': 'Was ist ein Trail Stop?',
  'backtest.trailStopInfo1': 'Ein Trail Stop ermöglicht es, dass das Stop-Loss-Niveau automatisch mit dem Preis nach oben verschoben wird, wenn Ihr Handel profitabel wird.',
  'backtest.trailStopInfo2': 'Das Ziel ist es, bestehende Gewinne bei Marktumkehrungen zu schützen.',
  'backtest.maxOrders': 'Max. Auftragsmenge',
  'backtest.maxOrdersDescription': 'Legen Sie die maximale Anzahl von Aufträgen fest',
  'backtest.startBacktest': 'Backtest starten',
  totalTrades: 'Gesamte Handel',
  winRate: 'Gewinnrate',
  totalPL: 'Gesamt G/V',
  averageTrade: 'Durchschnittlicher Handel',
  openPositions: 'Offene Positionen',
  closedPositions: 'Geschlossene Positionen',
  cumulativeProfitLoss: 'Kumulativer Gewinn/Verlust',
  profitLossPerChannel: 'G/V nach API im Zeitverlauf',
  notEnoughData: 'Nicht genügend Daten für das Diagramm.',
  date: 'Datum',
  previous: 'Vorherige',
  next: 'Nächste',
  page: 'Seite',
  trendDirection: 'Trendrichtung',
  symbol: "Symbol",
  entry1: 'Einstieg 1',
  entry2: 'Einstieg 2',
  sl: 'SL',
  tp1: 'TP1',
  tp2: 'TP2',
  tp3: 'TP3',
  tp4: 'TP4',
  tp5: 'TP5',
  tp6: 'TP6',
  tp7: 'TP7',
  tp8: 'TP8',
  tp9: 'TP9',
  tp10: 'TP10',
  entryPrice: "Einstiegspreis",
  entryDate: "Einstiegsdatum",
  takeProfit: 'Gewinnmitnahme',
  exitPrice: 'Ausstiegspreis',
  exitDate: 'Ausstiegsdatum',
  profitLoss: 'Gewinn/Verlust',
  allTime: 'Alle Zeiten',
  last24: 'Letzte 24 Stunden',
  last30: 'Letzte 30 Tage',
  last7: 'Letzte 7 Tage',
  channelSelect: 'Kanal auswählen',
  allChannels: 'Alle Kanäle',
  timeSelect: 'Zeit auswählen',
  error: "Fehler",
  tradeHistory: 'Handelsverlauf',
  totalPnL: 'Gesamt G/V',
  profitLossByApi: 'G/V nach API',
  tradeSearch: 'Handel suchen...',
  allExchanges: 'Alle Börsen',
  realizedPnL: 'Realisierter G/V',
  perCompletedTrade: 'pro abgeschlossenem Handel',
  profitableTrades: 'Profitable Handel',
  ticket: 'Ticket',
  direction: "Richtung",
  openPrice: 'Eröffnungskurs',
  openTime: 'Eröffnungszeit',
  volume: 'Volumen',
  closePrice: 'Schlusskurs',
  closeTime: 'Schlusszeit',
  status: 'Status',
  completed: 'Abgeschlossen',
  open: "Öffnen",
  allTrades: 'Alle Handel',
  'signals.title': 'Signale',
  'signals.activeSignals': 'Aktive Signale',
  'signals.signalHistory': 'Signalverlauf',
  'signals.channel': 'Kanal',
  'signals.symbol': 'Symbol',
  'signals.direction': 'Richtung',
  'signals.openPrice': 'Eröffnungskurs',
  'signals.openDate': 'Eröffnungsdatum',
  'signals.closePrice': 'Schlusskurs',
  'signals.closeDate': 'Schlussdatum',
  'signals.stopLoss': 'Stop-Loss',
  'signals.takeProfit': 'Gewinnmitnahme',
  'signals.profitLoss': 'Gewinn/Verlust',
  'signals.totalTrades': 'GESAMTE HANDEL',
  'signals.winRate': 'GEWINNRATE',
  'signals.totalPL': 'GESAMT G/V',
  'signals.avgTrade': 'DURCHSCHNITTLICHER HANDEL',
  'signals.openPositions': 'Offene Positionen',
  'signals.closedPositions': 'Geschlossene Positionen',
  'signals.cumulativePL': 'Kumulativer G/V',
  'signals.plByChannel': 'G/V nach Kanal im Zeitverlauf',
  'signals.noChartData': 'Nicht genügend Daten für das Diagramm.',
  'signals.channelName': 'Kanalname:',
  'signals.trendDirection': 'Trendrichtung:',
  'signals.entry1': 'Einstieg 1:',
  'signals.entry2': 'Einstieg 2:',
  'signals.sl': 'SL:',
  'signals.tp': 'TP',
  'backtest.noResults': 'Keine Ergebnisse gefunden',
  'backtest.results': 'Backtest-Ergebnisse',
  'backtest.profitChart': 'Gewinndiagramm',
  'backtest.simulationTrades': 'Simulationshandel',
  'backtest.lot': 'Lot',
  retry: 'Wiederholen',
  goBack: "Zurück",
  channelOwnerApply: "Kanalinhaber-Bewerbung",
  channelNamePlaceholder: "Kanalnamen eingeben",
  channelLink: "Kanal-Link",
  followerCount: "Follower-Anzahl",
  fullName: "Vollständiger Name",
  email: "E-Mail",
  phoneNumber: "Telefonnummer",
  ownerTelegram: "Telegram-Benutzername",
  agreementAccept: "Ich habe die Partnerschaftsvereinbarung gelesen und akzeptiere sie",
  submit: "Senden",
  submitting: "Wird gesendet...",
  telegram_channels: "Telegram-Kanäle",
  total_signals: "Gesamtsignale",
  success_rate: "Erfolgsrate",
  total_profit: "Gesamtgewinn",
  subscribers: "Abonnenten",
  per_month: "Monat",
  channel_loading: "Kanalinformationen werden geladen...",
  channel_not_found: "Kanalinformationen nicht gefunden",
  back_to_channels: "Zurück zu den Kanälen",
  no_channels_found: "Noch keine Kanäle gefunden.",
  success: "Erfolg",
  application_success: "Ihre Bewerbung wurde erfolgreich übermittelt.",
  error_occurred: "Ein Fehler ist aufgetreten",
  accept_agreement_warning: "Bitte akzeptieren Sie die Partnerschaftsvereinbarung.",
  fill_all_fields_warning: "Bitte füllen Sie alle Felder aus.",
  confirmation_title: "Bewerbung bestätigt",
  confirmation_message: "Ihre Bewerbung wurde erfolgreich empfangen. Wir werden uns so schnell wie möglich mit Ihnen in Verbindung setzen.",
  confirmation_return: "Zurück zur Startseite",
  go_to_channel: "Gehe zum Kanal",
  subscribe: "Abonnieren",
  closed_signals: "Geschlossene Signale",
  cumulative_profit_loss: "Kumulativer Gewinn/Verlust",
  profit_loss_per_channel: "G/V nach Kanal im Zeitverlauf",
  total: "Gesamt",
  openDate: "Eröffnungsdatum",
  closeDate: "Schlussdatum",
  channelNameLabel: "Kanalname",
  subscription_title: "Abonnement",
  adminMenu: "Admin-Menü",
  members: "Mitglieder",
  memberNotifications: "Mitgliederbenachrichtigungen",
  channelNotifications: "Kanalbenachrichtigungen",
  botChannels: {
    loadError: "Bot-Kanäle konnten nicht geladen werden",
    unknownDeleteError: "Unbekannter Löschfehler",
    deleteError: "Löschvorgang fehlgeschlagen",
    deleteSuccess: "Bot-Kanal erfolgreich gelöscht",
    deleteErrorDetailed: "Fehler beim Löschen des Bot-Kanals: {{error}}",
    channelId: "Kanal-ID",
    channelName: "Kanalname",
    status: "Status",
    actions: "Aktionen",
    admin: "Admin",
    description: "Beschreibung",
    registerDate: "Registrierungsdatum",
    channelImageAlt: "Kanalbild",
    title: "Bot-Kanäle",
    addChannel: "Kanal hinzufügen",
    pageDescription: "Registrierte Bot-Kanäle im System anzeigen und verwalten.",
    searchPlaceholder: "Nach Kanalnamen oder ID suchen...",
    deleteConfirmTitle: "Löschen des Bot-Kanals bestätigen",
    deleteConfirmDesc: "Sind Sie sicher, dass Sie diesen Bot-Kanal dauerhaft löschen möchten?",
    confirmDelete: "Ja, löschen",
  },
  subscriptions: "Abonnements",
  subscriptionPackages: "Abonnementpakete",
  'signalsList.title': "Letzte Signale",
  'signalsList.description': "Letzte Handelssignale aus dem Kanal",
  'signalsList.viewAll': "Alle Signale anzeigen →",
  'tradesList.viewAll': "Alle Handel anzeigen →",
  subscriptionHistory: "Abonnementverlauf",
  allActiveAndPastSubscriptions: "Alle Ihre aktiven und vergangenen Abonnements",
  ended: "Beendet",
  start: "Start",
  end: "Ende",
  noSubscriptionFound: "Sie haben noch kein Abonnement.",
  upgradeToPremium: "Auf Premium upgraden",
  monthlyPlan: "Monatlich",
  monthlyAccess: "Premium-Zugang für einen Monat",
  selectPlan: "Paket auswählen",
  enterPassword: "Passwort eingeben",
  login: "Anmelden",
  'Tüm sinyallere erişim': "Zugang zu allen Signalen",
  'Manuel trading': "Manueller Handel",
  'Temel destek': "Grundlegender Support",
  'Tanışma Paketi': "Willkommenspaket",
  'Öncelikli destek': "Vorrangiger Support",
  '3 aylık indirim': "3-Monats-Rabatt",
  'Premium destek': "Premium-Support",
  '6 aylık indirim': "6-Monats-Rabatt",
  'VIP destek': "VIP-Support",
  'Yıllık indirim': "Jährlicher Rabatt",
  threeMonthPlan: "3-Monats",
  sixMonthPlan: "6-Monats",
  yearlyPlan: "Jährlich",
  premiumAccess: "Premium-Zugang für",
  accessAllSignals: "Zugang zu allen Signalen",
  manualTrading: "Manueller Handel",
  basicSupport: "Grundlegender Support",
  welcomePackage: "Willkommenspaket",
  prioritySupport: "Vorrangiger Support",
  threeMonthDiscount: "3-Monats-Rabatt",
  premiumSupport: "Premium-Support",
  sixMonthDiscount: "6-Monats-Rabatt",
  vipSupport: "VIP-Support",
  annualDiscount: "Jährlicher Rabatt",
  'settings.title': 'API-Einstellungen',
  'settings.invalidId': 'Ungültige ID',
  'settings.apiNotFound': 'API nicht gefunden',
  'settings.loadingError': 'Ladefehler',
  'settings.missingApiId': 'API-ID fehlt',
  'settings.autoTrade': 'Automatischer Handel',
  'settings.autoTradeDescription': 'Funktion für automatischen Handel aktivieren',
  'settings.entryAmount': 'Handelsbetrag',
  'settings.entryAmountDescription': 'Betrag, der für jeden Handel verwendet werden soll',
  'settings.entryAmountPlaceholder': 'Betrag eingeben',
  'settings.usdt': 'USDT',
  'settings.entryAmountQuestion': 'Wie hoch sollte der Handelsbetrag sein?',
  'settings.entryAmountExplanation1': 'Dies ist der anfängliche Betrag, der in jedem Handel verwendet wird.',
  'settings.entryAmountExplanation2': 'Die Positionsgröße variiert je nach Hebelverhältnis.',
  'settings.leverage': 'Hebel',
  'settings.leverageDescription': 'Hebelverhältnis, das für Ihre Handel verwendet werden soll',
  'settings.safe': 'Sicher',
  'settings.risky': 'Riskant',
  'settings.tradeType': 'Handelsart',
  'settings.tradeTypeDescription': 'Margenart, die für Ihre Handel verwendet werden soll',
  'settings.isolated': 'Isoliert',
  'settings.cross': 'Cross',
  'settings.profitTradeSettings': 'Gewinnmitnahme-Einstellungen',
  'settings.profitTradeSettingsDescription': 'Gewinnmitnahme-Niveaus und -Strategien',
  'settings.selectEntryType': 'Einstiegsart auswählen',
  'settings.closed': 'Geschlossen',
  'settings.percentage': 'Prozentsatz',
  'settings.fixedAmount': 'Fester Betrag',
  'settings.percentSymbol': '%',
  'settings.tp1': 'TP1',
  'settings.tp2': 'TP2',
  'settings.tp3': 'TP3',
  'settings.tp4': 'TP4',
  'settings.tp5': 'TP5',
  'settings.tp6': 'TP6',
  'settings.tp7': 'TP7',
  'settings.tp8': 'TP8',
  'settings.tp9': 'TP9',
  'settings.tp10': 'TP10',
  'settings.tpLevel': 'TP-Niveau',
  'settings.stoplossTradeSettings': 'Stop-Loss-Einstellungen',
  'settings.stoplossTradeSettingsDescription': 'Stop-Loss-Niveaus und -Strategien',
  'settings.selectStopLossStrategy': 'Stop-Loss-Strategie auswählen',
  'settings.useSignalSL': 'Signal-SL verwenden',
  'settings.customStopLoss': 'Benutzerdefinierter Stop-Loss',
  'settings.customStopLossInput': 'Stop-Loss-Niveau',
  'settings.customStopLossHelp': 'Prozentuales Stop-Loss-Niveau basierend auf dem Positionseinstiegspreis',
  'settings.stopLossActionSettings': 'Stop-Loss-Aktionseinstellungen',
  'settings.stopLossActionDescription': 'Aktionen, die ausgeführt werden sollen, wenn der Stop-Loss ausgelöst wird',
  'settings.selectAction': 'Aktion auswählen',
  'settings.trailStopAction': 'Trailing Stop',
  'settings.costWithdrawAction': 'Auf Einstand ziehen',
  'settings.specificLossAction': 'Bei bestimmtem Verlust schließen',
  'settings.specificLossLabel': 'Verlustprozentsatz',
  'settings.specificLossQuestion': 'Wie funktioniert diese Funktion?',
  'settings.specificLossExplanation': 'Die Position wird automatisch geschlossen, wenn der angegebene Verlustprozentsatz erreicht ist.',
  'settings.costWithdraw': 'Auf Einstand ziehen',
  'settings.costWithdrawDescription': 'Stop-Loss-Niveau auf Einstand ziehen, wenn das Gewinnziel erreicht ist',
  'settings.selectLevel': 'Niveau auswählen',
  'settings.none': 'Keine',
  'settings.costWithdrawQuestion': 'Wie funktioniert "Auf Einstand ziehen"?',
  'settings.costWithdrawExplanation1': 'Wenn das ausgewählte TP-Niveau erreicht ist, wird das Stop-Loss-Niveau auf Einstand gezogen.',
  'settings.costWithdrawExplanation2': 'Auf diese Weise erzielen Sie im schlimmsten Fall ein ausgeglichenes Ergebnis.',
  'settings.costWithdrawExplanation3': 'Wenn sich der Markt umkehrt, ist der Gewinn geschützt.',
  'settings.costWithdrawExplanation4': 'Es ist eine wichtige Strategie für das Risikomanagement.',
  'settings.trailStop': 'Trailing Stop',
  'settings.trailStopDescription': 'Stop-Loss-Niveau automatisch nach oben ziehen',
  'settings.trailStopQuestion': 'Wie funktioniert der Trailing Stop?',
  'settings.trailStopExplanation': 'Wenn das ausgewählte TP-Niveau erreicht ist, wird der Stop-Loss automatisch in die Gewinnzone verschoben und bewegt sich nach oben, wenn der Preis steigt.',
  'settings.maxOrders': 'Maximale Aufträge',
  'settings.maxOrdersDescription': 'Die maximale Anzahl von Aufträgen, die gleichzeitig offen sein können',
  'settings.save': 'Speichern',
  'settings.saving': 'Wird gespeichert...',
  'settings.saveSuccess': 'Einstellungen erfolgreich gespeichert.',
  'settings.saveError': 'Beim Speichern der Einstellungen ist ein Fehler aufgetreten.',
  addSignal: 'Signal hinzufügen',
  addNewSignal: 'Neues Signal hinzufügen',
  fillSignalDetails: 'Signaldetails ausfüllen',
  exchange: "Börse",
  side: "Richtung",
  pnl: "G/V",
  action: "Aktion",
  close: "Schließen",
  trend: 'Trend',
  selectTrend: 'Trend auswählen',
  long: "LONG",
  short: "SHORT",
  stopLossPercentage: 'Stop-Loss-Prozentsatz',
  entryRangePercentage: 'Einstiegsbereichsprozentsatz',
  takeProfitCount: 'Anzahl der Gewinnmitnahmen',
  takeProfitRangePercentage: 'Gewinnmitnahme-Bereichsprozentsatz',
  createSignal: 'Signal erstellen',
  signal_channels: "Signalkanäle",
  addYourChannel: "Ihren Kanal hinzufügen",
  welcomeMessage: "Willkommen,",
  openTradesLabel: "Handel laufen",
  apiStatusLabel: "Börsenkonten verbunden",
  addApiKey: "API-Schlüssel hinzufügen",
  noApiKeyCta: "Sie haben noch keinen API-Schlüssel. Klicken Sie hier, um Ihr Börsenkonto zu verbinden.",
  noOpenTrades: "Keine offenen Handel gefunden",
  waiting: "Wartend",
  open: "Offen",
  recentTrades: "Letzte Handel",
  yourRecentTrades: "Ihre letzten Handel",
  openClose: "Öffnen/Schließen",
  noTradesFound: "Keine Handel gefunden",
  unknown: "Unbekannt",
  closed: "Geschlossen",
  loginError: "Anmeldefehler",
  loginWithTelegram: "Mit Telegram anmelden",
  pleaseLoginWithTelegram: "Bitte melden Sie sich über Telegram an.",
  pageNotFound: "Hoppla! Seite nicht gefunden",
  returnToHome: "Zurück zur Startseite",
  copied: "Kopiert",
  copiedToClipboard: "{{field}} in die Zwischenablage kopiert.",
  copyError: "Kopieren fehlgeschlagen.",
  fillAllFields: "Bitte füllen Sie alle Felder aus.",
  sessionNotFound: "Sitzungsinformationen nicht gefunden",
  userNotFound: "Benutzer nicht gefunden",
  newApiKey: "Neuer API-Schlüssel:",
  addApiKeyError: "API-Schlüssel konnte nicht hinzugefügt werden",
  newApiKeyNotFound: "Neuer API-Schlüssel nicht gefunden",
  apiKeyAdded: 'API-Schlüssel "{{name}}" wurde erfolgreich hinzugefügt.',
  apiKeyAddError: "Fehler beim Hinzufügen des API-Schlüssels:",
  addNewApiKey: "Neuen API-Schlüssel hinzufügen",
  addNewApiKeyDesc: "Geben Sie hier die API-Schlüsselinformationen Ihrer Börse ein. Diese Informationen werden für den automatisierten Handel verwendet.",
  exchangeType: "Börsentyp",
  name: "Name",
  apiKeyNamePlaceholder: "z.B. Binance Futures",
  apiKeyNameDesc: "Geben Sie einen Namen ein, damit Sie sich an diesen Schlüssel erinnern können.",
  apiKeyPlaceholder: "Geben Sie Ihren API-Schlüssel ein",
  apiSecretPlaceholder: "Geben Sie Ihr API-Secret ein",
  apiSecretDesc: "Teilen Sie Ihren API-Schlüssel und Ihr Secret mit niemandem.",
  signalChannel: "Signalkanal",
  searchChannelPlaceholder: "Nach Kanalnamen oder ID suchen...",
  selectedChannel: "Ausgewählter Kanal",
  subscriptionPackage: "Abonnementpaket",
  select: "Auswählen",
  cancel: "Abbrechen",
  adding: "Wird hinzugefügt...",
  save: "Speichern",
  apiKeyIdNotFound: "API-Schlüssel-ID nicht gefunden",
  apiKeyNotFound: "API-Schlüssel nicht gefunden",
  apiKeyLoadError: "Fehler beim Laden des API-Schlüssels:",
  apiKeyLoadErrorText: "API-Schlüssel konnte nicht geladen werden",
  apiKeyUpdated: 'API-Schlüssel "{{name}}" wurde erfolgreich aktualisiert.',
  apiKeyUpdateError: "Fehler beim Aktualisieren des API-Schlüssels:",
  apiKeyUpdateErrorText: "API-Schlüssel konnte nicht aktualisiert werden.",
  editApiKey: "API-Schlüssel bearbeiten",
  editApiKeyDesc: "Aktualisieren Sie Ihre Börsen-API-Schlüsselinformationen.",
  saving: "Wird gespeichert...",
  apiChannelDesc: "Wählen Sie den Signalkanal aus, auf den der API-Schlüssel lauschen soll.",
  deleteApiKeyConfirm: "Möchten Sie diesen API-Schlüssel wirklich löschen?",
  apiKeyDeleted: "API-Schlüssel erfolgreich gelöscht.",
  apiKeyDeleteError: "API-Schlüssel konnte nicht gelöscht werden.",
  networkError: "Netzwerkantwort war nicht ok",
  fetchDetailsError: "Details konnten nicht abgerufen werden",
  deleteFailed: "Löschvorgang fehlgeschlagen",
  apiKeyDeletedSuccess: "API-Schlüssel erfolgreich gelöscht",
  adminApiKeys: {
    title: "API-Schlüssel",
    description: "Benutzer-API-Schlüssel anzeigen und verwalten.",
    searchPlaceholder: "Nach Benutzername oder Name suchen...",
    user: "Benutzer",
    apiName: "API-Name",
    apiType: "API-Typ",
    packageEnd: "Paketende",
    channel: "Kanal",
    packageStart: "Paketstart",
    lotsize: "Losgröße",
    leverage: "Hebel",
    marginType: "Margenart",
    maxOrders: "Max. Aufträge",
    autoTrade: "Automatischer Handel",
    actions: "Aktionen",
    deleteConfirmTitle: "Löschen bestätigen",
    deleteConfirmDesc: "Sind Sie sicher, dass Sie diesen API-Schlüssel dauerhaft löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
  },
  on: "Ein",
  off: "Aus",
  delete: "Löschen",
  edit: "Bearbeiten",
  admin: {
    notLoggedIn: "Sie sind nicht als Administrator angemeldet oder Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an.",
    faq: {
      addSuccess: "Frage erfolgreich hinzugefügt!",
      addError: "Eintrag konnte nicht hinzugefügt werden",
      addNewTitle: "Neue Frage hinzufügen",
      addNewDesc: "Sie können eine neue häufig gestellte Frage hinzufügen.",
      questionInfo: "Frageninformationen",
      question: "Frage",
      questionPlaceholder: "Schreiben Sie die Frage...",
      answer: "Antwort",
      answerPlaceholder: "Schreiben Sie die Antwort...",
    }
  },
  fromLastMonth: "vom letzten Monat",
  newTrades: "neue Handel",
  thisMonth: "diesen Monat",
  dashboard: "Dashboard",
  switchToLightMode: "In den hellen Modus wechseln",
  switchToDarkMode: "In den dunklen Modus wechseln",
  noTradeOnPage: "Auf dieser Seite gibt es keine anzuzeigenden Handel.",
  tradeRecordNotFound: "Handelsdatensatz nicht gefunden.",
  previousPage: "Vorherige Seite",
  nextPage: "Nächste Seite",
  filterByExchange: "Nach Börse filtern",
  profit: "Gewinn",
  "faq.title": "Häufig gestellte Fragen",
  tradeStatus: {
    waiting: "Wartend",
    open: "Offen",
    completed: "Abgeschlossen",
    failed: "Fehlgeschlagen",
    unknown: "Unbekannt"
  },
  orderError: "Order-Fehler: {{error}}",
};

export default de;