const es = {
  anasayfa: "Página principal",
  apiKeys: "Mis claves API",
  addNew: "Agregar nuevo",
  noApiKey: "Aún no se ha agregado ninguna clave API. Puede comenzar con el botón 'Agregar nuevo'.",
  trades: "Operaciones",
  signals: "Señales",
  channels: "Canales",
  partnership: "Asociación",
  subscription: "Suscripción",
  adminLogin: "Inicio de sesión de administrador",
  loading: "Cargando...",
  telegramRequired: "Debe iniciar sesión a través de Telegram para usar esta aplicación.",
  goToTelegram: "Ir a Telegram",
  dashboardTitle: "Panel de control",
  lastUpdate: "Última actualización",
  activeSignals: "Señales activas",
  activeSignalsDesc: "Señal a procesar",
  openTrades: "Operaciones abiertas",
  openTradesDesc: "Puede seguir sus operaciones en curso aquí.",
  performance: "Rendimiento",
  performanceDesc: "P/L de 30 días",
  apiStatus: "Estado de la API",
  apiStatusDesc: "Bolsa activa",
  son_islemler: "Últimas operaciones",
  sizin_adiniza_gerceklesen_son_islemler: "Últimas operaciones realizadas en su nombre",
  signalsList: {
    title: "Últimas señales",
    description: "Últimas señales de operación del canal",
    viewAll: "Ver todas las señales →"
  },
  buy: "COMPRA",
  sell: "VENTA",
  unit: "unidad",
  tradesList: { viewAll: "Ver todas las operaciones →" },
  entry: "Entrada",
  usdt: "USDT",
  active: "ACTIVO",
  filled: "LLENO",
  cancelled: "CANCELADO",
  balanceChart: {
    title: "Evolución del saldo",
    balance: "Saldo",
    description: "Cambio de su portafolio a lo largo del tiempo"
  },
  'backtest.title': 'Backtest',
  'backtest.channelSelect': 'Selección de canal',
  'backtest.channelSelectDescription': 'Seleccione el canal de señales a utilizar para el backtest',
  'backtest.selectChannel': 'Seleccione un canal',
  'backtest.dateRange': 'Rango de fechas',
  'backtest.dateRangeDescription': 'Seleccione el rango de fechas para el backtest',
  'backtest.selectDateRange': 'Seleccione un rango de fechas',
  'backtest.autoTrade': 'Trading automático',
  'backtest.autoTradeDescription': 'Procesar señales automáticamente',
  'backtest.entryAmount': 'Cantidad de entrada a la operación',
  'backtest.entryAmountDescription': 'Cantidad a utilizar para cada operación',
  'backtest.enterAmount': 'Ingrese la cantidad',
  'backtest.usdt': 'USDT',
  'backtest.howMuchToEnter': '¿Con cuántos dólares desea entrar en la operación?',
  'backtest.enterAmountInfo1': 'Multiplique la cantidad que desea ingresar por el apalancamiento que ha determinado y escriba el resultado como lote.',
  'backtest.enterAmountInfo2': 'Ejemplo: Si desea ingresar con $20 usando un apalancamiento de 20X: 20 × 20 = 400. En este caso, debe escribir 400 en la sección de lotes.',
  'backtest.leverage': 'Apalancamiento',
  'backtest.leverageDescription': 'Tasa de apalancamiento para sus operaciones',
  'backtest.safe': '1x (Seguro)',
  'backtest.risky': '25x (Riesgoso)',
  'backtest.tradeType': 'Tipo de operación',
  'backtest.tradeTypeDescription': 'Seleccione el tipo de margen de la operación',
  'backtest.isolated': 'ISOLATED',
  'backtest.cross': 'CROSS',
  'backtest.profitTradeSettings': 'Configuración de toma de ganancias',
  'backtest.profitTradeSettingsDescription': 'Seleccione la estrategia de cierre de operaciones',
  'backtest.profitTradeSelect': 'Seleccione una estrategia de toma de ganancias',
  'backtest.closed': 'Cerrado',
  'backtest.percentage': 'Porcentaje del saldo',
  'backtest.fixedAmount': 'Cantidad fija',
  'backtest.tp': 'TP',
  'backtest.tpLevel': 'Nivel TP',
  'backtest.stopLossSettings': 'Configuración de stop loss',
  'backtest.stopLossSettingsDescription': 'Seleccione la acción después del stop',
  'backtest.actionSelect': 'Seleccione una acción',
  'backtest.trailStop': 'TrailStop',
  'backtest.costToWithdraw': 'Retirar al costo',
  'backtest.specificLoss': 'Cerrar operación con pérdida específica',
  'backtest.lossPercentage': 'Cerrar con pérdida (%)',
  'backtest.specificLossInfo': '¿Qué es cerrar operación con pérdida específica?',
  'backtest.specificLossInfo1': 'Esta función permite cerrar automáticamente su operación cuando alcanza un cierto porcentaje de pérdida.',
  'backtest.specificLossInfo2': 'Por ejemplo, si desea que su posición se cierre cuando tenga una pérdida del 10% según el precio spot, simplemente escriba 10% en la configuración correspondiente.',
  'backtest.costToWithdrawDescription': 'Seleccione el nivel para retirar al costo',
  'backtest.levelSelect': 'Seleccione un nivel',
  'backtest.none': 'Ninguno',
  'backtest.tp1': 'TP1',
  'backtest.tp2': 'TP2',
  'backtest.tp3': 'TP3',
  'backtest.tp4': 'TP4',
  'backtest.tp5': 'TP5',
  'backtest.costToWithdrawInfo': '¿Qué es retirar al costo?',
  'backtest.costToWithdrawInfo1': 'Cuando se alcanza el nivel de toma de ganancias 1 o 2, la orden de stop loss se mueve al nivel de entrada.',
  'backtest.costToWithdrawInfo2': 'Gracias a este sistema, la gestión de riesgos se vuelve más segura mientras se protegen las ganancias.',
  'backtest.trailStopDescription': 'Seleccione el nivel de TrailStop',
  'backtest.trailStopInfo': '¿Qué es el Trail Stop?',
  'backtest.trailStopInfo1': 'El trail stop permite que el nivel de stop loss se mueva automáticamente hacia arriba junto con el precio a medida que su operación obtiene ganancias.',
  'backtest.trailStopInfo2': 'El objetivo es proteger las ganancias existentes cuando hay retrocesos en el mercado.',
  'backtest.maxOrders': 'Cantidad máxima de órdenes',
  'backtest.maxOrdersDescription': 'Determine el número máximo de órdenes',
  'backtest.startBacktest': 'Iniciar backtest',
  'totalTrades': 'Operaciones totales',
  'winRate': 'Tasa de éxito',
  'totalPL': 'P/L total',
  'averageTrade': 'Operación promedio',
  'openPositions': 'Posiciones abiertas',
  'closedPositions': 'Posiciones cerradas',
  'cumulativeProfitLoss': 'Ganancia/pérdida acumulada',
  'profitLossPerChannel': 'Ganancia/pérdida por API a lo largo del tiempo',
  'notEnoughData': 'No hay suficientes datos para el gráfico.',
  'date': 'Fecha',
  'previous': 'Anterior',
  'next': 'Siguiente',
  'page': 'Página',
  'trendDirection': 'Dirección de la tendencia',
  'symbol': "Par",
  'entry1': 'Entrada 1',
  'entry2': 'Entrada 2',
  'sl': 'SL',
  'tp1': 'TP1',
  'tp2': 'TP2',
  'tp3': 'TP3',
  'tp4': 'TP4',
  'tp5': 'TP5',
  'tp6': 'TP6',
  'tp7': 'TP7',
  'tp8': 'TP8',
  'tp9': 'TP9',
  'tp10': 'TP10',
  'entryPrice': "Precio de apertura",
  'entryDate': "Fecha de apertura",
  'takeProfit': 'Take Profit',
  'exitPrice': 'Precio de cierre',
  'exitDate': 'Fecha de cierre',
  'profitLoss': 'Ganancia/Pérdida',
  'allTime': 'Todo el tiempo',
  'last24': 'Últimas 24 horas',
  'last30': 'Últimos 30 días',
  'last7': 'Últimos 7 días',
  'channelSelect': 'Seleccione un canal',
  'allChannels': 'Todos los canales',
  'timeSelect': 'Seleccione el tiempo',
  'error': "Error",
  tradeHistory: 'Historial de operaciones',
  totalPnL: 'P/L total',
  profitLossByApi: 'Ganancia/pérdida por API',
  tradeSearch: 'Buscar operación...',
  allExchanges: 'Todas las bolsas',
  realizedPnL: 'Ganancia/pérdida realizada',
  perCompletedTrade: 'Por operación completada',
  profitableTrades: 'Operaciones rentables',
  ticket: 'Ticket',
  direction: "Dirección",
  openPrice: 'Precio de apertura',
  openTime: 'Hora de apertura',
  volume: 'Cantidad',
  closePrice: 'Precio de cierre',
  closeTime: 'Hora de cierre',
  status: 'Estado',
  completed: 'Completado',
  open: "Apertura",
  allTrades: 'Todas las operaciones',
  'signals.title': 'Señales',
  'signals.activeSignals': 'Señales activas',
  'signals.signalHistory': 'Historial de señales',
  'signals.channel': 'Canal',
  'signals.symbol': 'Símbolo',
  'signals.direction': 'Dirección',
  'signals.openPrice': 'Apertura',
  'signals.openDate': 'Fecha de apertura',
  'signals.closePrice': 'Cierre',
  'signals.closeDate': 'Fecha de cierre',
  'signals.stopLoss': 'Stop Loss',
  'signals.takeProfit': 'Take Profit',
  'signals.profitLoss': 'Ganancia/Pérdida',
  'signals.totalTrades': 'OPERACIONES TOTALES',
  'signals.winRate': 'TASA DE ÉXITO',
  'signals.totalPL': 'P/L TOTAL',
  'signals.avgTrade': 'OPERACIÓN PROMEDIO',
  'signals.openPositions': 'Posiciones abiertas',
  'signals.closedPositions': 'Posiciones cerradas',
  'signals.cumulativePL': 'Ganancia/pérdida acumulada',
  'signals.plByChannel': 'Ganancia/pérdida por canal a lo largo del tiempo',
  'signals.noChartData': 'No hay suficientes datos para el gráfico.',
  'signals.channelName': 'Nombre del canal:',
  'signals.trendDirection': 'Dirección de la tendencia:',
  'signals.entry1': 'Entrada 1:',
  'signals.entry2': 'Entrada 2:',
  'signals.sl': 'SL:',
  'signals.tp': 'TP',
  'backtest.noResults': 'No se encontraron resultados',
  'backtest.results': 'Resultados del backtest',
  'backtest.profitChart': 'Gráfico de ganancias',
  'backtest.simulationTrades': 'Operaciones de simulación',
  'backtest.lot': 'Lote',
  'retry': 'Intentar de nuevo',
  goBack: "Volver",
  channelOwnerApply: "Solicitud de propietario de canal",
  channelNamePlaceholder: "Ingrese el nombre del canal",
  channelLink: "Enlace del canal",
  followerCount: "Número de seguidores",
  fullName: "Nombre y apellido",
  email: "Correo electrónico",
  phoneNumber: "Número de teléfono",
  ownerTelegram: "Nombre de usuario de Telegram",
  agreementAccept: "He leído y acepto el Acuerdo de Asociación",
  submit: "Enviar",
  submitting: "Enviando...",
  telegram_channels: "Canales de Telegram",
  total_signals: "Total de señales",
  success_rate: "Tasa de éxito",
  total_profit: "Ganancia total",
  subscribers: "Número de suscriptores",
  per_month: "mes",
  channel_loading: "Cargando información del canal...",
  channel_not_found: "Información del canal no encontrada",
  back_to_channels: "Volver a los canales",
  no_channels_found: "Aún no se han encontrado canales.",
  success: "Éxito",
  application_success: "Su solicitud ha sido enviada con éxito.",
  error_occurred: "Ocurrió un error",
  accept_agreement_warning: "Por favor, acepte el Acuerdo de Asociación.",
  fill_all_fields_warning: "Por favor, complete todos los campos.",
  confirmation_title: "Solicitud aprobada",
  confirmation_message: "Su solicitud ha sido recibida con éxito. Nos pondremos en contacto con usted lo antes posible.",
  confirmation_return: "Volver a la página principal",
  go_to_channel: "Ir al canal",
  subscribe: "Suscribirse",
  closed_signals: "Señales cerradas",
  cumulative_profit_loss: "Ganancia/pérdida acumulada",
  profit_loss_per_channel: "Ganancia/pérdida por canal a lo largo del tiempo",
  total: "Total",
  openDate: "Fecha de apertura",
  closeDate: "Fecha de cierre",
  channelNameLabel: "Nombre del canal",
  subscription_title: "Suscripción",
  adminMenu: "Menú de administrador",
  members: "Miembros",
  memberNotifications: "Notificaciones de miembros",
  channelNotifications: "Notificaciones de canal",
  botChannels: {
    loadError: "No se pudieron cargar los canales de bots",
    unknownDeleteError: "Error de eliminación desconocido",
    deleteError: "La eliminación falló",
    deleteSuccess: "Canal de bot eliminado con éxito",
  },
  deleteErrorDetailed: "Error al eliminar el canal de bots: {{error}}",
  channelId: "ID del canal",
  channelName: "Nombre del canal",
  status: "Estado",
  actions: "Acciones",
  admin: "Admin",
  description: "Descripción",
  registerDate: "Fecha de registro",
  channelImageAlt: "Imagen del canal",
  title: "Canales de bots",
  addChannel: "Agregar canal",
  pageDescription: "Puede ver y administrar los canales de bots registrados en el sistema.",
  searchPlaceholder: "Buscar por nombre o ID del canal...",
  deleteConfirmTitle: "Confirmación de eliminación de canal de bots",
  deleteConfirmDesc: "¿Está seguro de que desea eliminar este canal de bots de forma permanente?",
  confirmDelete: "Sí, eliminar",
  subscriptions: "Suscripciones",
  subscriptionPackages: "Paquetes de suscripción",
  'signalsList.title': "Últimas señales",
  'signalsList.description': "Últimas señales de operación del canal",
  'signalsList.viewAll': "Ver todas las señales →",
  'tradesList.viewAll': "Ver todas las operaciones →",
  subscriptionHistory: "Historial de suscripción",
  allActiveAndPastSubscriptions: "Todas sus suscripciones activas y pasadas",
  ended: "Finalizado",
  start: "Inicio",
  end: "Fin",
  noSubscriptionFound: "Aún no tiene ninguna suscripción.",
  upgradeToPremium: "Actualizar a Premium",
  monthlyPlan: "Mensual",
  monthlyAccess: "acceso premium durante un mes",
  selectPlan: "Seleccionar paquete",
  enterPassword: "Ingrese la contraseña",
  login: "Iniciar sesión",
  'Tüm sinyallere erişim': "Acceso a todas las señales",
  'Manuel trading': "Trading manual",
  'Temel destek': "Soporte básico",
  'Tanışma Paketi': "Paquete de bienvenida",
  'Öncelikli destek': "Soporte prioritario",
  '3 aylık indirim': "Descuento de 3 meses",
  'Premium destek': "Soporte premium",
  '6 aylık indirim': "Descuento de 6 meses",
  'VIP destek': "Soporte VIP",
  'Yıllık indirim': "Descuento anual",
  threeMonthPlan: "3 meses",
  sixMonthPlan: "6 meses",
  yearlyPlan: "Anual",
  premiumAccess: "acceso premium durante",
  accessAllSignals: "Acceso a todas las señales",
  manualTrading: "Trading manual",
  basicSupport: "Soporte básico",
  welcomePackage: "Paquete de bienvenida",
  prioritySupport: "Soporte prioritario",
  threeMonthDiscount: "Descuento de 3 meses",
  premiumSupport: "Soporte premium",
  sixMonthDiscount: "Descuento de 6 meses",
  vipSupport: "Soporte VIP",
  annualDiscount: "Descuento anual",
  'settings.title': 'Configuración de la API',
  'settings.invalidId': 'ID no válido',
  'settings.apiNotFound': 'API no encontrada',
  'settings.loadingError': 'Error de carga',
  'settings.missingApiId': 'Falta el ID de la API',
  'settings.autoTrade': 'Operación automática',
  'settings.autoTradeDescription': 'Activar la función de operación automática',
  'settings.entryAmount': 'Cantidad de operación',
  'settings.entryAmountDescription': 'Cantidad a utilizar para cada operación',
  'settings.entryAmountPlaceholder': 'Ingrese la cantidad',
  'settings.usdt': 'USDT',
  'settings.entryAmountQuestion': '¿Cuál debe ser la cantidad de operación?',
  'settings.entryAmountExplanation1': 'Esta cantidad es la cantidad inicial que se utilizará en cada operación.',
  'settings.entryAmountExplanation2': 'El tamaño de la posición cambiará según la tasa de apalancamiento.',
  'settings.leverage': 'Apalancamiento',
  'settings.leverageDescription': 'Tasa de apalancamiento a utilizar para sus operaciones',
  'settings.safe': 'Seguro',
  'settings.risky': 'Riesgoso',
  'settings.tradeType': 'Tipo de operación',
  'settings.tradeTypeDescription': 'Tipo de margen a utilizar para sus operaciones',
  'settings.isolated': 'Aislado',
  'settings.cross': 'Cruzado',
  'settings.profitTradeSettings': 'Configuración de toma de ganancias',
  'settings.profitTradeSettingsDescription': 'Niveles y estrategias de toma de ganancias',
  'settings.selectEntryType': 'Seleccione el tipo de entrada',
  'settings.closed': 'Cerrado',
  'settings.percentage': 'Porcentaje',
  'settings.fixedAmount': 'Cantidad fija',
  'settings.percentSymbol': '%',
  'settings.tp1': 'TP1',
  'settings.tp2': 'TP2',
  'settings.tp3': 'TP3',
  'settings.tp4': 'TP4',
  'settings.tp5': 'TP5',
  'settings.tp6': 'TP6',
  'settings.tp7': 'TP7',
  'settings.tp8': 'TP8',
  'settings.tp9': 'TP9',
  'settings.tp10': 'TP10',
  'settings.tpLevel': 'Nivel TP',
  'settings.stoplossTradeSettings': 'Configuración de stop loss',
  'settings.stoplossTradeSettingsDescription': 'Niveles y estrategias de stop loss',
  'settings.selectStopLossStrategy': 'Seleccione la estrategia de stop loss',
  'settings.useSignalSL': 'Usar SL de señal',
  'settings.customStopLoss': 'Stop Loss personalizado',
  'settings.customStopLossInput': 'Nivel de Stop Loss',
  'settings.customStopLossHelp': 'Nivel de stop loss porcentual según el precio de apertura de la posición',
  'settings.stopLossActionSettings': 'Configuración de acción de stop loss',
  'settings.stopLossActionDescription': 'Acciones a realizar cuando se activa el stop loss',
  'settings.selectAction': 'Seleccione una acción',
  'settings.trailStopAction': 'Trailing Stop',
  'settings.costWithdrawAction': 'Retirar al costo',
  'settings.specificLossAction': 'Cerrar con pérdida específica',
  'settings.specificLossLabel': 'Porcentaje de pérdida',
  'settings.specificLossQuestion': '¿Cómo funciona esta función?',
  'settings.specificLossExplanation': 'La posición se cerrará automáticamente cuando se alcance el porcentaje de pérdida especificado.',
  'settings.costWithdraw': 'Retirar al costo',
  'settings.costWithdrawDescription': 'Mueva el nivel de stop loss al costo cuando se alcance el objetivo de ganancia',
  'settings.selectLevel': 'Seleccione el nivel',
  'settings.none': 'Ninguno',
  'settings.costWithdrawQuestion': '¿Cómo funciona retirar al costo?',
  'settings.costWithdrawExplanation1': 'Cuando se alcanza el nivel TP seleccionado, el nivel de stop loss se mueve al costo.',
  'settings.costWithdrawExplanation2': 'Así, en el peor de los casos, se sale en punto de equilibrio.',
  'settings.costWithdrawExplanation3': 'Si el mercado se revierte, la ganancia se conserva.',
  'settings.costWithdrawExplanation4': 'Es una estrategia importante para la gestión de riesgos.',
  'settings.trailStop': 'Trailing Stop',
  'settings.trailStopDescription': 'Mueva automáticamente el nivel de stop loss hacia arriba',
  'settings.trailStopQuestion': '¿Cómo funciona el trailing stop?',
  'settings.trailStopExplanation': 'Cuando se alcanza el nivel TP seleccionado, el stop loss se mueve automáticamente a la zona de ganancia y se mueve hacia arriba a medida que sube el precio.',
  'settings.maxOrders': 'Órdenes máximas',
  'settings.maxOrdersDescription': 'Número máximo de órdenes que pueden estar abiertas al mismo tiempo',
  'settings.save': 'Guardar',
  'settings.saving': 'Guardando...',
  'settings.saveSuccess': 'La configuración se guardó correctamente.',
  'settings.saveError': 'Se produjo un error al guardar la configuración.',
  addSignal: 'Agregar señal',
  addNewSignal: 'Agregar nueva señal',
  fillSignalDetails: 'Complete los detalles de la señal',
  exchange: "Bolsa",
  side: "Dirección",
  pnl: "Ganancia/Pérdida",
  action: "Acción",
  close: "Cerrar",
  trend: 'Tendencia',
  selectTrend: 'Seleccione la tendencia',
  long: "LARGO",
  short: "CORTO",
  stopLossPercentage: 'Porcentaje de stop loss',
  entryRangePercentage: 'Porcentaje de rango de entrada',
  takeProfitCount: 'Cantidad de take profit',
  takeProfitRangePercentage: 'Porcentaje de rango de take profit',
  createSignal: 'Crear señal',
  signal_channels: "Canales de señales",
  addYourChannel: "Agrega tu canal",
  welcomeMessage: "Bienvenido,",
  openTradesLabel: "operaciones en curso",
  apiStatusLabel: "cuentas de bolsa conectadas",
  addApiKey: "Agregar clave API",
  noApiKeyCta: "Aún no tiene una clave API. Haga clic para conectar su cuenta de bolsa.",
  noOpenTrades: "No hay operaciones abiertas",
  waiting: "En espera",
  open: "Abierto",
  recentTrades: "Operaciones recientes",
  yourRecentTrades: "Sus operaciones más recientes",
  openClose: "Apertura/Cierre",
  noTradesFound: "No se encontraron operaciones",
  unknown: "Desconocido",
  closed: "Cerrado",
  loginError: "Error de inicio de sesión",
  loginWithTelegram: "Iniciar sesión con Telegram",
  pleaseLoginWithTelegram: "Por favor, inicie sesión a través de Telegram.",
  pageNotFound: "¡Vaya! Página no encontrada",
  returnToHome: "Volver a la página principal",
  copied: "Copiado",
  copiedToClipboard: "{{field}} copiado al portapapeles.",
  copyError: "Error al copiar.",
  fillAllFields: "Por favor, complete todos los campos.",
  sessionNotFound: "No se encontró información de la sesión",
  userNotFound: "Usuario no encontrado",
  newApiKey: "Nueva clave API:",
  addApiKeyError: "No se pudo agregar la clave API",
  newApiKeyNotFound: "No se encontró la nueva clave API",
  apiKeyAdded: 'La clave API "{{name}}" se agregó correctamente.',
  apiKeyAddError: "Error al agregar la clave API:",
  addNewApiKey: "Agregar nueva clave API",
  addNewApiKeyDesc: "Ingrese la información de la clave API de su bolsa aquí. Esta información se utilizará para operaciones automáticas.",
  exchangeType: "Tipo de bolsa",
  name: "Nombre",
  apiKeyNamePlaceholder: "Ej: Binance Futuros",
  apiKeyNameDesc: "Ingrese un nombre que le ayude a recordar esta clave.",
  apiKeyPlaceholder: "Ingrese su clave API",
  apiSecretPlaceholder: "Ingrese su API Secret",
  apiSecretDesc: "No comparta su clave API y secret con nadie.",
  signalChannel: "Canal de señales",
  searchChannelPlaceholder: "Buscar por nombre o ID del canal...",
  selectedChannel: "Canal seleccionado",
  subscriptionPackage: "Paquete de suscripción",
  select: "Seleccione",
  cancel: "Cancelar",
  adding: "Agregando...",
  save: "Guardar",
  apiKeyIdNotFound: "No se encontró el ID de la clave API",
  apiKeyNotFound: "Clave API no encontrada",
  apiKeyLoadError: "Error al cargar la clave API:",
  apiKeyLoadErrorText: "No se pudo cargar la clave API",
  apiKeyUpdated: 'La clave API "{{name}}" se actualizó correctamente.',
  apiKeyUpdateError: "Error al actualizar la clave API:",
  apiKeyUpdateErrorText: "No se pudo actualizar la clave API.",
  editApiKey: "Editar clave API",
  editApiKeyDesc: "Actualice la información de la clave API de su bolsa.",
  saving: "Guardando...",
  apiChannelDesc: "Seleccione el canal de señales que escuchará la clave API.",
  deleteApiKeyConfirm: "¿Está seguro de que desea eliminar esta clave API?",
  apiKeyDeleted: "La clave API se eliminó correctamente.",
  apiKeyDeleteError: "Se produjo un error al eliminar la clave API.",
  networkError: "La respuesta de la red no fue correcta",
  fetchDetailsError: "No se pudieron obtener los detalles",
  deleteFailed: "La eliminación falló",
  apiKeyDeletedSuccess: "La clave API se eliminó correctamente",
  adminApiKeys: {
    title: "Claves API",
    description: "Puede ver y administrar las claves API de los usuarios.",
    searchPlaceholder: "Buscar por nombre de usuario o nombre...",
    user: "Usuario",
    apiName: "Nombre de la API",
    apiType: "Tipo de API",
    packageEnd: "Fin del paquete",
    channel: "Canal",
    packageStart: "Inicio del paquete",
    lotsize: "Tamaño de lote",
    leverage: "Apalancamiento",
    marginType: "Tipo de margen",
    maxOrders: "Órdenes máximas",
    autoTrade: "Operación automática",
    actions: "Acciones",
    deleteConfirmTitle: "Confirmación de eliminación",
    deleteConfirmDesc: "¿Está seguro de que desea eliminar esta clave API de forma permanente? Esta acción no se puede deshacer.",
  },
  on: "Encendido",
  off: "Apagado",
  delete: "Eliminar",
  edit: "Editar",
  admin: {
    notLoggedIn: "No ha iniciado sesión como administrador o su sesión ha expirado. Por favor, inicie sesión de nuevo.",
    faq: {
      addSuccess: "¡Pregunta agregada con éxito!",
      addError: "No se pudo agregar el registro",
      addNewTitle: "Agregar nueva pregunta",
      addNewDesc: "Puede agregar una nueva pregunta frecuente.",
      questionInfo: "Información de la pregunta",
      question: "Pregunta",
      questionPlaceholder: "Escriba la pregunta...",
      answer: "Respuesta",
      answerPlaceholder: "Escriba la respuesta...",
    }
  },
  fromLastMonth: "en comparación con el mes pasado",
  newTrades: "nueva operación",
  thisMonth: "este mes",
  dashboard: "Panel de control",
  switchToLightMode: "Cambiar a modo claro",
  switchToDarkMode: "Cambiar a modo oscuro",
  noTradeOnPage: "No hay operaciones para mostrar en esta página.",
  tradeRecordNotFound: "No se encontró el registro de la operación.",
  previousPage: "Página anterior",
  nextPage: "Página siguiente",
  filterByExchange: "Filtrar por bolsa",
  profit: "Ganancia",
  "faq.title": "Preguntas frecuentes",
  tradeStatus: {
    waiting: "Esperando",
    open: "Abierto",
    completed: "Completado",
    failed: "Fallido",
    unknown: "Desconocido"
  },
  orderError: "Error de orden: {{error}}",
};

export default es;