const fr = {
  anasayfa: "Accueil",
  apiKeys: "Mes clés API",
  addNew: "Ajouter",
  noApiKey: "Aucune clé API n'a encore été ajoutée. Vous pouvez commencer avec le bouton 'Ajouter'.",
  trades: "Transactions",
  signals: "Signaux",
  channels: "Canaux",
  partnership: "Partenariat",
  subscription: "Abonnement",
  adminLogin: "Connexion administrateur",
  loading: "Chargement...",
  telegramRequired: "Vous devez vous connecter via Telegram pour utiliser cette application.",
  goToTelegram: "Aller sur Telegram",
  dashboardTitle: "Tableau de bord",
  lastUpdate: "Dernière mise à jour",
  activeSignals: "Signaux actifs",
  activeSignalsDesc: "Signal à traiter",
  openTrades: "Transactions ouvertes",
  openTradesDesc: "Vous pouvez suivre vos transactions en cours ici.",
  performance: "Performance",
  performanceDesc: "P/L sur 30 jours",
  apiStatus: "Statut de l'API",
  apiStatusDesc: "Bourse active",
  son_islemler: "Dernières transactions",
  sizin_adiniza_gerceklesen_son_islemler: "Dernières transactions effectuées en votre nom",
  signalsList: {
    title: "Derniers signaux",
    description: "Derniers signaux de trading du canal",
    viewAll: "Voir tous les signaux →"
  },
  buy: "ACHETER",
  sell: "VENDRE",
  unit: "unité",
  tradesList: { viewAll: "Voir toutes les transactions →" },
  entry: "Entrée",
  usdt: "USDT",
  active: "ACTIF",
  filled: "REMPLI",
  cancelled: "ANNULÉ",
  balanceChart: {
    title: "Évolution du solde",
    balance: "Solde",
    description: "Évolution de votre portefeuille au fil du temps"
  },
  'backtest.title': 'Backtest',
  'backtest.channelSelect': 'Sélection du canal',
  'backtest.channelSelectDescription': 'Sélectionnez le canal de signaux à utiliser pour le backtest',
  'backtest.selectChannel': 'Sélectionner un canal',
  'backtest.dateRange': 'Plage de dates',
  'backtest.dateRangeDescription': 'Sélectionnez la plage de dates pour le backtest',
  'backtest.selectDateRange': 'Sélectionner la plage de dates',
  'backtest.autoTrade': 'Trading automatique',
  'backtest.autoTradeDescription': 'Exécuter automatiquement les signaux',
  'backtest.entryAmount': "Montant de l'entrée",
  'backtest.entryAmountDescription': 'Montant à utiliser pour chaque transaction',
  'backtest.enterAmount': 'Saisir le montant',
  'backtest.usdt': 'USDT',
  'backtest.howMuchToEnter': 'Avec combien de dollars souhaitez-vous entrer dans la transaction ?',
  'backtest.enterAmountInfo1': "Multipliez le montant que vous souhaitez investir par le ratio de levier que vous avez défini et entrez le résultat en tant que lot.",
  'backtest.enterAmountInfo2': 'Exemple : si vous souhaitez entrer dans une transaction avec 20 $ et un effet de levier de 20X : 20 × 20 = 400. Dans ce cas, vous devez écrire 400 dans la section Lot.',
  'backtest.leverage': 'Effet de levier',
  'backtest.leverageDescription': "Ratio de levier pour vos transactions",
  'backtest.safe': '1x (Sûr)',
  'backtest.risky': '25x (Risqué)',
  'backtest.tradeType': 'Type de transaction',
  'backtest.tradeTypeDescription': 'Sélectionnez le type de marge de la transaction',
  'backtest.isolated': 'ISOLÉ',
  'backtest.cross': 'CROISÉ',
  'backtest.profitTradeSettings': 'Paramètres de prise de profit',
  'backtest.profitTradeSettingsDescription': 'Sélectionnez la stratégie de clôture de transaction',
  'backtest.profitTradeSelect': 'Sélectionner une stratégie de prise de profit',
  'backtest.closed': 'Fermé',
  'backtest.percentage': 'Pourcentage du solde',
  'backtest.fixedAmount': 'Montant fixe',
  'backtest.tp': 'TP',
  'backtest.tpLevel': 'Niveau de TP',
  'backtest.stopLossSettings': 'Paramètres de Stop Loss',
  'backtest.stopLossSettingsDescription': "Sélectionnez l'action après le stop",
  'backtest.actionSelect': "Sélectionner une action",
  'backtest.trailStop': 'TrailStop',
  'backtest.costToWithdraw': 'Retirer au coût',
  'backtest.specificLoss': 'Fermer la transaction à une perte spécifique',
  'backtest.lossPercentage': 'Fermer à perte (%)',
  'backtest.specificLossInfo': "Qu'est-ce que 'Fermer la transaction à une perte spécifique' ?",
  'backtest.specificLossInfo1': "Cette fonctionnalité garantit que votre transaction est automatiquement fermée lorsqu'elle atteint un certain taux de perte.",
  'backtest.specificLossInfo2': "Par exemple, si vous voulez que la position se ferme lorsque votre transaction subit une perte de 10 % par rapport au prix spot, il suffit d'entrer 10 % dans le paramètre correspondant.",
  'backtest.costToWithdrawDescription': 'Sélectionnez le niveau de retrait au coût',
  'backtest.levelSelect': 'Sélectionner un niveau',
  'backtest.none': 'Aucun',
  'backtest.tp1': 'TP1',
  'backtest.tp2': 'TP2',
  'backtest.tp3': 'TP3',
  'backtest.tp4': 'TP4',
  'backtest.tp5': 'TP5',
  'backtest.costToWithdrawInfo': "Qu'est-ce que 'Retirer au coût' ?",
  'backtest.costToWithdrawInfo1': "Lorsque le niveau de prise de profit 1 ou 2 est atteint, l'ordre de stop loss est déplacé au niveau d'entrée.",
  'backtest.costToWithdrawInfo2': "Grâce à ce système, la gestion des risques devient plus sûre tout en protégeant les gains.",
  'backtest.trailStopDescription': 'Sélectionnez le niveau de TrailStop',
  'backtest.trailStopInfo': "Qu'est-ce que le 'Trail Stop' ?",
  'backtest.trailStopInfo1': "Un stop suiveur permet au niveau de stop loss de monter automatiquement avec le prix à mesure que votre transaction devient rentable.",
  'backtest.trailStopInfo2': "L'objectif est de protéger les profits existants en cas de retournement du marché.",
  'backtest.maxOrders': "Nombre maximal d'ordres",
  'backtest.maxOrdersDescription': "Définir le nombre maximum d'ordres",
  'backtest.startBacktest': 'Démarrer le backtest',
  'totalTrades': 'Total des transactions',
  'winRate': 'Taux de réussite',
  'totalPL': 'P/L total',
  'averageTrade': 'Transaction moyenne',
  'openPositions': 'Positions ouvertes',
  'closedPositions': 'Positions fermées',
  'cumulativeProfitLoss': 'Pertes/Gains cumulés',
  'profitLossPerChannel': "Profits/pertes par API au fil du temps",
  'notEnoughData': "Pas assez de données pour le graphique.",
  'date': 'Date',
  'previous': 'Précédent',
  'next': 'Suivant',
  'page': 'Page',
  'trendDirection': 'Direction de la tendance',
  'symbol': "Paire",
  'entry1': 'Entrée 1',
  'entry2': 'Entrée 2',
  'sl': 'SL',
  'tp1': 'TP1',
  'tp2': 'TP2',
  'tp3': 'TP3',
  'tp4': 'TP4',
  'tp5': 'TP5',
  'tp6': 'TP6',
  'tp7': 'TP7',
  'tp8': 'TP8',
  'tp9': 'TP9',
  'tp10': 'TP10',
  'entryPrice': "Prix d'ouverture",
  'entryDate': "Date d'ouverture",
  'takeProfit': 'Prise de profit',
  'exitPrice': 'Prix de clôture',
  'exitDate': 'Date de clôture',
  'profitLoss': 'Profits/Pertes',
  'allTime': 'Tout le temps',
  'last24': 'Dernières 24 heures',
  'last30': 'Derniers 30 jours',
  'last7': 'Derniers 7 jours',
  'channelSelect': 'Sélectionner un canal',
  'allChannels': 'Tous les canaux',
  'timeSelect': "Sélectionner l'heure",
  'error': "Erreur",
  tradeHistory: "Historique des transactions",
  totalPnL: 'P/L total',
  profitLossByApi: 'Profits/pertes par API',
  tradeSearch: 'Rechercher une transaction...',
  allExchanges: 'Toutes les bourses',
  realizedPnL: 'P/L réalisé',
  perCompletedTrade: 'Par transaction terminée',
  profitableTrades: 'Transactions rentables',
  ticket: 'Ticket',
  direction: "Direction",
  openPrice: "Prix d'ouverture",
  openTime: "Heure d'ouverture",
  volume: 'Volume',
  closePrice: 'Prix de clôture',
  closeTime: 'Heure de clôture',
  status: 'Statut',
  completed: 'Terminé',
  open: 'Ouverture',
  allTrades: 'Toutes les transactions',
  'signals.title': 'Signaux',
  'signals.activeSignals': 'Signaux actifs',
  'signals.signalHistory': 'Historique des signaux',
  'signals.channel': 'Canal',
  'signals.symbol': 'Symbole',
  'signals.direction': 'Direction',
  'signals.openPrice': 'Ouverture',
  'signals.openDate': "Date d'ouverture",
  'signals.closePrice': 'Clôture',
  'signals.closeDate': 'Date de clôture',
  'signals.stopLoss': 'Stop Loss',
  'signals.takeProfit': 'Prise de profit',
  'signals.profitLoss': 'Profits/Pertes',
  'signals.totalTrades': 'TOTAL DES TRANSACTIONS',
  'signals.winRate': 'TAUX DE RÉUSSITE',
  'signals.totalPL': 'P/L TOTAL',
  'signals.avgTrade': 'TRANSACTION MOYENNE',
  'signals.openPositions': 'Positions ouvertes',
  'signals.closedPositions': 'Positions fermées',
  'signals.cumulativePL': 'Pertes/Gains cumulés',
  'signals.plByChannel': 'Profits/pertes par canal au fil du temps',
  'signals.noChartData': "Pas assez de données pour le graphique.",
  'signals.channelName': 'Nom du canal :',
  'signals.trendDirection': 'Direction de la tendance :',
  'signals.entry1': 'Entrée 1 :',
  'signals.entry2': 'Entrée 2 :',
  'signals.sl': 'SL :',
  'signals.tp': 'TP',
  'backtest.noResults': 'Aucun résultat trouvé',
  'backtest.results': 'Résultats du backtest',
  'backtest.profitChart': 'Graphique des profits',
  'backtest.simulationTrades': 'Transactions de simulation',
  'backtest.lot': 'Lot',
  'retry': 'Réessayer',
  goBack: "Retour",
  channelOwnerApply: "Demande de propriétaire de canal",
  channelNamePlaceholder: "Entrez le nom du canal",
  channelLink: "Lien du canal",
  followerCount: "Nombre d'abonnés",
  fullName: "Nom complet",
  email: "E-mail",
  phoneNumber: "Numéro de téléphone",
  ownerTelegram: "Nom d'utilisateur Telegram",
  agreementAccept: "J'ai lu et j'accepte le contrat de partenariat",
  submit: "Envoyer",
  submitting: "Envoi en cours...",
  telegram_channels: "Canaux Telegram",
  total_signals: "Total des signaux",
  success_rate: "Taux de réussite",
  total_profit: "Profit total",
  subscribers: "Nombre d'abonnés",
  per_month: "mois",
  channel_loading: "Chargement des informations du canal...",
  channel_not_found: "Informations sur le canal introuvables",
  back_to_channels: "Retour aux canaux",
  no_channels_found: "Aucun canal trouvé pour le moment.",
  success: "Succès",
  application_success: "Votre demande a été envoyée avec succès.",
  error_occurred: "Une erreur s'est produite",
  accept_agreement_warning: "Veuillez accepter le contrat de partenariat.",
  fill_all_fields_warning: "Veuillez remplir tous les champs.",
  confirmation_title: 'Demande confirmée',
  confirmation_message: "Votre demande a été reçue avec succès. Nous vous contacterons dans les plus brefs délais.",
  confirmation_return: "Retour à l'accueil",
  go_to_channel: "Aller au canal",
  subscribe: "S'abonner",
  closed_signals: "Signaux fermés",
  cumulative_profit_loss: "Pertes/Gains cumulés",
  profit_loss_per_channel: "Profits/pertes par canal au fil du temps",
  total: "Total",
  openDate: "Date d'ouverture",
  closeDate: "Date de clôture",
  channelNameLabel: "Nom du canal",
  subscription_title: "Abonnement",
  adminMenu: "Menu administrateur",
  members: "Membres",
  memberNotifications: "Notifications des membres",
  channelNotifications: "Notifications du canal",
  botChannels: {
    loadError: "Échec du chargement des canaux du bot",
    unknownDeleteError: "Erreur de suppression inconnue",
    deleteError: "Échec de la suppression",
    deleteSuccess: "Canal du bot supprimé avec succès",
    deleteErrorDetailed: "Erreur lors de la suppression du canal du bot : {{error}}",
    channelId: "ID du canal",
    channelName: "Nom du canal",
    status: "Statut",
    actions: "Actions",
    admin: "Admin",
    description: "Description",
    registerDate: "Date d'enregistrement",
    channelImageAlt: "Image du canal",
    title: "Canaux du bot",
    addChannel: "Ajouter un canal",
    pageDescription: "Vous pouvez afficher et gérer les canaux de bot enregistrés dans le système.",
    searchPlaceholder: "Rechercher par nom de canal ou ID...",
    deleteConfirmTitle: "Confirmation de la suppression du canal du bot",
    deleteConfirmDesc: "Êtes-vous sûr de vouloir supprimer définitivement ce canal de bot ?",
    confirmDelete: "Oui, supprimer",
  },
  subscriptions: "Abonnements",
  subscriptionPackages: "Forfaits d'abonnement",
  'signalsList.title': "Derniers signaux",
  'signalsList.description': "Derniers signaux de trading du canal",
  'signalsList.viewAll': "Voir tous les signaux →",
  'tradesList.viewAll': "Voir toutes les transactions →",
  subscriptionHistory: "Historique des abonnements",
  allActiveAndPastSubscriptions: "Tous vos abonnements actifs et passés",
  ended: "Terminé",
  start: "Début",
  end: "Fin",
  noSubscriptionFound: "Vous n'avez pas encore d'abonnement.",
  upgradeToPremium: "Passer à Premium",
  monthlyPlan: "Mensuel",
  monthlyAccess: "accès premium pendant un mois",
  selectPlan: "Sélectionner le forfait",
  enterPassword: "Entrez le mot de passe",
  login: "Connexion",
  'Tüm sinyallere erişim': "Accès à tous les signaux",
  'Manuel trading': "Trading manuel",
  'Temel destek': "Support de base",
  'Tanışma Paketi': "Forfait de bienvenue",
  'Öncelikli destek': "Support prioritaire",
  '3 aylık indirim': "Réduction de 3 mois",
  'Premium destek': "Support Premium",
  '6 aylık indirim': "Réduction de 6 mois",
  'VIP destek': "Support VIP",
  'Yıllık indirim': "Réduction annuelle",
  threeMonthPlan: "3 mois",
  sixMonthPlan: "6 mois",
  yearlyPlan: "Annuel",
  premiumAccess: "accès premium pour",
  accessAllSignals: "Accès à tous les signaux",
  manualTrading: "Trading manuel",
  basicSupport: "Support de base",
  welcomePackage: "Forfait de bienvenue",
  prioritySupport: "Support prioritaire",
  threeMonthDiscount: "Réduction de 3 mois",
  premiumSupport: "Support Premium",
  sixMonthDiscount: "Réduction de 6 mois",
  vipSupport: "Support VIP",
  annualDiscount: "Réduction annuelle",
  'settings.title': 'Paramètres API',
  'settings.invalidId': 'ID invalide',
  'settings.apiNotFound': 'API introuvable',
  'settings.loadingError': 'Erreur de chargement',
  'settings.missingApiId': 'ID API manquant',
  'settings.autoTrade': 'Transaction automatique',
  'settings.autoTradeDescription': "Activer la fonction de trading automatique",
  'settings.entryAmount': 'Montant de la transaction',
  'settings.entryAmountDescription': 'Montant à utiliser pour chaque transaction',
  'settings.entryAmountPlaceholder': 'Saisir le montant',
  'settings.usdt': 'USDT',
  'settings.entryAmountQuestion': 'Quel devrait être le montant de la transaction ?',
  'settings.entryAmountExplanation1': 'Ce montant est le montant de départ à utiliser dans chaque transaction.',
  'settings.entryAmountExplanation2': "La taille de la position changera en fonction du ratio de levier.",
  'settings.leverage': 'Effet de levier',
  'settings.leverageDescription': 'Ratio de levier à utiliser pour vos transactions',
  'settings.safe': 'Sûr',
  'settings.risky': 'Risqué',
  'settings.tradeType': 'Type de transaction',
  'settings.tradeTypeDescription': 'Type de marge à utiliser pour vos transactions',
  'settings.isolated': 'Isolé',
  'settings.cross': 'Croisé',
  'settings.profitTradeSettings': 'Paramètres de prise de profit',
  'settings.profitTradeSettingsDescription': 'Niveaux et stratégies de prise de profit',
  'settings.selectEntryType': "Sélectionnez le type d'entrée",
  'settings.closed': 'Fermé',
  'settings.percentage': 'Pourcentage',
  'settings.fixedAmount': 'Montant fixe',
  'settings.percentSymbol': '%',
  'settings.tp1': 'TP1',
  'settings.tp2': 'TP2',
  'settings.tp3': 'TP3',
  'settings.tp4': 'TP4',
  'settings.tp5': 'TP5',
  'settings.tp6': 'TP6',
  'settings.tp7': 'TP7',
  'settings.tp8': 'TP8',
  'settings.tp9': 'TP9',
  'settings.tp10': 'TP10',
  'settings.tpLevel': 'Niveau de TP',
  'settings.stoplossTradeSettings': 'Paramètres de Stop Loss',
  'settings.stoplossTradeSettingsDescription': 'Niveaux et stratégies de stop loss',
  'settings.selectStopLossStrategy': 'Sélectionner une stratégie de stop loss',
  'settings.useSignalSL': 'Utiliser le SL du signal',
  'settings.customStopLoss': 'Stop Loss personnalisé',
  'settings.customStopLossInput': 'Niveau de Stop Loss',
  'settings.customStopLossHelp': "Niveau de stop loss en pourcentage par rapport au prix d'ouverture de la position",
  'settings.stopLossActionSettings': "Paramètres d'action Stop Loss",
  'settings.stopLossActionDescription': 'Actions à entreprendre lorsque le stop loss est déclenché',
  'settings.selectAction': "Sélectionner une action",
  'settings.trailStopAction': 'Trailing Stop',
  'settings.costWithdrawAction': 'Retirer au coût',
  'settings.specificLossAction': 'Fermer à une perte spécifique',
  'settings.specificLossLabel': 'Pourcentage de perte',
  'settings.specificLossQuestion': 'Comment fonctionne cette fonctionnalité ?',
  'settings.specificLossExplanation': "La position est automatiquement fermée lorsque le pourcentage de perte spécifié est atteint.",
  'settings.costWithdraw': 'Retirer au coût',
  'settings.costWithdrawDescription': "Déplacer le niveau de stop loss au seuil de rentabilité lorsque l'objectif de profit est atteint",
  'settings.selectLevel': 'Sélectionner un niveau',
  'settings.none': 'Aucun',
  'settings.costWithdrawQuestion': 'Comment fonctionne le retrait au coût ?',
  'settings.costWithdrawExplanation1': "Lorsque le niveau de TP sélectionné est atteint, le niveau de stop loss est déplacé au seuil de rentabilité.",
  'settings.costWithdrawExplanation2': "De cette façon, dans le pire des cas, vous atteignez le seuil de rentabilité.",
  'settings.costWithdrawExplanation3': 'Si le marché se retourne, le gain est protégé.',
  'settings.costWithdrawExplanation4': "C'est une stratégie importante pour la gestion des risques.",
  'settings.trailStop': 'Trailing Stop',
  'settings.trailStopDescription': 'Déplacer automatiquement le niveau de stop loss vers le haut',
  'settings.trailStopQuestion': 'Comment fonctionne le trailing stop ?',
  'settings.trailStopExplanation': "Lorsque le niveau de TP sélectionné est atteint, le stop loss est automatiquement déplacé dans la zone de profit et continue de monter à mesure que le prix augmente.",
  'settings.maxOrders': 'Ordres maximum',
  'settings.maxOrdersDescription': "Nombre maximum d'ordres pouvant être ouverts simultanément",
  'settings.save': 'Enregistrer',
  'settings.saving': 'Enregistrement en cours...',
  'settings.saveSuccess': 'Paramètres enregistrés avec succès.',
  'settings.saveError': "Une erreur s'est produite lors de l'enregistrement des paramètres.",
  addSignal: 'Ajouter un signal',
  addNewSignal: 'Ajouter un nouveau signal',
  fillSignalDetails: 'Remplir les détails du signal',
  exchange: "Bourse",
  side: "Direction",
  pnl: "Pertes/Gains",
  action: "Action",
  close: "Fermer",
  trend: 'Tendance',
  selectTrend: 'Sélectionner une tendance',
  long: "LONG",
  short: "SHORT",
  stopLossPercentage: 'Pourcentage de Stop Loss',
  entryRangePercentage: "Pourcentage de la plage d'entrée",
  takeProfitCount: 'Nombre de prises de profit',
  takeProfitRangePercentage: 'Pourcentage de la plage de prise de profit',
  createSignal: 'Créer un signal',
  signal_channels: "Canaux de signaux",
  addYourChannel: "Ajouter votre canal",
  welcomeMessage: "Bienvenue,",
  openTradesLabel: "transactions en cours",
  apiStatusLabel: "comptes de bourse connectés",
  addApiKey: "Ajouter une clé API",
  noApiKeyCta: "Vous n'avez pas encore de clé API. Cliquez pour connecter votre compte de bourse.",
  noOpenTrades: "Aucune transaction ouverte",
  waiting: 'En attente',
  openStatus: "Ouvert",
  recentTrades: "Transactions récentes",
  yourRecentTrades: "Vos dernières transactions",
  openClose: "Ouverture/Clôture",
  noTradesFound: "Aucune transaction trouvée",
  unknown: 'Inconnu',
  closed: 'Fermé',
  loginError: "Erreur de connexion",
  loginWithTelegram: "Se connecter avec Telegram",
  pleaseLoginWithTelegram: "Veuillez vous connecter via Telegram.",
  pageNotFound: "Oups ! Page non trouvée",
  returnToHome: "Retour à l'accueil",
  copied: "Copié",
  copiedToClipboard: "{{field}} copié dans le presse-papiers.",
  copyError: "Échec de la copie.",
  fillAllFields: "Veuillez remplir tous les champs.",
  sessionNotFound: "Informations de session introuvables",
  userNotFound: "Utilisateur introuvable",
  newApiKey: "Nouvelle clé API :",
  addApiKeyError: "Impossible d'ajouter la clé API",
  newApiKeyNotFound: "Nouvelle clé API introuvable",
  apiKeyAdded: 'Clé API "{{name}}" ajoutée avec succès.',
  apiKeyAddError: "Erreur lors de l'ajout de la clé API :",
  addNewApiKey: "Ajouter une nouvelle clé API",
  addNewApiKeyDesc: "Entrez ici les informations de votre clé API de bourse. Ces informations seront utilisées pour les transactions automatiques.",
  exchangeType: "Type de bourse",
  name: "Nom",
  apiKeyNamePlaceholder: "Ex: Binance Futures",
  apiKeyNameDesc: "Entrez un nom pour vous aider à vous souvenir de cette clé.",
  apiKeyPlaceholder: "Entrez votre clé API",
  apiSecretPlaceholder: "Entrez votre secret API",
  apiSecretDesc: "Ne partagez votre clé API et votre secret avec personne.",
  signalChannel: "Canal de signaux",
  searchChannelPlaceholder: "Rechercher par nom de canal ou ID...",
  selectedChannel: "Canal sélectionné",
  subscriptionPackage: "Forfait d'abonnement",
  select: "Sélectionner",
  cancel: "Annuler",
  adding: "Ajout en cours...",
  save: "Enregistrer",
  apiKeyIdNotFound: "ID de clé API introuvable",
  apiKeyNotFound: "Clé API introuvable",
  apiKeyLoadError: "Erreur lors du chargement de la clé API :",
  apiKeyLoadErrorText: "Échec du chargement de la clé API",
  apiKeyUpdated: 'Clé API "{{name}}" mise à jour avec succès.',
  apiKeyUpdateError: "Erreur lors de la mise à jour de la clé API :",
  apiKeyUpdateErrorText: "Échec de la mise à jour de la clé API.",
  editApiKey: "Modifier la clé API",
  editApiKeyDesc: "Mettez à jour les informations de votre clé API de bourse.",
  saving: "Enregistrement en cours...",
  apiChannelDesc: "Sélectionnez le canal de signaux que la clé API écoutera.",
  deleteApiKeyConfirm: "Êtes-vous sûr de vouloir supprimer cette clé API ?",
  apiKeyDeleted: "Clé API supprimée avec succès.",
  apiKeyDeleteError: "Une erreur s'est produite lors de la suppression de la clé API.",
  networkError: "La réponse du réseau n'était pas ok",
  fetchDetailsError: "Échec de la récupération des détails",
  deleteFailed: "Échec de la suppression",
  apiKeyDeletedSuccess: "Clé API supprimée avec succès",
  adminApiKeys: {
    title: "Clés API",
    description: "Vous pouvez afficher et gérer les clés API des utilisateurs.",
    searchPlaceholder: "Rechercher par nom d'utilisateur ou nom...",
    user: "Utilisateur",
    apiName: "Nom de l'API",
    apiType: "Type d'API",
    packageEnd: "Fin du forfait",
    channel: "Canal",
    packageStart: "Début du forfait",
    lotsize: "Taille du lot",
    leverage: "Effet de levier",
    marginType: "Type de marge",
    maxOrders: "Ordres max",
    autoTrade: "Auto Trade",
    actions: "Actions",
    deleteConfirmTitle: "Confirmation de la suppression",
    deleteConfirmDesc: "Êtes-vous sûr de vouloir supprimer définitivement cette clé API ? Cette action est irréversible.",
  },
  on: "Activé",
  off: "Désactivé",
  delete: "Supprimer",
  edit: "Modifier",
  admin: {
    notLoggedIn: "Vous n'êtes pas connecté en tant qu'administrateur ou votre session a expiré. Veuillez vous reconnecter.",
    faq: {
      addSuccess: "Question ajoutée avec succès !",
      addError: "Échec de l'ajout de l'enregistrement",
      addNewTitle: "Ajouter une nouvelle question",
      addNewDesc: "Vous pouvez ajouter une nouvelle question fréquemment posée.",
      questionInfo: "Informations sur la question",
      question: "Question",
      questionPlaceholder: "Écrivez la question...",
      answer: "Réponse",
      answerPlaceholder: "Écrivez la réponse...",
    }
  },
  fromLastMonth: "par rapport au mois dernier",
  newTrades: "nouvelle transaction",
  thisMonth: "ce mois-ci",
  dashboard: "Tableau de bord",
  switchToLightMode: "Passer en mode clair",
  switchToDarkMode: "Passer en mode sombre",
  noTradeOnPage: "Aucune transaction à afficher sur cette page.",
  tradeRecordNotFound: "Enregistrement de transaction introuvable.",
  previousPage: "Page précédente",
  nextPage: "Page suivante",
  filterByExchange: "Filtrer par bourse",
  profit: "Profit",
  "faq.title": "FAQ",
  tradeStatus: {
    waiting: "En attente",
    open: "Ouvert",
    completed: "Terminé",
    failed: "Échoué",
    unknown: "Inconnu"
  },
  orderError: "Erreur de commande : {{error}}",
};

export default fr; 