const it = {
  anasayfa: "Homepage",
  apiKeys: "Le mie chiavi API",
  addNew: "Aggiungi nuovo",
  noApiKey: "Nessuna chiave API è stata ancora aggiunta. Puoi iniziare con il pulsante 'Aggiungi nuovo'.",
  trades: "Operazioni",
  signals: "Segnali",
  channels: "Canali",
  partnership: "Partnership",
  subscription: "Abbonamento",
  adminLogin: "Login amministratore",
  loading: "Caricamento...",
  telegramRequired: "Devi accedere tramite Telegram per utilizzare questa applicazione.",
  goToTelegram: "Vai a Telegram",
  dashboardTitle: "Pannello di controllo",
  lastUpdate: "Ultimo aggiornamento",
  activeSignals: "Segnali attivi",
  activeSignalsDesc: "Segnale da elaborare",
  openTrades: "Operazioni aperte",
  openTradesDesc: "Puoi monitorare le tue operazioni in corso qui.",
  performance: "Performance",
  performanceDesc: "P/L di 30 giorni",
  apiStatus: "Stato API",
  apiStatusDesc: "Borsa attiva",
  son_islemler: "Ultime operazioni",
  sizin_adiniza_gerceklesen_son_islemler: "Ultime operazioni eseguite per tuo conto",
  signalsList: {
    title: "Ultimi segnali",
    description: "Ultimi segnali di trading dal canale",
    viewAll: "Visualizza tutti i segnali →"
  },
  buy: "ACQUISTA",
  sell: "VENDI",
  unit: "unità",
  tradesList: { viewAll: "Visualizza tutte le operazioni →" },
  entry: "Ingresso",
  usdt: "USDT",
  active: "ATTIVO",
  filled: "ESEGUITO",
  cancelled: "ANNULLATO",
  balanceChart: {
    title: "Andamento del saldo",
    balance: "Saldo",
    description: "Variazione del tuo portafoglio nel tempo"
  },
  'backtest.title': 'Backtest',
  'backtest.channelSelect': 'Selezione canale',
  'backtest.channelSelectDescription': 'Seleziona il canale dei segnali da utilizzare per il backtest',
  'backtest.selectChannel': 'Seleziona canale',
  'backtest.dateRange': 'Intervallo di date',
  'backtest.dateRangeDescription': "Seleziona l'intervallo di date per il backtest",
  'backtest.selectDateRange': "Seleziona l'intervallo di date",
  'backtest.autoTrade': 'Trading automatico',
  'backtest.autoTradeDescription': 'Esegui automaticamente i segnali',
  'backtest.entryAmount': 'Importo di ingresso',
  'backtest.entryAmountDescription': 'Importo da utilizzare per ogni operazione',
  'backtest.enterAmount': 'Inserisci importo',
  'backtest.usdt': 'USDT',
  'backtest.howMuchToEnter': 'Con quanti dollari vuoi entrare nell\'operazione?',
  'backtest.enterAmountInfo1': "Moltiplica l'importo che desideri investire per il rapporto di leva che hai impostato e inserisci il risultato come lotto.",
  'backtest.enterAmountInfo2': 'Esempio: se vuoi entrare in un\'operazione con 20$ e leva 20X: 20 × 20 = 400. In questo caso, devi scrivere 400 nella sezione Lotto.',
  'backtest.leverage': 'Leva',
  'backtest.leverageDescription': 'Rapporto di leva per le tue operazioni',
  'backtest.safe': '1x (Sicuro)',
  'backtest.risky': '25x (Rischioso)',
  'backtest.tradeType': 'Tipo di operazione',
  'backtest.tradeTypeDescription': "Seleziona il tipo di margine dell'operazione",
  'backtest.isolated': 'ISOLATO',
  'backtest.cross': 'INCROCIATO',
  'backtest.profitTradeSettings': 'Impostazioni di Take Profit',
  'backtest.profitTradeSettingsDescription': 'Seleziona la strategia di chiusura delle operazioni',
  'backtest.profitTradeSelect': 'Seleziona la strategia di take profit',
  'backtest.closed': 'Chiuso',
  'backtest.percentage': 'Percentuale del saldo',
  'backtest.fixedAmount': 'Importo fisso',
  'backtest.tp': 'TP',
  'backtest.tpLevel': 'Livello TP',
  'backtest.stopLossSettings': 'Impostazioni di Stop Loss',
  'backtest.stopLossSettingsDescription': 'Seleziona l\'azione dopo lo stop',
  'backtest.actionSelect': 'Seleziona azione',
  'backtest.trailStop': 'TrailStop',
  'backtest.costToWithdraw': 'Ritira al costo',
  'backtest.specificLoss': "Chiudi l'operazione a una perdita specifica",
  'backtest.lossPercentage': 'Chiudi in perdita (%)',
  'backtest.specificLossInfo': 'Cos\'è "Chiudi l\'operazione a una perdita specifica"?',
  'backtest.specificLossInfo1': "Questa funzione garantisce che la tua operazione venga chiusa automaticamente quando raggiunge un certo tasso di perdita.",
  'backtest.specificLossInfo2': "Ad esempio, se desideri che la posizione si chiuda quando la tua operazione subisce una perdita del 10% rispetto al prezzo spot, è sufficiente inserire il 10% nell'impostazione pertinente.",
  'backtest.costToWithdrawDescription': 'Seleziona il livello di ritiro al costo',
  'backtest.levelSelect': 'Seleziona livello',
  'backtest.none': 'Nessuno',
  'backtest.tp1': 'TP1',
  'backtest.tp2': 'TP2',
  'backtest.tp3': 'TP3',
  'backtest.tp4': 'TP4',
  'backtest.tp5': 'TP5',
  'backtest.costToWithdrawInfo': 'Cos\'è "Ritira al costo"?',
  'backtest.costToWithdrawInfo1': "Quando viene raggiunto il livello di take profit 1 o 2, l'ordine di stop loss viene spostato al livello di ingresso.",
  'backtest.costToWithdrawInfo2': 'Grazie a questo sistema, la gestione del rischio diventa più sicura proteggendo i guadagni.',
  'backtest.trailStopDescription': 'Seleziona il livello di TrailStop',
  'backtest.trailStopInfo': 'Cos\'è il "Trail Stop"?',
  'backtest.trailStopInfo1': "Un trailing stop consente al livello di stop loss di spostarsi automaticamente verso l'alto con il prezzo man mano che la tua operazione diventa redditizia.",
  'backtest.trailStopInfo2': "L'obiettivo è proteggere i profitti esistenti in caso di inversioni di mercato.",
  'backtest.maxOrders': 'Numero massimo di ordini',
  'backtest.maxOrdersDescription': 'Imposta il numero massimo di ordini',
  'backtest.startBacktest': 'Avvia backtest',
  'totalTrades': 'Operazioni totali',
  'winRate': 'Tasso di vincita',
  'totalPL': 'P/L totale',
  'averageTrade': 'Operazione media',
  'openPositions': 'Posizioni aperte',
  'closedPositions': 'Posizioni chiuse',
  'cumulativeProfitLoss': 'Perdite/Guadagni cumulativi',
  'profitLossPerChannel': "Profitto/perdita per API nel tempo",
  'notEnoughData': 'Dati insufficienti per il grafico.',
  'date': 'Data',
  'previous': 'Precedente',
  'next': 'Successivo',
  'page': 'Pagina',
  'trendDirection': 'Direzione del trend',
  'symbol': "Coppia",
  'entry1': 'Ingresso 1',
  'entry2': 'Ingresso 2',
  'sl': 'SL',
  'tp1': 'TP1',
  'tp2': 'TP2',
  'tp3': 'TP3',
  'tp4': 'TP4',
  'tp5': 'TP5',
  'tp6': 'TP6',
  'tp7': 'TP7',
  'tp8': 'TP8',
  'tp9': 'TP9',
  'tp10': 'TP10',
  'entryPrice': "Prezzo di apertura",
  'entryDate': "Data di apertura",
  'takeProfit': 'Take Profit',
  'exitPrice': 'Prezzo di chiusura',
  'exitDate': 'Data di chiusura',
  'profitLoss': 'Profitto/Perdita',
  'allTime': 'Sempre',
  'last24': 'Ultime 24 ore',
  'last30': 'Ultimi 30 giorni',
  'last7': 'Ultimi 7 giorni',
  'channelSelect': 'Seleziona canale',
  'allChannels': 'Tutti i canali',
  'timeSelect': 'Seleziona ora',
  'error': "Errore",
  tradeHistory: 'Cronologia operazioni',
  totalPnL: 'P/L totale',
  profitLossByApi: 'Profitto/perdita per API',
  tradeSearch: 'Cerca operazione...',
  allExchanges: 'Tutte le borse',
  realizedPnL: 'P/L realizzato',
  perCompletedTrade: 'Per operazione completata',
  profitableTrades: 'Operazioni redditizie',
  ticket: 'Ticket',
  direction: "Direzione",
  openPrice: 'Prezzo di apertura',
  openTime: 'Ora di apertura',
  volume: 'Volume',
  closePrice: 'Prezzo di chiusura',
  closeTime: 'Ora di chiusura',
  status: 'Stato',
  completed: 'Completato',
  open: 'Apertura',
  allTrades: 'Tutte le operazioni',
  'signals.title': 'Segnali',
  'signals.activeSignals': 'Segnali attivi',
  'signals.signalHistory': 'Cronologia segnali',
  'signals.channel': 'Canale',
  'signals.symbol': 'Simbolo',
  'signals.direction': 'Direzione',
  'signals.openPrice': 'Apertura',
  'signals.openDate': 'Data di apertura',
  'signals.closePrice': 'Chiusura',
  'signals.closeDate': 'Data di chiusura',
  'signals.stopLoss': 'Stop Loss',
  'signals.takeProfit': 'Take Profit',
  'signals.profitLoss': 'Profitto/Perdita',
  'signals.totalTrades': 'OPERAZIONI TOTALI',
  'signals.winRate': 'TASSO DI VINCITA',
  'signals.totalPL': 'P/L TOTALE',
  'signals.avgTrade': 'OPERAZIONE MEDIA',
  'signals.openPositions': 'Posizioni aperte',
  'signals.closedPositions': 'Posizioni chiuse',
  'signals.cumulativePL': 'Perdite/Guadagni cumulativi',
  'signals.plByChannel': 'Profitto/perdita per canale nel tempo',
  'signals.noChartData': 'Dati insufficienti per il grafico.',
  'signals.channelName': 'Nome canale:',
  'signals.trendDirection': 'Direzione del trend:',
  'signals.entry1': 'Ingresso 1:',
  'signals.entry2': 'Ingresso 2:',
  'signals.sl': 'SL:',
  'signals.tp': 'TP',
  'backtest.noResults': 'Nessun risultato trovato',
  'backtest.results': 'Risultati backtest',
  'backtest.profitChart': 'Grafico dei profitti',
  'backtest.simulationTrades': 'Operazioni di simulazione',
  'backtest.lot': 'Lotto',
  'retry': 'Riprova',
  goBack: "Indietro",
  channelOwnerApply: "Richiesta proprietario canale",
  channelNamePlaceholder: "Inserisci il nome del canale",
  channelLink: "Link del canale",
  followerCount: "Numero di follower",
  fullName: "Nome completo",
  email: "E-mail",
  phoneNumber: "Numero di telefono",
  ownerTelegram: "Nome utente Telegram",
  agreementAccept: "Ho letto e accetto il contratto di partnership",
  submit: "Invia",
  submitting: "Invio in corso...",
  telegram_channels: "Canali Telegram",
  total_signals: "Segnali totali",
  success_rate: "Tasso di successo",
  total_profit: "Profitto totale",
  subscribers: "Numero di iscritti",
  per_month: "mese",
  channel_loading: "Caricamento informazioni canale...",
  channel_not_found: "Informazioni canale non trovate",
  back_to_channels: "Torna ai canali",
  no_channels_found: "Nessun canale ancora trovato.",
  success: "Successo",
  application_success: "La tua richiesta è stata inviata con successo.",
  error_occurred: "Si è verificato un errore",
  accept_agreement_warning: "Si prega di accettare il contratto di partnership.",
  fill_all_fields_warning: "Si prega di compilare tutti i campi.",
  confirmation_title: 'Richiesta confermata',
  confirmation_message: "La tua richiesta è stata ricevuta con successo. Ti contatteremo il prima possibile.",
  confirmation_return: "Torna alla homepage",
  go_to_channel: "Vai al canale",
  subscribe: "Iscriviti",
  closed_signals: "Segnali chiusi",
  cumulative_profit_loss: "Perdite/Guadagni cumulativi",
  profit_loss_per_channel: "Profitto/perdita per canale nel tempo",
  total: "Totale",
  openDate: "Data di apertura",
  closeDate: "Data di chiusura",
  channelNameLabel: "Nome canale",
  subscription_title: "Abbonamento",
  adminMenu: "Menu amministratore",
  members: "Membri",
  memberNotifications: "Notifiche membri",
  channelNotifications: "Notifiche canale",
  botChannels: {
    loadError: "Impossibile caricare i canali bot",
    unknownDeleteError: "Errore di eliminazione sconosciuto",
    deleteError: "Eliminazione non riuscita",
    deleteSuccess: "Canale bot eliminato con successo",
    deleteErrorDetailed: "Errore durante l'eliminazione del canale bot: {{error}}",
    channelId: "ID canale",
    channelName: "Nome canale",
    status: "Stato",
    actions: "Azioni",
    admin: "Admin",
    description: "Descrizione",
    registerDate: "Data di registrazione",
    channelImageAlt: "Immagine canale",
    title: "Canali bot",
    addChannel: "Aggiungi canale",
    pageDescription: "Puoi visualizzare e gestire i canali bot registrati nel sistema.",
    searchPlaceholder: "Cerca per nome canale o ID...",
    deleteConfirmTitle: "Conferma eliminazione canale bot",
    deleteConfirmDesc: "Sei sicuro di voler eliminare permanentemente questo canale bot?",
    confirmDelete: "Sì, elimina",
  },
  subscriptions: "Abbonamenti",
  subscriptionPackages: "Pacchetti di abbonamento",
  'signalsList.title': "Ultimi segnali",
  'signalsList.description': "Ultimi segnali di trading dal canale",
  'signalsList.viewAll': "Visualizza tutti i segnali →",
  'tradesList.viewAll': "Visualizza tutte le operazioni →",
  subscriptionHistory: "Cronologia abbonamenti",
  allActiveAndPastSubscriptions: "Tutti i tuoi abbonamenti attivi e passati",
  ended: "Terminato",
  start: "Inizio",
  end: "Fine",
  noSubscriptionFound: "Non hai ancora un abbonamento.",
  upgradeToPremium: "Passa a Premium",
  monthlyPlan: "Mensile",
  monthlyAccess: "accesso premium per un mese",
  selectPlan: "Seleziona piano",
  enterPassword: "Inserisci la password",
  login: "Accedi",
  // Caratteristiche
  'Tüm sinyallere erişim': "Accesso a tutti i segnali",
  'Manuel trading': "Trading manuale",
  'Temel destek': "Supporto di base",
  'Tanışma Paketi': "Pacchetto di benvenuto",
  'Öncelikli destek': "Supporto prioritario",
  '3 aylık indirim': "Sconto di 3 mesi",
  'Premium destek': "Supporto Premium",
  '6 aylık indirim': "Sconto di 6 mesi",
  'VIP destek': "Supporto VIP",
  'Yıllık indirim': "Sconto annuale",
  threeMonthPlan: "3 mesi",
  sixMonthPlan: "6 mesi",
  yearlyPlan: "Annuale",
  premiumAccess: "accesso premium per",
  accessAllSignals: "Accesso a tutti i segnali",
  manualTrading: "Trading manuale",
  basicSupport: "Supporto di base",
  welcomePackage: "Pacchetto di benvenuto",
  prioritySupport: "Supporto prioritario",
  threeMonthDiscount: "Sconto di 3 mesi",
  premiumSupport: "Supporto Premium",
  sixMonthDiscount: "Sconto di 6 mesi",
  vipSupport: "Supporto VIP",
  annualDiscount: "Sconto annuale",
  'settings.title': 'Impostazioni API',
  'settings.invalidId': 'ID non valido',
  'settings.apiNotFound': 'API non trovata',
  'settings.loadingError': 'Errore di caricamento',
  'settings.missingApiId': 'ID API mancante',
  'settings.autoTrade': 'Operazione automatica',
  'settings.autoTradeDescription': 'Attiva la funzione di trading automatico',
  'settings.entryAmount': 'Importo operazione',
  'settings.entryAmountDescription': 'Importo da utilizzare per ogni operazione',
  'settings.entryAmountPlaceholder': 'Inserisci importo',
  'settings.usdt': 'USDT',
  'settings.entryAmountQuestion': 'Quale dovrebbe essere l\'importo dell\'operazione?',
  'settings.entryAmountExplanation1': 'Questo importo è l\'importo iniziale da utilizzare in ogni operazione.',
  'settings.entryAmountExplanation2': "La dimensione della posizione cambierà in base al rapporto di leva.",
  'settings.leverage': 'Leva',
  'settings.leverageDescription': 'Rapporto di leva da utilizzare per le tue operazioni',
  'settings.safe': 'Sicuro',
  'settings.risky': 'Rischioso',
  'settings.tradeType': 'Tipo di operazione',
  'settings.tradeTypeDescription': 'Tipo di margine da utilizzare per le tue operazioni',
  'settings.isolated': 'Isolato',
  'settings.cross': 'Increspato',
  'settings.profitTradeSettings': 'Impostazioni di Take Profit',
  'settings.profitTradeSettingsDescription': 'Livelli e strategie di take profit',
  'settings.selectEntryType': 'Seleziona il tipo di ingresso',
  'settings.closed': 'Chiuso',
  'settings.percentage': 'Percentuale',
  'settings.fixedAmount': 'Importo fisso',
  'settings.percentSymbol': '%',
  'settings.tp1': 'TP1',
  'settings.tp2': 'TP2',
  'settings.tp3': 'TP3',
  'settings.tp4': 'TP4',
  'settings.tp5': 'TP5',
  'settings.tp6': 'TP6',
  'settings.tp7': 'TP7',
  'settings.tp8': 'TP8',
  'settings.tp9': 'TP9',
  'settings.tp10': 'TP10',
  'settings.tpLevel': 'Livello TP',
  'settings.stoplossTradeSettings': 'Impostazioni di Stop Loss',
  'settings.stoplossTradeSettingsDescription': 'Livelli e strategie di stop loss',
  'settings.selectStopLossStrategy': 'Seleziona la strategia di stop loss',
  'settings.useSignalSL': 'Usa SL del segnale',
  'settings.customStopLoss': 'Stop Loss personalizzato',
  'settings.customStopLossInput': 'Livello di Stop Loss',
  'settings.customStopLossHelp': 'Livello di stop loss percentuale basato sul prezzo di apertura della posizione',
  'settings.stopLossActionSettings': 'Impostazioni azione Stop Loss',
  'settings.stopLossActionDescription': 'Azioni da intraprendere quando viene attivato lo stop loss',
  'settings.selectAction': 'Seleziona azione',
  'settings.trailStopAction': 'Trailing Stop',
  'settings.costWithdrawAction': 'Ritira al costo',
  'settings.specificLossAction': 'Chiudi a perdita specifica',
  'settings.specificLossLabel': 'Percentuale di perdita',
  'settings.specificLossQuestion': 'Come funziona questa funzione?',
  'settings.specificLossExplanation': 'La posizione viene chiusa automaticamente quando viene raggiunta la percentuale di perdita specificata.',
  'settings.costWithdraw': 'Ritira al costo',
  'settings.costWithdrawDescription': 'Sposta il livello di stop loss al pareggio quando viene raggiunto l\'obiettivo di profitto',
  'settings.selectLevel': 'Seleziona livello',
  'settings.none': 'Nessuno',
  'settings.costWithdrawQuestion': 'Come funziona il ritiro al costo?',
  'settings.costWithdrawExplanation1': "Quando viene raggiunto il livello TP selezionato, il livello di stop loss viene spostato al pareggio.",
  'settings.costWithdrawExplanation2': "In questo modo, nel peggiore dei casi, si va in pareggio.",
  'settings.costWithdrawExplanation3': 'Se il mercato si inverte, il guadagno è protetto.',
  'settings.costWithdrawExplanation4': 'È una strategia importante per la gestione del rischio.',
  'settings.trailStop': 'Trailing Stop',
  'settings.trailStopDescription': 'Sposta automaticamente il livello di stop loss verso l\'alto',
  'settings.trailStopQuestion': 'Come funziona il trailing stop?',
  'settings.trailStopExplanation': "Quando viene raggiunto il livello TP selezionato, lo stop loss viene automaticamente spostato nella zona di profitto e continua a salire man mano che il prezzo aumenta.",
  'settings.maxOrders': 'Ordini massimi',
  'settings.maxOrdersDescription': 'Numero massimo di ordini che possono essere aperti contemporaneamente',
  'settings.save': 'Salva',
  'settings.saving': 'Salvataggio...',
  'settings.saveSuccess': 'Impostazioni salvate con successo.',
  'settings.saveError': 'Si è verificato un errore durante il salvataggio delle impostazioni.',
  addSignal: 'Aggiungi segnale',
  addNewSignal: 'Aggiungi nuovo segnale',
  fillSignalDetails: 'Compila i dettagli del segnale',
  exchange: "Borsa",
  side: "Direzione",
  pnl: "Profitto/Perdita",
  action: "Azione",
  close: "Chiudi",
  trend: 'Tendenza',
  selectTrend: 'Seleziona tendenza',
  long: "LONG",
  short: "SHORT",
  stopLossPercentage: 'Percentuale di Stop Loss',
  entryRangePercentage: "Percentuale dell intervallo di ingresso",
  takeProfitCount: 'Numero di Take Profit',
  takeProfitRangePercentage: 'Percentuale dell\'intervallo di Take Profit',
  createSignal: 'Crea segnale',
  signal_channels: "Canali di segnali",
  addYourChannel: "Aggiungi il tuo canale",
  welcomeMessage: "Benvenuto,",
  openTradesLabel: "operazioni in corso",
  apiStatusLabel: "conti di borsa collegati",
  addApiKey: "Aggiungi chiave API",
  noApiKeyCta: "Non hai ancora una chiave API. Clicca per collegare il tuo conto di borsa.",
  noOpenTrades: "Nessuna operazione aperta",
  waiting: 'In attesa',
  openStatus: "Aperto",
  recentTrades: "Operazioni recenti",
  yourRecentTrades: "Le tue ultime operazioni",
  openClose: "Apertura/Chiusura",
  noTradesFound: "Nessuna operazione trovata",
  unknown: 'Sconosciuto',
  closed: 'Chiuso',
  loginError: "Errore di accesso",
  loginWithTelegram: "Accedi con Telegram",
  pleaseLoginWithTelegram: "Si prega di accedere tramite Telegram.",
  pageNotFound: "Oops! Pagina non trovata",
  returnToHome: "Torna alla homepage",
  copied: "Copiato",
  copiedToClipboard: "{{field}} copiato negli appunti.",
  copyError: "Copia non riuscita.",
  fillAllFields: "Si prega di compilare tutti i campi.",
  sessionNotFound: "Informazioni sulla sessione non trovate",
  userNotFound: "Utente non trovato",
  newApiKey: "Nuova chiave API:",
  addApiKeyError: "Impossibile aggiungere la chiave API",
  newApiKeyNotFound: "Nuova chiave API non trovata",
  apiKeyAdded: 'Chiave API "{{name}}" aggiunta con successo.',
  apiKeyAddError: "Errore durante l'aggiunta della chiave API:",
  addNewApiKey: "Aggiungi nuova chiave API",
  addNewApiKeyDesc: "Inserisci qui le informazioni della tua chiave API di borsa. Queste informazioni verranno utilizzate per le operazioni automatiche.",
  exchangeType: "Tipo di borsa",
  name: "Nome",
  apiKeyNamePlaceholder: "Es: Binance Futures",
  apiKeyNameDesc: "Inserisci un nome che ti aiuti a ricordare questa chiave.",
  apiKeyPlaceholder: "Inserisci la tua chiave API",
  apiSecretPlaceholder: "Inserisci il tuo segreto API",
  apiSecretDesc: "Non condividere la tua chiave API e il tuo segreto con nessuno.",
  signalChannel: "Canale dei segnali",
  searchChannelPlaceholder: "Cerca per nome canale o ID...",
  selectedChannel: "Canale selezionato",
  subscriptionPackage: "Pacchetto di abbonamento",
  select: "Seleziona",
  cancel: "Annulla",
  adding: "Aggiunta in corso...",
  save: "Salva",
  apiKeyIdNotFound: "ID chiave API non trovato",
  apiKeyNotFound: "Chiave API non trovata",
  apiKeyLoadError: "Errore durante il caricamento della chiave API:",
  apiKeyLoadErrorText: "Impossibile caricare la chiave API",
  apiKeyUpdated: 'Chiave API "{{name}}" aggiornata con successo.',
  apiKeyUpdateError: "Errore durante l'aggiornamento della chiave API:",
  apiKeyUpdateErrorText: "Impossibile aggiornare la chiave API.",
  editApiKey: "Modifica chiave API",
  editApiKeyDesc: "Aggiorna le informazioni della tua chiave API di borsa.",
  saving: "Salvataggio...",
  apiChannelDesc: "Seleziona il canale dei segnali che la chiave API ascolterà.",
  deleteApiKeyConfirm: "Sei sicuro di voler eliminare questa chiave API?",
  apiKeyDeleted: "Chiave API eliminata con successo.",
  apiKeyDeleteError: "Si è verificato un errore durante l'eliminazione della chiave API.",
  networkError: "La risposta della rete non era ok",
  fetchDetailsError: "Impossibile recuperare i dettagli",
  deleteFailed: "Eliminazione non riuscita",
  apiKeyDeletedSuccess: "Chiave API eliminata con successo",
  adminApiKeys: {
    title: "Chiavi API",
    description: "Puoi visualizzare e gestire le chiavi API degli utenti.",
    searchPlaceholder: "Cerca per nome utente o nome...",
    user: "Utente",
    apiName: "Nome API",
    apiType: "Tipo API",
    packageEnd: "Fine pacchetto",
    channel: "Canale",
    packageStart: "Inizio pacchetto",
    lotsize: "Dimensione lotto",
    leverage: "Leva",
    marginType: "Tipo di margine",
    maxOrders: "Ordini massimi",
    autoTrade: "Auto Trade",
    actions: "Azioni",
    deleteConfirmTitle: "Conferma eliminazione",
    deleteConfirmDesc: "Sei sicuro di voler eliminare permanentemente questa chiave API? Questa azione è irreversibile.",
  },
  on: "Attivo",
  off: "Disattivato",
  delete: "Elimina",
  edit: "Modifica",
  admin: {
    notLoggedIn: "Non hai effettuato l'accesso come amministratore o la tua sessione è scaduta. Effettua nuovamente l'accesso.",
    faq: {
      addSuccess: "Domanda aggiunta con successo!",
      addError: "Impossibile aggiungere il record",
      addNewTitle: "Aggiungi nuova domanda",
      addNewDesc: "Puoi aggiungere una nuova domanda frequente.",
      questionInfo: "Informazioni sulla domanda",
      question: "Domanda",
      questionPlaceholder: "Scrivi la domanda...",
      answer: "Risposta",
      answerPlaceholder: "Scrivi la risposta...",
    }
  },
  fromLastMonth: "rispetto al mese scorso",
  newTrades: "nuova operazione",
  thisMonth: "questo mese",
  dashboard: "Pannello di controllo",
  switchToLightMode: "Passa alla modalità chiara",
  switchToDarkMode: "Passa alla modalità scura",
  noTradeOnPage: "Nessuna operazione da visualizzare in questa pagina.",
  tradeRecordNotFound: "Record dell'operazione non trovato.",
  previousPage: "Pagina precedente",
  nextPage: "Pagina successiva",
  filterByExchange: "Filtra per borsa",
  profit: "Profitto",
  "faq.title": "FAQ",
  tradeStatus: {
    waiting: "In attesa",
    open: "Aperto",
    completed: "Completato",
    failed: "Fallito",
    unknown: "Sconosciuto"
  },
  orderError: "Errore ordine: {{error}}",
};

export default it; 