const ru = {
  anasayfa: "Главная",
  apiKeys: "Мои ключи API",
  addNew: "Добавить новый",
  noApiKey: "Ключ API еще не добавлен. Вы можете начать с кнопки 'Добавить новый'.",
  trades: "Сделки",
  signals: "Сигналы",
  channels: "Каналы",
  partnership: "Партнерство",
  subscription: "Подписка",
  adminLogin: "Вход для администратора",
  loading: "Загрузка...",
  telegramRequired: "Вам необходимо войти через Telegram, чтобы использовать это приложение.",
  goToTelegram: "Перейти в Telegram",
  dashboardTitle: "Панель управления",
  lastUpdate: "Последнее обновление",
  activeSignals: "Активные сигналы",
  activeSignalsDesc: "Сигнал для обработки",
  openTrades: "Открытые сделки",
  openTradesDesc: "Вы можете отслеживать свои текущие сделки здесь.",
  performance: "Производительность",
  performanceDesc: "P/L за 30 дней",
  apiStatus: "Статус API",
  apiStatusDesc: "Активная биржа",
  son_islemler: "Последние сделки",
  sizin_adiniza_gerceklesen_son_islemler: "Последние сделки, совершенные от вашего имени",
  signalsList: {
    title: "Последние сигналы",
    description: "Последние торговые сигналы с канала",
    viewAll: "Посмотреть все сигналы →"
  },
  buy: "ПОКУПКА",
  sell: "ПРОДАЖА",
  unit: "единица",
  tradesList: { viewAll: "Посмотреть все сделки →" },
  entry: "Вход",
  usdt: "USDT",
  active: "АКТИВНО",
  filled: "ИСПОЛНЕНО",
  cancelled: "ОТМЕНЕНО",
  balanceChart: {
    title: "Динамика баланса",
    balance: "Баланс",
    description: "Изменение вашего портфеля с течением времени"
  },
  'backtest.title': 'Бэктест',
  'backtest.channelSelect': 'Выбор канала',
  'backtest.channelSelectDescription': 'Выберите канал сигналов для бэктеста',
  'backtest.selectChannel': 'Выберите канал',
  'backtest.dateRange': 'Диапазон дат',
  'backtest.dateRangeDescription': 'Выберите диапазон дат для бэктеста',
  'backtest.selectDateRange': 'Выберите диапазон дат',
  'backtest.autoTrade': 'Автоматическая торговля',
  'backtest.autoTradeDescription': 'Автоматически исполнять сигналы',
  'backtest.entryAmount': 'Сумма входа',
  'backtest.entryAmountDescription': 'Сумма для использования в каждой сделке',
  'backtest.enterAmount': 'Введите сумму',
  'backtest.usdt': 'USDT',
  'backtest.howMuchToEnter': 'С какой суммой в долларах вы хотите войти в сделку?',
  'backtest.enterAmountInfo1': 'Умножьте сумму, которую вы хотите инвестировать, на установленный вами коэффициент кредитного плеча и введите результат в качестве лота.',
  'backtest.enterAmountInfo2': 'Пример: если вы хотите войти в сделку с 20$ и кредитным плечом 20X: 20 × 20 = 400. В этом случае вы должны написать 400 в разделе "Лот".',
  'backtest.leverage': 'Кредитное плечо',
  'backtest.leverageDescription': 'Коэффициент кредитного плеча для ваших сделок',
  'backtest.safe': '1x (Безопасно)',
  'backtest.risky': '25x (Рискованно)',
  'backtest.tradeType': 'Тип сделки',
  'backtest.tradeTypeDescription': 'Выберите тип маржи сделки',
  'backtest.isolated': 'ИЗОЛИРОВАННАЯ',
  'backtest.cross': 'ПЕРЕКРЕСТНАЯ',
  'backtest.profitTradeSettings': 'Настройки фиксации прибыли',
  'backtest.profitTradeSettingsDescription': 'Выберите стратегию закрытия сделки',
  'backtest.profitTradeSelect': 'Выберите стратегию фиксации прибыли',
  'backtest.closed': 'Закрыто',
  'backtest.percentage': 'Процент от баланса',
  'backtest.fixedAmount': 'Фиксированная сумма',
  'backtest.tp': 'TP',
  'backtest.tpLevel': 'Уровень TP',
  'backtest.stopLossSettings': 'Настройки стоп-лосса',
  'backtest.stopLossSettingsDescription': 'Выберите действие после стоп-лосса',
  'backtest.actionSelect': 'Выберите действие',
  'backtest.trailStop': 'Трейлинг-стоп',
  'backtest.costToWithdraw': 'Вывод по себестоимости',
  'backtest.specificLoss': 'Закрыть сделку при определенном убытке',
  'backtest.lossPercentage': 'Закрыть с убытком (%)',
  'backtest.specificLossInfo': 'Что такое "Закрыть сделку при определенном убытке"?',
  'backtest.specificLossInfo1': 'Эта функция гарантирует автоматическое закрытие вашей сделки при достижении определенного уровня убытка.',
  'backtest.specificLossInfo2': 'Например, если вы хотите, чтобы позиция закрылась, когда ваша сделка понесет убыток в 10% от спотовой цены, просто введите 10% в соответствующей настройке.',
  'backtest.costToWithdrawDescription': 'Выберите уровень вывода по себестоимости',
  'backtest.levelSelect': 'Выберите уровень',
  'backtest.none': 'Нет',
  'backtest.tp1': 'TP1',
  'backtest.tp2': 'TP2',
  'backtest.tp3': 'TP3',
  'backtest.tp4': 'TP4',
  'backtest.tp5': 'TP5',
  'backtest.costToWithdrawInfo': 'Что такое "Вывод по себестоимости"?',
  'backtest.costToWithdrawInfo1': 'При достижении уровня тейк-профита 1 или 2 ордер стоп-лосс перемещается на уровень входа.',
  'backtest.costToWithdrawInfo2': 'Благодаря этой системе управление рисками становится более безопасным при защите прибыли.',
  'backtest.trailStopDescription': 'Выберите уровень трейлинг-стопа',
  'backtest.trailStopInfo': 'Что такое "Трейлинг-стоп"?',
  'backtest.trailStopInfo1': 'Трейлинг-стоп позволяет уровню стоп-лосса автоматически перемещаться вверх вместе с ценой по мере того, как ваша сделка становится прибыльной.',
  'backtest.trailStopInfo2': 'Цель состоит в том, чтобы защитить существующую прибыль в случае разворота рынка.',
  'backtest.maxOrders': 'Максимальное количество ордеров',
  'backtest.maxOrdersDescription': 'Определите максимальное количество ордеров',
  'backtest.startBacktest': 'Начать бэктест',
  'totalTrades': 'Всего сделок',
  'winRate': 'Коэффициент выигрышей',
  'totalPL': 'Общий P/L',
  'averageTrade': 'Средняя сделка',
  'openPositions': 'Открытые позиции',
  'closedPositions': 'Закрытые позиции',
  'cumulativeProfitLoss': 'Накопленная прибыль/убыток',
  'profitLossPerChannel': 'Прибыль/убыток по API с течением времени',
  'notEnoughData': 'Недостаточно данных для графика.',
  'date': 'Дата',
  'previous': 'Предыдущий',
  'next': 'Следующий',
  'page': 'Страница',
  'trendDirection': 'Направление тренда',
  'symbol': "Пара",
  'entry1': 'Вход 1',
  'entry2': 'Вход 2',
  'sl': 'SL',
  'tp1': 'TP1',
  'tp2': 'TP2',
  'tp3': 'TP3',
  'tp4': 'TP4',
  'tp5': 'TP5',
  'tp6': 'TP6',
  'tp7': 'TP7',
  'tp8': 'TP8',
  'tp9': 'TP9',
  'tp10': 'TP10',
  'entryPrice': "Цена входа",
  'entryDate': "Дата входа",
  'takeProfit': 'Тейк-профит',
  'exitPrice': 'Цена выхода',
  'exitDate': 'Дата выхода',
  'profitLoss': 'Прибыль/Убыток',
  'allTime': 'За все время',
  'last24': 'Последние 24 часа',
  'last30': 'Последние 30 дней',
  'last7': 'Последние 7 дней',
  'channelSelect': 'Выберите канал',
  'allChannels': 'Все каналы',
  'timeSelect': 'Выберите время',
  'error': "Ошибка",
  tradeHistory: 'История сделок',
  totalPnL: 'Общий P/L',
  profitLossByApi: 'Прибыль/убыток по API',
  tradeSearch: 'Поиск сделки...',
  allExchanges: 'Все биржи',
  realizedPnL: 'Реализованный P/L',
  perCompletedTrade: 'За завершенную сделку',
  profitableTrades: 'Прибыльные сделки',
  ticket: 'Тикет',
  direction: "Направление",
  openPrice: 'Цена открытия',
  openTime: 'Время открытия',
  volume: 'Объем',
  closePrice: 'Цена закрытия',
  closeTime: 'Время закрытия',
  status: 'Статус',
  completed: 'Завершено',
  open: 'Открытие',
  allTrades: 'Все сделки',
  'signals.title': 'Сигналы',
  'signals.activeSignals': 'Активные сигналы',
  'signals.signalHistory': 'История сигналов',
  'signals.channel': 'Канал',
  'signals.symbol': 'Символ',
  'signals.direction': 'Направление',
  'signals.openPrice': 'Открытие',
  'signals.openDate': 'Дата открытия',
  'signals.closePrice': 'Закрытие',
  'signals.closeDate': 'Дата закрытия',
  'signals.stopLoss': 'Стоп-лосс',
  'signals.takeProfit': 'Тейк-профит',
  'signals.profitLoss': 'Прибыль/Убыток',
  'signals.totalTrades': 'ВСЕГО СДЕЛОК',
  'signals.winRate': 'КОЭФФИЦИЕНТ ВЫИГРЫШЕЙ',
  'signals.totalPL': 'ОБЩИЙ P/L',
  'signals.avgTrade': 'СРЕДНЯЯ СДЕЛКА',
  'signals.openPositions': 'Открытые позиции',
  'signals.closedPositions': 'Закрытые позиции',
  'signals.cumulativePL': 'Накопленная прибыль/убыток',
  'signals.plByChannel': 'Прибыль/убыток по каналам с течением времени',
  'signals.noChartData': 'Недостаточно данных для графика.',
  'signals.channelName': 'Название канала:',
  'signals.trendDirection': 'Направление тренда:',
  'signals.entry1': 'Вход 1:',
  'signals.entry2': 'Вход 2:',
  'signals.sl': 'SL:',
  'signals.tp': 'TP',
  'backtest.noResults': 'Результаты не найдены',
  'backtest.results': 'Результаты бэктеста',
  'backtest.profitChart': 'График прибыли',
  'backtest.simulationTrades': 'Симуляционные сделки',
  'backtest.lot': 'Лот',
  'retry': 'Повторить',
  goBack: "Назад",
  channelOwnerApply: "Заявка владельца канала",
  channelNamePlaceholder: "Введите название канала",
  channelLink: "Ссылка на канал",
  followerCount: "Количество подписчиков",
  fullName: "Полное имя",
  email: "Электронная почта",
  phoneNumber: "Номер телефона",
  ownerTelegram: "Имя пользователя Telegram",
  agreementAccept: "Я прочитал и принимаю партнерское соглашение",
  submit: "Отправить",
  submitting: "Отправка...",
  telegram_channels: "Каналы Telegram",
  total_signals: "Всего сигналов",
  success_rate: "Коэффициент успешности",
  total_profit: "Общая прибыль",
  subscribers: "Количество подписчиков",
  per_month: "месяц",
  channel_loading: "Загрузка информации о канале...",
  channel_not_found: "Информация о канале не найдена",
  back_to_channels: "Вернуться к каналам",
  no_channels_found: "Каналы пока не найдены.",
  success: "Успешно",
  application_success: "Ваша заявка успешно отправлена.",
  error_occurred: "Произошла ошибка",
  accept_agreement_warning: "Пожалуйста, примите партнерское соглашение.",
  fill_all_fields_warning: "Пожалуйста, заполните все поля.",
  confirmation_title: 'Заявка подтверждена',
  confirmation_message: "Ваша заявка успешно принята. Мы свяжемся с вами в ближайшее время.",
  confirmation_return: "Вернуться на главную",
  go_to_channel: "Перейти на канал",
  subscribe: "Подписаться",
  closed_signals: "Закрытые сигналы",
  cumulative_profit_loss: "Накопленная прибыль/убыток",
  profit_loss_per_channel: "Прибыль/убыток по каналам с течением времени",
  total: "Всего",
  openDate: "Дата открытия",
  closeDate: "Дата закрытия",
  channelNameLabel: "Название канала",
  subscription_title: "Подписка",
  adminMenu: "Меню администратора",
  members: "Участники",
  memberNotifications: "Уведомления для участников",
  channelNotifications: "Уведомления канала",
  botChannels: {
    loadError: "Не удалось загрузить каналы бота",
    unknownDeleteError: "Неизвестная ошибка удаления",
    deleteError: "Не удалось удалить",
    deleteSuccess: "Канал бота успешно удален",
    deleteErrorDetailed: "Ошибка при удалении канала бота: {{error}}",
    channelId: "ID канала",
    channelName: "Название канала",
    status: "Статус",
    actions: "Действия",
    admin: "Админ",
    description: "Описание",
    registerDate: "Дата регистрации",
    channelImageAlt: "Изображение канала",
    title: "Каналы бота",
    addChannel: "Добавить канал",
    pageDescription: "Вы можете просматривать и управлять каналами ботов, зарегистрированными в системе.",
    searchPlaceholder: "Поиск по названию канала или ID...",
    deleteConfirmTitle: "Подтверждение удаления канала бота",
    deleteConfirmDesc: "Вы уверены, что хотите навсегда удалить этот канал бота?",
    confirmDelete: "Да, удалить",
  },
  subscriptions: "Подписки",
  subscriptionPackages: "Пакеты подписки",
  'signalsList.title': "Последние сигналы",
  'signalsList.description': "Последние торговые сигналы с канала",
  'signalsList.viewAll': "Посмотреть все сигналы →",
  'tradesList.viewAll': "Посмотреть все сделки →",
  subscriptionHistory: "История подписок",
  allActiveAndPastSubscriptions: "Все ваши активные и прошлые подписки",
  ended: "Завершено",
  start: "Начало",
  end: "Конец",
  noSubscriptionFound: "У вас еще нет подписки.",
  upgradeToPremium: "Перейти на Премиум",
  monthlyPlan: "Ежемесячно",
  monthlyAccess: "премиум-доступ на месяц",
  selectPlan: "Выбрать план",
  enterPassword: "Введите пароль",
  login: "Войти",
  // Особенности
  'Tüm sinyallere erişim': "Доступ ко всем сигналам",
  'Manuel trading': "Ручная торговля",
  'Temel destek': "Базовая поддержка",
  'Tanışma Paketi': "Приветственный пакет",
  'Öncelikli destek': "Приоритетная поддержка",
  '3 aylık indirim': "Скидка на 3 месяца",
  'Premium destek': "Премиум-поддержка",
  '6 aylık indirim': "Скидка на 6 месяцев",
  'VIP destek': "VIP-поддержка",
  'Yıllık indirim': "Годовая скидка",
  threeMonthPlan: "3 месяца",
  sixMonthPlan: "6 месяцев",
  yearlyPlan: "Годовой",
  premiumAccess: "премиум-доступ на",
  accessAllSignals: "Доступ ко всем сигналам",
  manualTrading: "Ручная торговля",
  basicSupport: "Базовая поддержка",
  welcomePackage: "Приветственный пакет",
  prioritySupport: "Приоритетная поддержка",
  threeMonthDiscount: "Скидка на 3 месяца",
  premiumSupport: "Премиум-поддержка",
  sixMonthDiscount: "Скидка на 6 месяцев",
  vipSupport: "VIP-поддержка",
  annualDiscount: "Годовая скидка",
  'settings.title': 'Настройки API',
  'settings.invalidId': 'Неверный ID',
  'settings.apiNotFound': 'API не найден',
  'settings.loadingError': 'Ошибка загрузки',
  'settings.missingApiId': 'Отсутствует ID API',
  'settings.autoTrade': 'Автоматическая сделка',
  'settings.autoTradeDescription': 'Активировать функцию автоматической торговли',
  'settings.entryAmount': 'Сумма сделки',
  'settings.entryAmountDescription': 'Сумма для использования в каждой сделке',
  'settings.entryAmountPlaceholder': 'Введите сумму',
  'settings.usdt': 'USDT',
  'settings.entryAmountQuestion': 'Какой должна быть сумма сделки?',
  'settings.entryAmountExplanation1': 'Эта сумма является начальной суммой для использования в каждой сделке.',
  'settings.entryAmountExplanation2': 'Размер позиции будет меняться в зависимости от коэффициента кредитного плеча.',
  'settings.leverage': 'Кредитное плечо',
  'settings.leverageDescription': 'Коэффициент кредитного плеча для ваших сделок',
  'settings.safe': 'Безопасно',
  'settings.risky': 'Рискованно',
  'settings.tradeType': 'Тип сделки',
  'settings.tradeTypeDescription': 'Тип маржи для ваших сделок',
  'settings.isolated': 'Изолированная',
  'settings.cross': 'Перекрестная',
  'settings.profitTradeSettings': 'Настройки фиксации прибыли',
  'settings.profitTradeSettingsDescription': 'Уровни и стратегии фиксации прибыли',
  'settings.selectEntryType': 'Выберите тип входа',
  'settings.closed': 'Закрыто',
  'settings.percentage': 'Процент',
  'settings.fixedAmount': 'Фиксированная сумма',
  'settings.percentSymbol': '%',
  'settings.tp1': 'TP1',
  'settings.tp2': 'TP2',
  'settings.tp3': 'TP3',
  'settings.tp4': 'TP4',
  'settings.tp5': 'TP5',
  'settings.tp6': 'TP6',
  'settings.tp7': 'TP7',
  'settings.tp8': 'TP8',
  'settings.tp9': 'TP9',
  'settings.tp10': 'TP10',
  'settings.tpLevel': 'Уровень TP',
  'settings.stoplossTradeSettings': 'Настройки стоп-лосса',
  'settings.stoplossTradeSettingsDescription': 'Уровни и стратегии стоп-лосса',
  'settings.selectStopLossStrategy': 'Выберите стратегию стоп-лосса',
  'settings.useSignalSL': 'Использовать SL сигнала',
  'settings.customStopLoss': 'Пользовательский стоп-лосс',
  'settings.customStopLossInput': 'Уровень стоп-лосса',
  'settings.customStopLossHelp': 'Процентный уровень стоп-лосса от цены открытия позиции',
  'settings.stopLossActionSettings': 'Настройки действий при стоп-лоссе',
  'settings.stopLossActionDescription': 'Действия, которые необходимо предпринять при срабатывании стоп-лосса',
  'settings.selectAction': 'Выберите действие',
  'settings.trailStopAction': 'Трейлинг-стоп',
  'settings.costWithdrawAction': 'Вывод по себестоимости',
  'settings.specificLossAction': 'Закрыть при определенном убытке',
  'settings.specificLossLabel': 'Процент убытка',
  'settings.specificLossQuestion': 'Как работает эта функция?',
  'settings.specificLossExplanation': 'Позиция автоматически закрывается при достижении указанного процента убытка.',
  'settings.costWithdraw': 'Вывод по себестоимости',
  'settings.costWithdrawDescription': 'Переместить уровень стоп-лосса в безубыток при достижении цели по прибыли',
  'settings.selectLevel': 'Выберите уровень',
  'settings.none': 'Нет',
  'settings.costWithdrawQuestion': 'Как работает вывод по себестоимости?',
  'settings.costWithdrawExplanation1': 'При достижении выбранного уровня TP уровень стоп-лосса перемещается в безубыток.',
  'settings.costWithdrawExplanation2': 'Таким образом, в худшем случае вы выходите в безубыток.',
  'settings.costWithdrawExplanation3': 'Если рынок развернется, прибыль будет защищена.',
  'settings.costWithdrawExplanation4': 'Это важная стратегия управления рисками.',
  'settings.trailStop': 'Трейлинг-стоп',
  'settings.trailStopDescription': 'Автоматически перемещать уровень стоп-лосса вверх',
  'settings.trailStopQuestion': 'Как работает трейлинг-стоп?',
  'settings.trailStopExplanation': 'При достижении выбранного уровня TP стоп-лосс автоматически перемещается в прибыльную зону и продолжает подниматься по мере роста цены.',
  'settings.maxOrders': 'Максимум ордеров',
  'settings.maxOrdersDescription': 'Максимальное количество ордеров, которые могут быть открыты одновременно',
  'settings.save': 'Сохранить',
  'settings.saving': 'Сохранение...',
  'settings.saveSuccess': 'Настройки успешно сохранены.',
  'settings.saveError': 'Произошла ошибка при сохранении настроек.',
  addSignal: 'Добавить сигнал',
  addNewSignal: 'Добавить новый сигнал',
  fillSignalDetails: 'Заполните детали сигнала',
  exchange: "Биржа",
  side: "Направление",
  pnl: "Прибыль/Убыток",
  action: "Действие",
  close: "Закрыть",
  trend: 'Тренд',
  selectTrend: 'Выберите тренд',
  long: "ДЛИННАЯ",
  short: "КОРОТКАЯ",
  stopLossPercentage: 'Процент стоп-лосса',
  entryRangePercentage: 'Процент диапазона входа',
  takeProfitCount: 'Количество тейк-профитов',
  takeProfitRangePercentage: 'Процент диапазона тейк-профита',
  createSignal: 'Создать сигнал',
  signal_channels: "Каналы сигналов",
  addYourChannel: "Добавьте свой канал",
  welcomeMessage: "Добро пожаловать,",
  openTradesLabel: "открытых сделок",
  apiStatusLabel: "подключенных биржевых счетов",
  addApiKey: "Добавить ключ API",
  noApiKeyCta: "У вас еще нет ключа API. Нажмите, чтобы подключить свой биржевой счет.",
  noOpenTrades: "Нет открытых сделок",
  waiting: "В ожидании",
  openStatus: "Открыто",
  recentTrades: "Последние сделки",
  yourRecentTrades: "Ваши последние сделки",
  openClose: "Открытие/Закрытие",
  noTradesFound: "Сделки не найдены",
  unknown: "Неизвестно",
  closed: "Закрыто",
  loginError: "Ошибка входа",
  loginWithTelegram: "Войти через Telegram",
  pleaseLoginWithTelegram: "Пожалуйста, войдите через Telegram.",
  pageNotFound: "Упс! Страница не найдена",
  returnToHome: "Вернуться на главную",
  copied: "Скопировано",
  copiedToClipboard: "{{field}} скопировано в буфер обмена.",
  copyError: "Не удалось скопировать.",
  fillAllFields: "Пожалуйста, заполните все поля.",
  sessionNotFound: "Информация о сеансе не найдена",
  userNotFound: "Пользователь не найден",
  newApiKey: "Новый ключ API:",
  addApiKeyError: "Не удалось добавить ключ API",
  newApiKeyNotFound: "Новый ключ API не найден",
  apiKeyAdded: 'Ключ API "{{name}}" успешно добавлен.',
  apiKeyAddError: "Ошибка при добавлении ключа API:",
  addNewApiKey: "Добавить новый ключ API",
  addNewApiKeyDesc: "Введите здесь информацию о вашем ключе API биржи. Эта информация будет использоваться для автоматических сделок.",
  exchangeType: "Тип биржи",
  name: "Имя",
  apiKeyNamePlaceholder: "Пример: Binance Futures",
  apiKeyNameDesc: "Введите имя, которое поможет вам запомнить этот ключ.",
  apiKeyPlaceholder: "Введите ваш ключ API",
  apiSecretPlaceholder: "Введите ваш секрет API",
  apiSecretDesc: "Никому не сообщайте свой ключ API и секрет.",
  signalChannel: "Канал сигналов",
  searchChannelPlaceholder: "Поиск по названию канала или ID...",
  selectedChannel: "Выбранный канал",
  subscriptionPackage: "Пакет подписки",
  select: "Выбрать",
  cancel: "Отмена",
  adding: "Добавление...",
  save: "Сохранить",
  apiKeyIdNotFound: "ID ключа API не найден",
  apiKeyNotFound: "Ключ API не найден",
  apiKeyLoadError: "Ошибка при загрузке ключа API:",
  apiKeyLoadErrorText: "Не удалось загрузить ключ API",
  apiKeyUpdated: 'Ключ API "{{name}}" успешно обновлен.',
  apiKeyUpdateError: "Ошибка при обновлении ключа API:",
  apiKeyUpdateErrorText: "Не удалось обновить ключ API.",
  editApiKey: "Изменить ключ API",
  editApiKeyDesc: "Обновите информацию о вашем ключе API биржи.",
  saving: "Сохранение...",
  apiChannelDesc: "Выберите канал сигналов, который будет прослушивать ключ API.",
  deleteApiKeyConfirm: "Вы уверены, что хотите удалить этот ключ API?",
  apiKeyDeleted: "Ключ API успешно удален.",
  apiKeyDeleteError: "Произошла ошибка при удалении ключа API.",
  networkError: "Сетевой ответ был не в порядке",
  fetchDetailsError: "Не удалось получить детали",
  deleteFailed: "Не удалось удалить",
  apiKeyDeletedSuccess: "Ключ API успешно удален",
  adminApiKeys: {
    title: "Ключи API",
    description: "Вы можете просматривать и управлять ключами API пользователей.",
    searchPlaceholder: "Поиск по имени пользователя или имени...",
    user: "Пользователь",
    apiName: "Имя API",
    apiType: "Тип API",
    packageEnd: "Окончание пакета",
    channel: "Канал",
    packageStart: "Начало пакета",
    lotsize: "Размер лота",
    leverage: "Кредитное плечо",
    marginType: "Тип маржи",
    maxOrders: "Макс. ордеров",
    autoTrade: "Авто-торговля",
    actions: "Действия",
    deleteConfirmTitle: "Подтверждение удаления",
    deleteConfirmDesc: "Вы уверены, что хотите навсегда удалить этот ключ API? Это действие необратимо.",
  },
  on: "Вкл.",
  off: "Выкл.",
  delete: "Удалить",
  edit: "Изменить",
  admin: {
    notLoggedIn: "Вы не вошли в систему как администратор или ваш сеанс истек. Пожалуйста, войдите снова.",
    faq: {
      addSuccess: "Вопрос успешно добавлен!",
      addError: "Не удалось добавить запись",
      addNewTitle: "Добавить новый вопрос",
      addNewDesc: "Вы можете добавить новый часто задаваемый вопрос.",
      questionInfo: "Информация о вопросе",
      question: "Вопрос",
      questionPlaceholder: "Напишите вопрос...",
      answer: "Ответ",
      answerPlaceholder: "Напишите ответ...",
    }
  },
  fromLastMonth: "по сравнению с прошлым месяцем",
  newTrades: "новая сделка",
  thisMonth: "в этом месяце",
  dashboard: "Панель управления",
  switchToLightMode: "Переключиться на светлый режим",
  switchToDarkMode: "Переключиться на темный режим",
  noTradeOnPage: "На этой странице нет сделок для отображения.",
  tradeRecordNotFound: "Запись о сделке не найдена.",
  previousPage: "Предыдущая страница",
  nextPage: "Следующая страница",
  filterByExchange: "Фильтровать по бирже",
  profit: "Прибыль",
  "faq.title": "ЧАВО",
  tradeStatus: {
    waiting: "Ожидание",
    open: "Открыто",
    completed: "Завершено",
    failed: "Ошибка",
    unknown: "Неизвестно"
  },
  orderError: "Ошибка ордера: {{error}}",
};

export default ru; 