const tr = {
  anasayfa: "Anasayfa",
  apiKeys: "API Anahtarlarım",
  addNew: "Yeni Ekle",
  noApiKey: "Henüz API anahtarı eklenmemiş. 'Yeni Ekle' butonu ile başlayabilirsiniz.",
  trades: "İşlemler",
  signals: "Sinyaller",
  channels: "Kanallar",
  partnership: "Ortaklık",
  subscription: "Abonelik",
  adminLogin: "Admin Giriş",
  loading: "Yükleniyor...",
  telegramRequired: "Bu uygulamayı kullanmak için Telegram üzerinden giriş yapmanız gerekmektedir.",
  goToTelegram: "Telegram'a Git",
  dashboardTitle: "Kontrol Paneli",
  lastUpdate: "Son güncelleme",
  activeSignals: "Aktif Sinyaller",
  activeSignalsDesc: "İşleme alınacak sinyal",
  openTrades: "Açık İşlemler",
  openTradesDesc: "Devam eden işlemlerinizi buradan takip edebilirsiniz.",
  performance: "Performans",
  performanceDesc: "30 günlük K/Z",
  apiStatus: "API Durumu",
  apiStatusDesc: "Aktif borsa",
  son_islemler: "Son İşlemler",
  sizin_adiniza_gerceklesen_son_islemler: "Sizin adınıza gerçekleştirilen son işlemler",
  signalsList: {
    title: "Son Sinyaller",
    description: "Kanaldan gelen son işlem sinyalleri",
    viewAll: "Tüm sinyalleri görüntüle →"
  },
  buy: "ALIŞ",
  sell: "SATIŞ",
  unit: "birim",
  tradesList: { viewAll: "Tüm işlemleri görüntüle →" },
  entry: "Giriş",
  usdt: "USDT",
  active: "AKTİF",
  filled: "DOLU",
  cancelled: "İPTAL",
  balanceChart: {
    title: "Bakiye Gelişimi",
    balance: "Bakiye",
    description: "Portföyünüzün zaman içindeki değişimi"
  },
  'backtest.title': 'Backtest',
  'backtest.channelSelect': 'Kanal Seçimi',
  'backtest.channelSelectDescription': 'Backtest için kullanılacak sinyal kanalını seçin',
  'backtest.selectChannel': 'Kanal seçin',
  'backtest.dateRange': 'Tarih Aralığı',
  'backtest.dateRangeDescription': 'Backtest için tarih aralığını seçin',
  'backtest.selectDateRange': 'Tarih aralığı seçin',
  'backtest.autoTrade': 'Otomatik Trading',
  'backtest.autoTradeDescription': 'Sinyalleri otomatik olarak işleme al',
  'backtest.entryAmount': 'İşleme Giriş Miktarı',
  'backtest.entryAmountDescription': 'Her işlem için kullanılacak miktar',
  'backtest.enterAmount': 'Miktar girin',
  'backtest.usdt': 'USDT',
  'backtest.howMuchToEnter': 'İşleme Kaç Dolar ile Girmek İstersiniz?',
  'backtest.enterAmountInfo1': 'İşleme girmek istediğiniz miktarı, belirlediğiniz kaldıraç oranı ile çarpın ve sonucu lot olarak girin.',
  'backtest.enterAmountInfo2': 'Örnek: 20$ ile 20X kaldıraç kullanarak işleme girmek istiyorsanız: 20 × 20 = 400. Bu durumda Lot kısmına 400 yazmalısınız.',
  'backtest.leverage': 'Kaldıraç',
  'backtest.leverageDescription': 'İşlemleriniz için kaldıraç oranı',
  'backtest.safe': '1x (Güvenli)',
  'backtest.risky': '25x (Riskli)',
  'backtest.tradeType': 'İşlem Türü',
  'backtest.tradeTypeDescription': 'İşlem marjin türünü seçin',
  'backtest.isolated': 'ISOLATED',
  'backtest.cross': 'CROSS',
  'backtest.profitTradeSettings': 'Kar Al İşlem Ayarları',
  'backtest.profitTradeSettingsDescription': 'İşlem kapatma stratejisini seçin',
  'backtest.profitTradeSelect': 'Kar alma stratejisi seçin',
  'backtest.closed': 'Kapalı',
  'backtest.percentage': 'Bakiyenin Yüzdesi',
  'backtest.fixedAmount': 'Sabit Miktar',
  'backtest.noStopLoss': 'Stoploss Yok',
  'backtest.signalSL': 'Sinyal SL',
  'backtest.fixedSL': 'Sabit SL',
  'backtest.fixedSLPercentage': 'Sabit SL (%)',
  'backtest.selectStopLossStrategy': 'Stoploss stratejisi seçin',
  'backtest.starting': 'Başlatılıyor...',
  'backtest.tp': 'TP',
  'backtest.tpLevel': 'TP Seviyesi',
  'backtest.stopLossSettings': 'Zarar Durdur İşlem Ayarları',
  'backtest.stopLossSettingsDescription': 'Stop sonrası aksiyonu seçin',
  'backtest.actionSelect': 'Aksiyon seçin',
  'backtest.trailStop': 'TrailStop',
  'backtest.costToWithdraw': 'Maliyetine Çek',
  'backtest.specificLoss': 'Belirli Zararda İşlem Kapat',
  'backtest.lossPercentage': 'Zararda Kapat (%)',
  'backtest.specificLossInfo': 'Belirli Zararda İşlem Kapat nedir?',
  'backtest.specificLossInfo1': 'Bu özellik, işleminizin belirli bir zarar oranına ulaştığında otomatik olarak kapatılmasını sağlar.',
  'backtest.specificLossInfo2': 'Örneğin, işleminizin spot fiyatına göre %10 zarar ettiğinde pozisyonun kapanmasını istiyorsanız, ilgili ayara %10 yazmanız yeterlidir.',
  'backtest.costToWithdrawDescription': 'Maliyetine çekme seviyesini seçin',
  'backtest.levelSelect': 'Seviye seçin',
  'backtest.none': 'Yok',
  'backtest.tp1': 'TP1',
  'backtest.tp2': 'TP2',
  'backtest.tp3': 'TP3',
  'backtest.tp4': 'TP4',
  'backtest.tp5': 'TP5',
  'backtest.costToWithdrawInfo': 'Maliyete Çek Nedir?',
  'backtest.costToWithdrawInfo1': 'Kâr Al Seviyesi 1 veya 2\'ye ulaşıldığında, Zarar Durdur emri giriş seviyesine taşınır.',
  'backtest.costToWithdrawInfo2': 'Bu sistem sayesinde, kazançlar korunurken risk yönetimi daha güvenli hale getirilir.',
  'backtest.trailStopDescription': 'TrailStop seviyesini seçin',
  'backtest.trailStopInfo': 'Trail Stop Nedir?',
  'backtest.trailStopInfo1': 'Trail stop, işleminiz kâr ettikçe Zarar Durdur seviyesinin otomatik olarak fiyatla birlikte yukarı taşınmasını sağlar.',
  'backtest.trailStopInfo2': 'Amaç, piyasada geri dönüşler olduğunda mevcut kârı korumaktır.',
  'backtest.maxOrders': 'Maks Emir Miktarı',
  'backtest.maxOrdersDescription': 'Maksimum emir sayısını belirleyin',
  'backtest.startBacktest': 'Backtest\'e Başla',
  'totalTrades': 'Toplam İşlem',
  'winRate': 'Kazanma Oranı',
  'totalPL': 'Toplam K/Z',
  'averageTrade': 'Ortalama İşlem',
  'openPositions': 'Açık Pozisyonlar',
  'closedPositions': 'Kapanmış Pozisyonlar',
  'cumulativeProfitLoss': 'Kümülatif Kar/Zarar',
  'profitLossPerChannel': 'Zamana göre API bazında kar/zarar',
  'notEnoughData': 'Grafik için yeterli veri yok.',
  'date': 'Tarih',
  'previous': 'Önceki',
  'next': 'Sonraki',
  'page': 'Sayfa',
  'trendDirection': 'Trend Yönü',
  'symbol': "Parite",
  'entry1': 'Entry 1',
  'entry2': 'Entry 2',
  'sl': 'SL',
  'tp1': 'TP1',
  'tp2': 'TP2',
  'tp3': 'TP3',
  'tp4': 'TP4',
  'tp5': 'TP5',
  'tp6': 'TP6',
  'tp7': 'TP7',
  'tp8': 'TP8',
  'tp9': 'TP9',
  'tp10': 'TP10',
  'entryPrice': "Açılış Fiyatı",
  'entryDate': "Açılış Tarihi",
  'takeProfit': 'Take Profit',
  'exitPrice': 'Kapanış Fiyatı',
  'exitDate': 'Kapanış Tarihi',
  'profitLoss': 'Kâr/Zarar',
  'allTime': 'Tüm Zamanlar',
  'last24': 'Son 24 Saat',
  'last30': 'Son 30 Gün',
  'last7': 'Son 7 Gün',
  'channelSelect': 'Kanal seçin',
  'allChannels': 'Tüm Kanallar',
  'timeSelect': 'Zaman seçin',
  'error': "Hata",
  tradeHistory: 'İşlem Geçmişi',
  totalPnL: 'Toplam K/Z',
  profitLossByApi: 'API bazında kar/zarar',
  tradeSearch: 'İşlem ara...',
  allExchanges: 'Tüm Borsalar',
  realizedPnL: 'Gerçekleşen kar/zarar',
  perCompletedTrade: 'Tamamlanan işlem başına',
  profitableTrades: 'Karlı işlemler',
  ticket: 'Ticket',
  direction: "Yön",
  openPrice: 'Açılış Fiyatı',
  openTime: 'Açılış Zamanı',
  volume: 'Miktar',
  closePrice: 'Kapanış Fiyatı',
  closeTime: 'Kapanış Zamanı',
  status: 'Durum',
  completed: 'Tamamlandı',
  open: "Açılış",
  allTrades: 'Tüm İşlemler',
  'signals.title': 'Sinyaller',
  'signals.activeSignals': 'Aktif Sinyaller',
  'signals.signalHistory': 'Sinyal Geçmişi',
  'signals.channel': 'Kanal',
  'signals.symbol': 'Sembol',
  'signals.direction': 'Yön',
  'signals.openPrice': 'Açılış',
  'signals.openDate': 'Açılış Tarihi',
  'signals.closePrice': 'Kapanış',
  'signals.closeDate': 'Kapanış Tarihi',
  'signals.stopLoss': 'Stop Loss',
  'signals.takeProfit': 'Take Profit',
  'signals.profitLoss': 'Kâr/Zarar',
  'signals.totalTrades': 'TOPLAM İŞLEM',
  'signals.winRate': 'KAZANMA ORANI',
  'signals.totalPL': 'TOPLAM K/Z',
  'signals.avgTrade': 'ORTALAMA İŞLEM',
  'signals.openPositions': 'Açık Pozisyonlar',
  'signals.closedPositions': 'Kapanmış Pozisyonlar',
  'signals.cumulativePL': 'Kümülatif Kar/Zarar',
  'signals.plByChannel': 'Zamana göre kanal bazında kar/zarar',
  'signals.noChartData': 'Grafik için yeterli veri yok.',
  'signals.channelName': 'Kanal Adı:',
  'signals.trendDirection': 'Trend Yönü:',
  'signals.entry1': 'Entry 1:',
  'signals.entry2': 'Entry 2:',
  'signals.sl': 'SL:',
  'signals.tp': 'TP',
  'backtest.noResults': 'Sonuç bulunamadı',
  'backtest.results': 'Backtest Sonuçları',
  'backtest.profitChart': 'Kâr Grafiği',
  'backtest.simulationTrades': 'Simülasyon İşlemleri',
  'backtest.lot': 'Lot',
  'retry': 'Tekrar Dene',
  goBack: "Geri Dön",
  channelOwnerApply: "Kanal Sahibi Başvurusu",
  channelNamePlaceholder: "Kanal adını girin",
  channelLink: "Kanal Linki",
  followerCount: "Takipçi Sayısı",
  fullName: "Ad Soyad",
  email: "E-posta",
  phoneNumber: "Telefon Numarası",
  ownerTelegram: "Telegram Kullanıcı Adı",
  agreementAccept: "Ortaklık Sözleşmesini okudum ve kabul ediyorum",
  submit: "Gönder",
  submitting: "Gönderiliyor...",
  telegram_channels: "Telegram Kanalları",
  total_signals: "Toplam Sinyal",
  success_rate: "Başarı Oranı",
  total_profit: "Toplam Kar",
  subscribers: "Abone Sayısı",
  per_month: "ay",
  channel_loading: "Kanal bilgileri yükleniyor...",
  channel_not_found: "Kanal bilgisi bulunamadı",
  back_to_channels: "Kanallara Dön",
  no_channels_found: "Henüz hiç kanal bulunmuyor.",
  success: "Başarılı",
  application_success: "Başvurunuz başarıyla gönderildi.",
  error_occurred: "Bir hata oluştu",
  accept_agreement_warning: "Lütfen Ortaklık Sözleşmesini kabul edin.",
  fill_all_fields_warning: "Lütfen tüm alanları doldurun.",
  confirmation_title: "Başvuru Onaylandı",
  confirmation_message: "Başvurunuz başarıyla alınmıştır. En kısa sürede sizinle iletişime geçilecektir.",
  confirmation_return: "Anasayfaya Dön",
  go_to_channel: "Kanala Git",
  subscribe: "Abone Ol",
  closed_signals: "Kapanan Sinyaller",
  cumulative_profit_loss: "Kümülatif Kar/Zarar",
  profit_loss_per_channel: "Zamana göre kanal bazında kar/zarar",
  total: "Toplam",
  openDate: "Açılış Tarihi",
  closeDate: "Kapanış Tarihi",
  channelNameLabel: "Kanal Adı",
  subscription_title: "Abonelik",
  adminMenu: "Yönetici Menüsü",
  members: "Üyeler",
  memberNotifications: "Üye Bildirimleri",
  channelNotifications: "Kanal Bildirimleri",
  botChannels: {
    loadError: "Bot Kanalları yüklenemedi",
    unknownDeleteError: "Bilinmeyen silme hatası",
    deleteError: "Silme işlemi başarısız oldu",
    deleteSuccess: "Bot Kanalı başarıyla silindi",
    deleteErrorDetailed: "Bot Kanalı silinirken hata: {{error}}",
    channelId: "Kanal ID",
    channelName: "Kanal Adı",
    status: "Durum",
    actions: "İşlemler",
    admin: "Admin",
    description: "Açıklama",
    registerDate: "Kayıt Tarihi",
    channelImageAlt: "Kanal Resmi",
    title: "Bot Kanalları",
    addChannel: "Kanal Ekle",
    pageDescription: "Sisteme kayıtlı bot kanallarını görüntüleyebilir ve yönetebilirsiniz.",
    searchPlaceholder: "Kanal adı veya ID ile ara...",
    deleteConfirmTitle: "Bot Kanalı Silme Onayı",
    deleteConfirmDesc: "Bu bot kanalını kalıcı olarak silmek istediğinize emin misiniz?",
    confirmDelete: "Evet, Sil",
  },
  subscriptions: "Abonelikler",
  subscriptionPackages: "Abonelik Paketleri",
  'signalsList.title': "Son Sinyaller",
  'signalsList.description': "Kanaldan gelen son işlem sinyalleri",
  'signalsList.viewAll': "Tüm sinyalleri görüntüle →",
  'tradesList.viewAll': "Tüm işlemleri görüntüle →",
  subscriptionHistory: "Abonelik Geçmişi",
  allActiveAndPastSubscriptions: "Aktif ve geçmiş tüm abonelikleriniz",
  ended: "Sona Erdi",
  start: "Başlangıç",
  end: "Bitiş",
  noSubscriptionFound: "Henüz bir aboneliğiniz bulunmuyor.",
  upgradeToPremium: "Premium'a Geç",
  monthlyPlan: "Aylık",
  monthlyAccess: "ay boyunca premium erişim",
  selectPlan: "Paketi Seç",
  enterPassword: "Şifreyi yazınız",
  login: "Giriş Yap",
  // Özellikler
  'Tüm sinyallere erişim': "Tüm sinyallere erişim",
  'Manuel trading': "Manuel trading",
  'Temel destek': "Temel destek",
  'Tanışma Paketi': "Tanışma Paketi",
  'Öncelikli destek': "Öncelikli destek",
  '3 aylık indirim': "3 aylık indirim",
  'Premium destek': "Premium destek",
  '6 aylık indirim': "6 aylık indirim",
  'VIP destek': "VIP destek",
  'Yıllık indirim': "Yıllık indirim",
  threeMonthPlan: "3 Aylık",
  sixMonthPlan: "6 Aylık",
  yearlyPlan: "Yıllık",
  premiumAccess: "boyunca premium erişim",
  accessAllSignals: "Tüm sinyallere erişim",
  manualTrading: "Manuel trading",
  basicSupport: "Temel destek",
  welcomePackage: "Tanışma Paketi",
  prioritySupport: "Öncelikli destek",
  threeMonthDiscount: "3 aylık indirim",
  premiumSupport: "Premium destek",
  sixMonthDiscount: "6 aylık indirim",
  vipSupport: "VIP destek",
  annualDiscount: "Yıllık indirim",
  'settings.title': 'API Ayarları',
  'settings.invalidId': 'Geçersiz ID',
  'settings.apiNotFound': 'API Bulunamadı',
  'settings.loadingError': 'Yükleme Hatası',
  'settings.missingApiId': 'API ID Eksik',
  'settings.autoTrade': 'Otomatik İşlem',
  'settings.autoTradeDescription': 'Otomatik işlem özelliğini aktif et',
  'settings.entryAmount': 'İşlem Miktarı',
  'settings.entryAmountDescription': 'Her işlem için kullanılacak miktar',
  'settings.entryAmountPlaceholder': 'Miktar girin',
  'settings.usdt': 'USDT',
  'settings.entryAmountQuestion': 'İşlem miktarı ne kadar olmalı?',
  'settings.entryAmountExplanation1': 'İşlem Miktarı Nasıl Hesaplanır?\n\nİşlem miktarını belirlemek için, işleme ayırmak istediğiniz tutarı kaldıraç oranıyla çarpmanız yeterlidir. Bu çarpım sonucunda, pozisyonunuzun toplam büyüklüğü (lot miktarı) ortaya çıkar ve bu değeri sistemde “işlem miktarı” alanına yazmanız gerekir.\n\nÖrnek:\n30 dolarlık bir sermaye ile işlem açmak istiyorsunuz ve 20x kaldıraç kullanacaksınız:\n👉 30 × 20 = 600\n\nBu durumda, işlem miktarına yazmanız gereken değer 600 olmalıdır.',
  'settings.entryAmountExplanation2': '',
  'settings.leverage': 'Kaldıraç',
  'settings.leverageDescription': 'İşlemleriniz için kullanılacak kaldıraç oranı',
  'settings.safe': 'Güvenli',
  'settings.risky': 'Riskli',
  'settings.tradeType': 'İşlem Türü',
  'settings.tradeTypeDescription': 'İzole Marjin (Isolated) Nedir?\n\nSadece o pozisyona ayırdığınız sermaye risk altındadır.\nPozisyonunuz likide olursa, sadece o işlemdeki bakiyeyi kaybedersiniz. Diğer bakiyeniz etkilenmez.\n\nÇapraz Marjin (Cross) Nedir?\n\nTüm cüzdan bakiyeniz pozisyonu destekler.\nPozisyon zarar ederse sistem diğer bakiyenizi de kullanarak likidasyonu geciktirir.\n\nÖzetle:\nİzole = sadece o pozisyon riske girer.\nCross = tüm bakiyen riske girer ama daha geç patlar.',
  'settings.isolated': 'İzole',
  'settings.cross': 'Çapraz',
  'settings.profitTradeSettings': 'Kar Al Ayarları',
  'settings.profitTradeSettingsDescription': 'Sabit Kâr Al Nedir?\n\nSabit Kâr Al, işlemin açıldığı anda belirlediğiniz spot fiyata göre, seçtiğiniz kâr yüzdesine ulaşıldığında pozisyonun tamamının otomatik olarak kapatılmasını sağlayan özelliktir.\n\nÖrnek:\nSpot fiyat 1000 USDT ise ve siz %10 sabit kâr al hedefi belirlediyseniz,\nfiyat 1100 USDT’ye ulaştığında işleminiz otomatik olarak kapanır ve kâr alınır.\n\nYüzdelik Kâr Al Nedir?\n\nİşleminizin belirli bir kısmını, kâr al (TP) seviyelerine ulaşıldığında otomatik olarak kapatmak için kullanılan ayardır.\n\nÖrnek:\nEğer TP1 seviyesine ulaşıldığında işlemin %50’sini kapatmak istiyorsanız, TP1 ayarını %50 olarak belirlemeniz gerekir.',
  'settings.selectEntryType': 'Giriş türünü seçin',
  'settings.closed': 'Kapalı',
  'settings.percentage': 'Yüzde',
  'settings.fixedAmount': 'Sabit Miktar',
  'settings.percentSymbol': '%',
  'settings.tp1': 'TP1',
  'settings.tp2': 'TP2',
  'settings.tp3': 'TP3',
  'settings.tp4': 'TP4',
  'settings.tp5': 'TP5',
  'settings.tp6': 'TP6',
  'settings.tp7': 'TP7',
  'settings.tp8': 'TP8',
  'settings.tp9': 'TP9',
  'settings.tp10': 'TP10',
  'settings.tpLevel': 'TP Seviyesi',
  'settings.stoplossTradeSettings': 'Zarar Durdur Ayarları',
  'settings.stoplossTradeSettingsDescription': 'Bu ayarda işlemde belirtilen zarar durdur (SL) emri uygulanmakdır.',
  'settings.selectStopLossStrategy': 'Zarar durdurma stratejisi seçin',
  'settings.useSignalSL': 'Sinyal SL Kullan',
  'settings.customStopLoss': 'Özel Stop Loss',
  'settings.customStopLossInput': 'Stop Loss Seviyesi',
  'settings.customStopLossHelp': 'Pozisyon açılış fiyatına göre yüzdelik zarar durdurma seviyesi',
  'settings.specificLossPercentage': 'Özel Stop Loss Yüzdesi (%)',
  'settings.stopLossActionSettings': 'Zarar Durdur Aksiyon Ayarları',
  'settings.stopLossActionDescription': 'Stop loss tetiklendiğinde yapılacak işlemler',
  'settings.selectAction': 'Aksiyon seçin',
  'settings.trailStopAction': 'Trailing Stop',
  'settings.costWithdrawAction': 'Maliyetine Çek',
  'settings.specificLossAction': 'Belirli Zararda Kapat',
  'settings.specificLossLabel': 'Zarar Yüzdesi',
  'settings.specificLossQuestion': 'Bu özellik nasıl çalışır?',
  'settings.specificLossExplanation': 'Belirlenen zarar yüzdesine ulaşıldığında pozisyon otomatik olarak kapatılır.',
  'settings.costWithdraw': 'Maliyetine Çekme',
  'settings.costWithdrawDescription': 'Maliyete Çek Nedir?\n\nMaliyete çek özelliği, fiyat belirlediğiniz Kâr Al (TP) seviyesine ulaştığında, mevcut zarar durdur (stop loss) seviyesini otomatik olarak işleme giriş fiyatına taşır. Böylece işlem risksiz hale gelir; yani fiyat geri dönerse zarar etmeden çıkarsınız.\n\n⸻\n\nÖrnek:\nGiriş fiyatınız: 1000 USDT\nStop loss: 950 USDT\nTP1: 1100 USDT\n➡️ Fiyat 1100’e ulaştığında, stop loss otomatik olarak 1000’e (maliyete) çekilir.\nBöylece işlem yukarı giderse kâr artar, geri dönerse sıfır zararla kapanır.',
  'settings.selectLevel': 'Seviye seçin',
  'settings.none': 'Yok',
  'settings.costWithdrawQuestion': 'Maliyetine çekme nasıl çalışır?',
  'settings.costWithdrawExplanation1': 'Seçilen TP seviyesine ulaşıldığında stop loss seviyesi maliyete çekilir.',
  'settings.costWithdrawExplanation2': 'Bu sayede en kötü durumda başabaş çıkılır.',
  'settings.costWithdrawExplanation3': 'Piyasa tersine dönerse kazanç korunmuş olur.',
  'settings.costWithdrawExplanation4': 'Risk yönetimi için önemli bir stratejidir.',
  'settings.trailStop': 'Trailing Stop',
  'settings.trailStopDescription': 'Trailing Stop (İz Süren Stop) Nedir?\n\nTrailing Stop, işleminiz belirlediğiniz bir kâr al (TP) seviyesine ulaştığında, stop loss seviyesini otomatik olarak yukarı taşır. Böylece kazanç korunur, işlem daha fazla kâr potansiyeli sunarken risk sıfıra yaklaşır.\n\nNasıl Çalışır?\n✅ TP1 seviyesine ulaşıldığında\n✅ Stop loss otomatik olarak giriş fiyatınıza (maliyetinize) çekilir\n✅ Fiyat yükselmeye devam ederse kârınız artar\n✅ Fiyat geri dönerse, en azından zarar etmeden çıkarsınız\n\nÖrnek:\nSpot fiyat: 1000 USDT\nTP1: 1100 USDT\nSL: 950 USDT\n➡️ Fiyat 1100’e ulaştığında stop loss artık 1000’e (maliyete) çekilir.\nFiyat daha yukarı giderse işlem devam eder, geri dönerse sıfır zararla kapanır.',
  'settings.trailStopQuestion': 'Trailing stop nasıl çalışır?',
  'settings.trailStopExplanation': 'Seçilen TP seviyesine ulaşıldığında stop loss otomatik olarak kar bölgesine taşınır ve fiyat yükseldikçe yukarı çekilir.',
  'settings.maxOrders': 'Maksimum Emir',
  'settings.maxOrdersDescription': 'Aynı anda açık olabilecek maksimum emir sayısı',
  'settings.save': 'Kaydet',
  'settings.saving': 'Kaydediliyor...',
  'settings.saveSuccess': 'Ayarlar başarıyla kaydedildi.',
  'settings.saveError': 'Ayarlar kaydedilirken bir hata oluştu.',
  addSignal: 'Sinyal Ekle',
  addNewSignal: 'Yeni Sinyal Ekle',
  fillSignalDetails: 'Sinyal detaylarını doldurun',
  exchange: "Borsa",
  side: "Yön",
  pnl: "Kar/Zarar",
  action: "İşlem",
  close: "Kapat",
  trend: 'Trend',
  selectTrend: 'Trend seçin',
  long: "LONG",
  short: "SHORT",
  stopLossPercentage: 'Stop Loss Yüzdesi',
  entryRangePercentage: 'Giriş Aralığı Yüzdesi',
  takeProfitCount: 'Take Profit Sayısı',
  takeProfitRangePercentage: 'Take Profit Aralık Yüzdesi',
  createSignal: 'Sinyal Oluştur',
  signal_channels: "Sinyal Kanalları",
  addYourChannel: "Kanalını Ekle",
  welcomeMessage: "Hoş geldin,",
  openTradesLabel: "adet işlem devam ediyor",
  apiStatusLabel: "adet borsa hesabı bağlı",
  addApiKey: "API Anahtarı Ekle",
  noApiKeyCta: "Henüz API anahtarınız yok. Borsa hesabınızı bağlamak için tıklayın.",
  noOpenTrades: "Açık işlem bulunmuyor",
  waiting: "Beklemede",
  openStatus: "Açık",
  recentTrades: "Son İşlemler",
  yourRecentTrades: "En son işlemleriniz",
  openClose: "Açılış/Kapanış",
  noTradesFound: "İşlem bulunmuyor",
  unknown: "Bilinmiyor",
  closed: "Kapalı",
  loginError: "Giriş Hatası",
  loginWithTelegram: "Telegram ile Giriş",
  pleaseLoginWithTelegram: "Lütfen Telegram üzerinden giriş yapınız.",
  pageNotFound: "Oops! Sayfa bulunamadı",
  returnToHome: "Anasayfaya Dön",
  copied: "Kopyalandı",
  copiedToClipboard: "{{field}} panoya kopyalandı.",
  copyError: "Kopyalama başarısız.",
  fillAllFields: "Lütfen tüm alanları doldurun.",
  sessionNotFound: "Oturum bilgisi bulunamadı",
  userNotFound: "Kullanıcı bulunamadı",
  newApiKey: "Yeni API Anahtarı:",
  addApiKeyError: "API anahtarı eklenemedi",
  newApiKeyNotFound: "Yeni API anahtarı bulunamadı",
  apiKeyAdded: '"{{name}}" API anahtarı başarıyla eklendi.',
  apiKeyAddError: "API anahtarı eklenirken hata:",
  addNewApiKey: "Yeni API Anahtarı Ekle",
  addNewApiKeyDesc: "Borsanıza ait API anahtar bilgilerinizi buraya girin. Bu bilgiler otomatik işlemler için kullanılacaktır.",
  exchangeType: "Borsa Tipi",
  name: "İsim",
  apiKeyNamePlaceholder: "Örn: Binance Vadeli",
  apiKeyNameDesc: "Bu anahtar için hatırlamanıza yardımcı olacak bir isim girin.",
  apiKeyPlaceholder: "API Key'inizi girin",
  apiSecretPlaceholder: "API Secret'inizi girin",
  apiSecretDesc: "API anahtarınızı ve secret'ınızı kimseyle paylaşmayın.",
  signalChannel: "Sinyal Kanalı",
  searchChannelPlaceholder: "Kanal adı veya ID ile ara...",
  selectedChannel: "Seçilen kanal",
  subscriptionPackage: "Abonelik Paketi",
  select: "Seçiniz",
  cancel: "İptal",
  adding: "Ekleniyor...",
  save: "Kaydet",
  apiKeyIdNotFound: "API anahtarı ID bulunamadı",
  apiKeyNotFound: "API anahtarı bulunamadı",
  apiKeyLoadError: "API anahtarı yüklenirken hata:",
  apiKeyLoadErrorText: "API anahtarı yüklenemedi",
  apiKeyUpdated: 'API anahtarı başarıyla güncellendi.',
  apiKeyUpdateError: "API anahtarı güncellenirken hata:",
  apiKeyUpdateErrorText: "API anahtarı güncellenemedi.",
  editApiKey: "API Anahtarını Düzenle",
  editApiKeyDesc: "Borsa API anahtar bilgilerinizi güncelleyin.",
  saving: "Kaydediliyor...",
  apiChannelDesc: "API anahtarının dinleyeceği sinyal kanalını seçin.",
  deleteApiKeyConfirm: "Bu API anahtarını silmek istediğinizden emin misiniz?",
  apiKeyDeleted: "API anahtarı başarıyla silindi.",
  apiKeyDeleteError: "API anahtarı silinirken bir hata oluştu.",
  networkError: "Network response was not ok",
  fetchDetailsError: "Detaylar alınamadı",
  deleteFailed: "Silme işlemi başarısız oldu",
  apiKeyDeletedSuccess: "API anahtarı başarıyla silindi",
  adminApiKeys: {
    title: "API Anahtarları",
    description: "Kullanıcıların API anahtarlarını görüntüleyebilir ve yönetebilirsiniz.",
    searchPlaceholder: "Kullanıcı adı veya isim ile ara...",
    user: "Kullanıcı",
    apiName: "API Adı",
    apiType: "API Türü",
    packageEnd: "Paket Bitiş",
    channel: "Kanal",
    packageStart: "Paket Başlangıç",
    lotsize: "Lotsize",
    leverage: "Leverage",
    marginType: "Margin Type",
    maxOrders: "Max Orders",
    autoTrade: "Auto Trade",
    actions: "İşlemler",
    deleteConfirmTitle: "Silme Onayı",
    deleteConfirmDesc: "Bu API anahtarını kalıcı olarak silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.",
  },
  on: "Açık",
  off: "Kapalı",
  delete: "Sil",
  edit: "Düzenle",
  admin: {
    notLoggedIn: "Admin olarak giriş yapmadınız veya oturumunuz sona erdi. Lütfen tekrar giriş yapın.",
    faq: {
      addSuccess: "Soru başarıyla eklendi!",
      addError: "Kayıt eklenemedi",
      addNewTitle: "Yeni Soru Ekle",
      addNewDesc: "Yeni bir sıkça sorulan soru ekleyebilirsiniz.",
      questionInfo: "Soru Bilgileri",
      question: "Soru",
      questionPlaceholder: "Soruyu yazın...",
      answer: "Cevap",
      answerPlaceholder: "Cevabı yazın...",
    }
  },
  fromLastMonth: "geçen aya göre",
  newTrades: "yeni işlem",
  thisMonth: "bu ay",
  dashboard: "Kontrol Paneli",
  switchToLightMode: "Aydınlık moda geç",
  switchToDarkMode: "Karanlık moda geç",
  noTradeOnPage: "Bu sayfada gösterilecek işlem yok.",
  tradeRecordNotFound: "İşlem kaydı bulunamadı.",
  previousPage: "Önceki Sayfa",
  nextPage: "Sonraki Sayfa",
  filterByExchange: "Borsaya Göre Filtrele",
  profit: "Kâr",
  "faq.title": "S.S.S",
  tradeStatus: {
    waiting: "Bekliyor",
    open: "Açık",
    completed: "Tamamlandı",
    failed: "Hatalı",
    unknown: "Bilinmeyen"
  },
  orderError: "Emir Hatası: {{error}}",
};

export default tr;